### ISSUE TITLE
[BERT_pytorch] RuntimeError: CUDA error: misaligned address

### ISSUE THREAD

**Issue by Chillee** [pytorch/torchdynamo#1016]
Command: `./benchmarks/torchbench.py -dcuda --float32 --inductor --training  --only BERT_pytorch --use-eval-mode`

There are a bunch of models that started failing with inductor yesterday. I've verified that BERT_pytorch is failing with this error, I haven't checked the other models.

<img width="643" alt="image" src="https://user-images.githubusercontent.com/6355099/186605050-d3dd52e6-8674-49da-b0d3-1a9a56d6963c.png">

```
  File "/scratch/chilli/fresh/pytorch/torch/cuda/__init__.py", line 501, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
ERROR
CUDA error: misaligned address
```

**Comment by desertfire** [comment]
This may be related to my PR https://github.com/pytorch/torchdynamo/pull/981, and also the same as what you reported at https://github.com/pytorch/torchdynamo/issues/965#issuecomment-1226957794. So how CI didn't catch it. Let me work on a fix.

**Comment by Chillee** [comment]
@desertfire I think CI didn't catch it since the nightlies run with `--use-eval-mode` and our CI doesn't?

**Comment by desertfire** [comment]
https://app.circleci.com/pipelines/github/pytorch/torchdynamo/1521/workflows/109ea192-b897-456c-af84-9f226dea2b69/jobs/2330, CI run does use `--use-eval-mode`. I suspect the specific failure has something to do with the environment, like CUDA version.

Let me close this one now as it is fixed with a guarding unit test.
