### ISSUE TITLE
float16-typed tensor introduced by CUDA target for backends

### ISSUE THREAD

**Issue by shingjan** [pytorch/torchdynamo#1033]
Hi, there is a couple models whose CUDA subgraph will contain tensor with different data types compared to CPU. One example I have is `hf_Reformer`. The following is my repro:
```
python benchmarks/torchbench.py --backend tvm --only hf_Reformer --device cuda
```
In one subgraph of the aforementioned model, there is a operator called `einsum`. On LLVM/CPU, the arguments of this ops looks like the following:
```
 a = torch.rand((1, 12, 4096, 64), dtype=torch.float32)
 b = torch.rand((12, 64, 1, 64), dtype=torch.float32)
 c = torch.einsum("bmtd,mdhr->bmhtr", a, b)
```
But when switched to CUDA, argument `a`'s dtype is changed to `float16`. And if we run the above code snippet in pytorch nightly with a being `float16`, the error stacktrace looks like:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/anaconda3/envs/torchdynamo/lib/python3.8/site-packages/torch/functional.py", line 360, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: expected scalar type Float but found Half
```
as this operator doesn't seem to support float16. One caveat is that this models runs fine with `--backend ts --device cuda`. So here are my questions:
1. Would torchdynamo somehow tweak the data type of tensors for kernels/operators based on the hardware target while partitioning the model?
2. Would TorchScript support/handle this data type mismatch case despite that pytorch itself doesn't support it?

cc: @jansel Would love your insight on this!
Thanks

**Comment by jansel** [comment]
That is strange.  I would not expect TorchDynamo to modify any dtypes.  One possibility is this change is in the model's code.  float16 is only well supports on GPU, so many models will only use it if the device is cuda.

I don't think this is related to TorchScript, because `--backend=eager` also works in addition to  `--backend=ts`.

You could try running with `--float32`, which will cast all the model params and inputs to float32.

**Comment by shingjan** [comment]
@jansel Thanks a lot for the `--float32` tip! It unblocks my repro on `hf_Reformer`. Would there be any side effect as now we are virtually rewriting the inputs and params of those models with float32 enforced? I am only asking that bcoz those models are expected to use float16 on gpu.

**Comment by jansel** [comment]
It depends on the model.  There is the side effect that you are now running a "different" model with changed dtypes.  Most models work with multiple float dtypes, but it could introduce issues.  Usually the issues come from lowering precision though (e.g. overflows) not raising precision.

**Comment by shingjan** [comment]
Thanks @jansel! close this as unblocked.
