### ISSUE TITLE
SGD.step() failure: RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

### ISSUE THREAD

**Issue by yanboliang** [pytorch/torchdynamo#1076]
Repro:
```
torchdynamo.config.fake_tensor_propagation = False

input = torch.ones([10, 10])
model = torch.nn.Sequential(*[torch.nn.Linear(10, 10) for _ in range(2)])
opt_model = torchdynamo.optimize("eager")(model)
opt_model(input).sum().backward()

optimizer = optim.SGD(opt_model.parameters(), lr=5e-5)
opt_fn = torchdynamo.optimize("eager")(optimizer.step)
opt_fn()
```
Error:
```
 ========== TorchDynamo Stack Trace ==========
Traceback (most recent call last):
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/variables/tensor.py", line 142, in create
    example_value = wrap_fake_exception(
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/variables/tensor.py", line 114, in wrap_fake_exception
    return func()
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/variables/tensor.py", line 143, in <lambda>
    lambda: cls.run_proxy(proxy, args, kwargs, nnmodule)
  File "/data/home/ybliang/Meta/torchdynamo/torchdynamo/variables/tensor.py", line 87, in run_proxy
    return getattr(args[0], proxy.node.target)(*args[1:], **kwargs)
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
```
It was caused by [this line](https://github.com/pytorch/pytorch/blob/master/torch/optim/sgd.py#L245) where we do in-place add on leaf tensor. But I'm still not clear why it doesn't fail in PyTorch.

**Comment by jansel** [comment]
Does this work if you disable fake_tensors?

**Comment by yanboliang** [comment]
I tried to disable fake tensor, it still doesn't work. But I remember it works last Thursday if I turn off fake tensor, so I suspect it's a regression issue. Will dig into and update later!

**Comment by ezyang** [comment]
It might be due to https://github.com/pytorch/torchdynamo/commit/2eef7fc79bacffc2dc533402249e15cbfce8cd71

**Comment by yanboliang** [comment]
This is regression issue caused by https://github.com/pytorch/torchdynamo/pull/1007
* Before that commit, disable fake_tensors works well, enable fake_tensor doesn't work well.
* After that commit, neither of disable/enable fake_tensors works well.

**Comment by yanboliang** [comment]
I think this brings good reason to add an end-to-end model training test/benchmark to avoid regression.

**Comment by anijain2305** [comment]
Repro

~~~

def use_grad(func):
    def _use_grad(*args, **kwargs):
        prev_grad = torch.is_grad_enabled()
        try:
            torch.set_grad_enabled(False)
            ret = func(*args, **kwargs)
        finally:
            torch.set_grad_enabled(prev_grad)
        return ret
    return _use_grad

@use_grad
def fn(param):
    param.add_(torch.randn(4))

x = torch.nn.Parameter(torch.randn(4))
fn(x)

opt_fn = torchdynamo.optimize("eager")(fn)
x = torch.nn.Parameter(torch.randn(4))
opt_fn(x)

~~~


This is likely because when during TorchDynamo `dynamic_propagation`, we do not run the torch operations with the correct grad state. Looking more into it.

**Comment by anijain2305** [comment]
https://github.com/pytorch/torchdynamo/pull/1260 Fixed this. Closing.
