### ISSUE TITLE
torchdynamo+fx2trt hangs torchbench opacus_cifar10

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/torchdynamo#109]
Command to reproduce: `python run.py opacus_cifar10 -d cuda -t eval --torchdynamo fx2trt`

The process never halts (waited for 1 hour)

**Comment by frank-wei** [comment]
It is a tracer issue. Need more efforts to dive in.

**Comment by anijain2305** [comment]
Closing the issue as this seems stale. Feel free to reopen.
