### ISSUE TITLE
Generate buck targets for inductor, inductor generated kernels are not runnable in fbcode atm

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/torchdynamo#1097]
This needs to:

1) Redirect the compile cache somewhere TARGETS works
2) Produce a valid TARGETS file so we can buck run the generated py file
3) Probably get an e2e test in fbcode

**Comment by malfet** [comment]
Claiming for myself, have work-in-progress diff/PR

**Comment by malfet** [comment]
And they are now, closing.
