### ISSUE TITLE
regression for fp16

### ISSUE THREAD

**Issue by soumith** [pytorch/torchdynamo#1119]
HuggingFace models regressed from 1.95x -> 1.77x without change in coverage (36/43 in both cases).

2 days ago:
```
73%, 35/48  | 84%, 36/43  | 80%, 53/66  |
 1.86x    |    1.95x    |    1.65x   
```
-> 

last night:

```
inductor_cudagraphs | 77%, 37/48 | 84%, 36/43  | 97%, 64/66
inductor_cudagraphs |   1.82x    |    1.77x    |    1.59x 
```

Right now i have to manually spot these things.
It would be a great visual aid to plot a line graph over time.

**Comment by voznesenskym** [comment]
> It would be a great visual aid to plot a line graph over time.

We could persist historical or last run results in the repo @anijain2305 - and produce a chart / delta column respectively. Thoughts?

**Comment by jansel** [comment]
`git bisect` points to #1096

I think this disabled functionalization for inductor.  

cc @Chillee

**Comment by anijain2305** [comment]
> > It would be a great visual aid to plot a line graph over time.
> 
> We could persist historical or last run results in the repo @anijain2305 - and produce a chart / delta column respectively. Thoughts?

Yes, I do have janky scripts here - https://github.com/anijain2305/torchdynamo_dashboard. I will also publish a diff from the last nightly to identify these regressions little bit easily. The logs are already persisted in shared filesystem in the AWS clusters.

**Comment by jansel** [comment]
Looks fixed in https://github.com/pytorch/torchdynamo/issues/681#issuecomment-1236277236

**Comment by anijain2305** [comment]
Lets keep this open as an action item for me to publish a diff.

**Comment by anijain2305** [comment]
Sample here - https://github.com/pytorch/torchdynamo/issues/681#issuecomment-1238672152



![Image](https://user-images.githubusercontent.com/13822661/188745490-28f700d7-876f-45b4-b912-89aed65fa3fa.png)

Should take a couple of days to land and show up.
