### ISSUE TITLE
NameError - torch is not defined - speech_transformer

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#1126]
Repro -  `TORCHDYNAMO_DEBUG_FUNCTION=forward python benchmarks/torchbench.py --training --float32 --backend=eager --use-eval-mode --only=speech_transformer`

And a diff

~~~
diff --git a/torchdynamo/convert_frame.py b/torchdynamo/convert_frame.py
index 7fa490d..c3af426 100644
--- a/torchdynamo/convert_frame.py
+++ b/torchdynamo/convert_frame.py
@@ -232,6 +232,9 @@ def convert_frame_assert(compiler_fn: Callable, guard_export_fn=None, one_graph=
             and os.environ.get("TORCHDYNAMO_DEBUG_FUNCTION") != code.co_name
         ):
             return None
+
+        if "encoder" not in code.co_filename:
+            return None
         if code.co_name == "<genexpr>" and code.co_filename.endswith(
             ("transformers/file_utils.py", "transformers/utils/generic.py")
         ):
~~~

This one leads to error like 
~~~
NameError: name 'torch' is not defined
ERROR
name 'torch' is not defined
~~~

I do not fully understand how globals are handled during inlining. The file containing the parent function has import `import torch.nn as nn` (no `import torch`), but the child function file has `import torch`. It seems that children imports are not passed on the parent function while inlining.

cc @voznesenskym @jansel

**Comment by voznesenskym** [comment]
Repro confirmed. I have a theory here, looking into this.

**Comment by voznesenskym** [comment]
Yeah this needs instruction translation for imports, I think.

Just (hilariously) jamming in 
```
hack_output.append(create_instruction("LOAD_CONST", 2, 0))
hack_output.append(create_instruction("LOAD_CONST", 0, None))
hack_output.append(create_instruction("IMPORT_NAME",  0, "torch"))
hack_output.append(create_instruction("STORE_FAST", 1, "torch"))
instructions = hack_output + instructions
```

Gets me past this import error, onto another one:

```
ModuleNotFoundError: No module named 'torchbenchmark.models.speech_transformer.speech_transformer.transformer.get_non_pad_mask'
```

Obviously not a real fix - but demonstrative of the issue.

There's also another problem here - when we inline code the stack trace is wrong.

**Comment by anijain2305** [comment]
I somehow jammed it in using https://github.com/pytorch/torchdynamo/pull/1128. But, idk.
