### ISSUE TITLE
Investigate sources of higher peak memory footprint

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#1132]
Using `pit_b_224` model to debug memory footprint issue

Eager - `15.27` GB
Aot_eager - `32.24` GB

* A major increase in footprint is coming from functionalization during [tracing](https://github.com/pytorch/functorch/blob/main/functorch/_src/aot_autograd.py#L288).  On disabling functionalization, memory footprint is `18.41`.
* Inside aot_autograd (after functionlization is turned off), tracing jumps the memory footprint to `15.27` GB. But, then it increases further during the backward pass of the custom autograd.Function object at runtime to `18.41` GB

------

Update - Sept 20

pit_b_224
eager - 12.04 GB
aot_eager - 15.18 GB
inductor - 14.47 GB

**Comment by anijain2305** [comment]
> do you think it's an explicit goal in dynamo for "non memory-planning backends" (like Aot_eager, or Aot_cudagraphs) to have memory footprint parity with eager mode?

It's a good question. I chose `aot_eager` just because `aot_eager` represents whats going on in TorchInductor lowering.

Imo, I think having `aot_eager` work well with re-inplacing should also be done with high priority. Developers might use `aot_eager` setup to get the graphs for their own backends, and not supporting eager batch size will be a bad UX there. 

For `aot_cudagraphs`, if we have fake tensor ON and re-inplacing, do we need anything else? There is definitely some interest in `aot_cudagraphs`.

**Comment by bdhirsh** [comment]
> Imo, I think having aot_eager work well with re-inplacing should also be done with high priority. Developers might use aot_eager setup to get the graphs for their own backends, and not supporting eager batch size will be a bad UX there.

Yeah, that seems totally fair. I'll start to take another swing at turning re-inplacing on in the aot_eager backend

> For aot_cudagraphs, if we have fake tensor ON and re-inplacing, do we need anything else? There is definitely some interest in aot_cudagraphs.

AFAIK, that should be everything. I guess we'll have to turn them both on and confirm that nothing breaks though.

**Comment by Chillee** [comment]
I don't think missing re-inplacing is the cause of the higher memory footprint.

**Comment by jansel** [comment]
Functionalization should not double memory usage as long as we properly free intermediates.  I think this is more likely a memory bug.

**Comment by Chillee** [comment]
@bdhirsh To clarify, the fact that it's happening *during* tracing means that it's not the *result* of functionalization that has higher peak memory, it's something that functionalization is doing during tracing.

So a re-inplacing pass wouldn't change things. OTOH, I suspect using faketensors during aotdispatcher would just fix things?

**Comment by bdhirsh** [comment]
> To clarify, the fact that it's happening during tracing means that it's not the result of functionalization that has higher peak memory, it's something that functionalization is doing during tracing.

Oh yep. Totally agreed that we need fake tensors during aotdispatcher to fix the higher peak memory from tracing. I just mean that I think we'll need both - fake tensors during tracing, *and* re-inplacing afterwards. (Although like you pointed out, those might not be the only two causes of higher peak memory).

**Comment by Chillee** [comment]
I think higher peak memory afterwards is just coming from the "backwards pass holding onto activations for the duration of the backwards pass". I'll make an issue for it.

**Comment by anijain2305** [comment]
Closing in favor of https://github.com/pytorch/torchdynamo/issues/1598
