### ISSUE TITLE
[fx2trt][fx] Proxy' object does not support item assignment

### ISSUE THREAD

**Issue by frank-wei** [pytorch/torchdynamo#117]
Error msg like 
Proxy' object does not support item assignment
Affected models: ~~hf_Longformer~~, pyhpc_isoneutral_mixing, speech_transformer

**Comment by frank-wei** [comment]
Solved the setitem blocker. There are some ops unsupported:
as_strided: ((torch.float16,), {})
torch.functional.einsum: ((None, torch.float16, torch.float16), {})
new_empty: ((torch.float16,), {})
new_ones: ((torch.float16,), {})
torch.masked_fill: ((torch.float32, torch.bool), {})
pad does not support value != 0

**Comment by ciciewang** [comment]
still have two ops not supported, will get these done this week.

**Comment by frank-wei** [comment]
Added the op support for setitem. But the performance is not good. TRT is slow on slicing operations. 
hf_longformer also has many as_strided and einsum operations which are slow to implement on TRT. Overall, hf_longformer is not good candidate for TRT in perf perspective.

**Comment by frank-wei** [comment]
speech_transformer: need to handle where input=0 or constant
%setitem : [#users=0] = call_function[target=operator.setitem](args = (%new_ones, (0, slice(getitem, None, None)), 0), kwargs = {})

**Comment by frank-wei** [comment]
speech_transformer is able to run now but the performance is 0.627x since there are 72 subgraphs. It is not a good candidate for TRT.
