### ISSUE TITLE
TorchDynamo log.debug is not getting printed for TorchDynamo tests

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#1184]
While running the Dynamo with `pytest`, even when I switch `torchdynamo.config.log_level` to DEBUG, I dont see `log.debug` statements printed out. Same problem exists when PyTorch tests are run with Dynamo.

**Comment by jansel** [comment]
See https://docs.pytest.org/en/7.1.x/how-to/logging.html

And [pytest.ini](https://github.com/pytorch/torchdynamo/blob/main/pytest.ini)

**Comment by williamwen42** [comment]
#1197 does not address issue of debug logs showing up when `torchdynamo.config.log_level` is set to `DEBUG`.
