### ISSUE TITLE
torchbench models hf_Bert, hf_GPT2_large failing with `A view was created in no_grad mode...`

### ISSUE THREAD

**Issue by davidberard98** [pytorch/torchdynamo#1189]
hf_Bert (and hf_GPT2_large) fail with this error:

```
Traceback (most recent call last):
  File "run.py", line 271, in <module>
    run_one_step(test, model_flops=model_flops, model=m, export_dcgm_metrics_file=export_dcgm_metrics_file, stress=args.stress)
  File "run.py", line 61, in run_one_step
    func()
  File "/fsx/users/dberard/scratch-local/bench-fast/benchmark/torchbenchmark/util/model.py", line 188, in invoke
    self.train()
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/dberard/scratch-local/bench-fast/benchmark/torchbenchmark/util/framework/huggingface/model_factory.py", line 111, in train
    def train(self):
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/torchdynamo/eval_frame.py", line 166, in _fn
    return fn(*args, **kwargs)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 889, in forward
    return compiled_f(
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 880, in new_func
    return compiled_fn(args)
  File "/data/home/dberard/miniconda/envs/bench-fast/lib/python3.8/site-packages/functorch/_src/aot_autograd.py", line 228, in g
    return f(*args)
RuntimeError: A view was created in no_grad mode and its base or another view of its base has been modified inplace with grad mode enabled. Given that this use case is ambiguous and error-prone, it is forbidden. You can clarify your code by moving both the view and the inplace either both inside the no_grad block (if you don't want the inplace to be tracked) or both outside (if you want the inplace to be tracked).
```

This issue is probably in the optimizer, because commenting out `optimizer.step()` causes the error to go away. https://github.com/pytorch/benchmark/blob/main/torchbenchmark/util/framework/huggingface/model_factory.py#L115

Repro: run torchbench with https://github.com/pytorch/benchmark/pull/1173:
```
python run.py hf_Bert -t train -m eager -d cuda --torchdynamo inductor
```

**Comment by davidberard98** [comment]
Note: commenting out the `optimizer.step()` line also removes many lines of thesee warnings:
```
torchinductor.ir: [WARNING] Using FallbackKernel: torch.ops.aten.addcdiv_.default
torchinductor.ir: [WARNING] Using FallbackKernel: torch.ops.aten.addcmul_.default
torchinductor.ir: [WARNING] Using FallbackKernel: torch.ops.aten.addcdiv_.default
torchinductor.ir: [WARNING] Using FallbackKernel: torch.ops.aten.addcmul_.default
...
```

**Comment by wconstab** [comment]
cc @mlazos seen this before on your optimizer work?  or anyone else @anijain2305 @voznesenskym

**Comment by anj-s** [comment]
cc @voznesenskym  This is the issue I ran into when benchmarking inductor for a GPT-3 style model. @torchdynamo.optimize("inductor")   wps: 14.473 for the first step before failing with the error: https://www.internalfb.com/phabricator/paste/view/P528342256

For comparison:
@torchdynamo.optimize("eager")   wps: 5290.917
@torchdynamo.optimize("aot_nop") wps: 4618.392
@torchdynamo.optimize("nvfuser") wps: 10289.557
@torchdynamo.optimize("aot_nvfuser")  wps: 7606.426
@torchdynamo.optimize("aot_cudagraphs") wps: 6436.990

**Comment by voznesenskym** [comment]
> cc @mlazos seen this before on your optimizer work? or anyone else @anijain2305 @voznesenskym

No, interestingly, I've never seen this, but I wonder why anything is made in no_grad mode here - let me take a look.

**Comment by voznesenskym** [comment]
> cc @voznesenskym This is the issue I ran into when benchmarking inductor for a GPT-3 style model. @torchdynamo.optimize("inductor") wps: 14.473 for the first step before failing with the error: https://www.internalfb.com/phabricator/paste/view/P528342256
> 
> For comparison: @torchdynamo.optimize("eager") wps: 5290.917 @torchdynamo.optimize("aot_nop") wps: 4618.392 @torchdynamo.optimize("nvfuser") wps: 10289.557 @torchdynamo.optimize("aot_nvfuser") wps: 7606.426 @torchdynamo.optimize("aot_cudagraphs") wps: 6436.990

Interesting - I wonder if we regressed something. Can you share the script? Internal diff is fine.

**Comment by voznesenskym** [comment]
Confirmed.

**Comment by anj-s** [comment]
> > cc @voznesenskym This is the issue I ran into when benchmarking inductor for a GPT-3 style model. @torchdynamo.optimize("inductor") wps: 14.473 for the first step before failing with the error: https://www.internalfb.com/phabricator/paste/view/P528342256
> > For comparison: @torchdynamo.optimize("eager") wps: 5290.917 @torchdynamo.optimize("aot_nop") wps: 4618.392 @torchdynamo.optimize("nvfuser") wps: 10289.557 @torchdynamo.optimize("aot_nvfuser") wps: 7606.426 @torchdynamo.optimize("aot_cudagraphs") wps: 6436.990
> 
> Interesting - I wonder if we regressed something. Can you share the script? Internal diff is fine.

Updated the [paste](https://www.internalfb.com/phabricator/paste/view/P528452557) with location of the script and repro commands.

**Comment by voznesenskym** [comment]
> > > cc @voznesenskym This is the issue I ran into when benchmarking inductor for a GPT-3 style model. @torchdynamo.optimize("inductor") wps: 14.473 for the first step before failing with the error: https://www.internalfb.com/phabricator/paste/view/P528342256
> > > For comparison: @torchdynamo.optimize("eager") wps: 5290.917 @torchdynamo.optimize("aot_nop") wps: 4618.392 @torchdynamo.optimize("nvfuser") wps: 10289.557 @torchdynamo.optimize("aot_nvfuser") wps: 7606.426 @torchdynamo.optimize("aot_cudagraphs") wps: 6436.990
> > 
> > 
> > Interesting - I wonder if we regressed something. Can you share the script? Internal diff is fine.
> 
> Updated the [paste](https://www.internalfb.com/phabricator/paste/view/P528452557) with location of the script and repro commands.

Thanks :) 

I tracked this down to `CreationMeta::NO_GRAD_MODE` being set, I need to see if it's correct. ATM, torchdynamo looks like its handling the grad mode correctly (at first blush). I'm looking into wether GradMode matches what we expect it to.

**Comment by yanboliang** [comment]
I hit this issue when I was running the end-to-end training loss benchmark. The extra info I can provided is: this error only happens when running on GPU, it works well on CPU. @anijain2305 mentioned this may be relevant to #1076.

**Comment by anijain2305** [comment]
Could be related to this - https://github.com/pytorch/torchdynamo/issues/1076#issuecomment-1249921605

Looking more into it. My naive fix breaks other things.

**Comment by yanboliang** [comment]
@SeaOfOcean This has been fixed by https://github.com/pytorch/pytorch/pull/87060

**Comment by davidberard98** [comment]
I confirmed that 87060 fixed this.
