### ISSUE TITLE
Run torchdynamo+nvfuser on PyTorch's test suite

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#119]
@ezyang suggested running TorchDynamo+nvFuser on the PyTorch test suite to get a better sense of corner cases we might be missing.

This should be doable using the [unittest setUp/tearDown](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUp) hooks.

**Comment by ezyang** [comment]
Before you even get here, should first just run TorchDynamo+Eager.

TorchDynamo will print a bunch of scary "failure" messages but as long as fallback to eager works OK this is not a problem (just check if the test suite passes). These failures should get deduplicated and triaged and used to inform bugfixing work that may need to be done. (We will need to turn off this errors printing by default when we actually do a release).

Although you can use setUp/tearDown, overriding run is easier:

```
diff --git a/torch/testing/_internal/common_utils.py b/torch/testing/_internal/common_utils.py
index 0b072919c4..549c1e9942 100644
--- a/torch/testing/_internal/common_utils.py
+++ b/torch/testing/_internal/common_utils.py
@@ -1794,7 +1794,11 @@ class TestCase(expecttest.TestCase):
             failures_before = 0 if result is None else len(result.failures)  # num tests marked as failed before starting
             errors_before = 0 if result is None else len(result.errors)  # num tests marked as errored before starting
 
-        super().run(result=result)
+        import torchdynamo
+        torchdynamo.config.trace = True
+        with torchdynamo.optimize("eager"):
+            super().run(result=result)
+
         # Early terminate test if necessary.
         if self._should_stop_test_suite():
             if result.wasSuccessful():
```

you may also consider just turning torchdynamo at the top level entry point `run_tests`, since this is supposed to work.

You might want to do https://github.com/facebookresearch/torchdynamo/issues/69 first so you don't rabbithole into useless code (and make your execution time take a long time)

**Comment by jansel** [comment]
The warnings @ezyang shared via chat are:

1)
```
"/data/users/ezyang/torchdynamo/torchdynamo/variables/torch.py", line 151, in call_function
    return TensorVariable.create(                                                                            
  File "/data/users/ezyang/torchdynamo/torchdynamo/variables/tensor.py", line 120, in create
    assert (                                                                                                 
AssertionError: torch.* op returned non-Tensor Generator call_function <class 'torch._C.Generator'>
```
Fix:
should add the op returning a RNG generator to `_disallowed_function_ids()`:
https://github.com/jansel/torchdynamo/blob/033d2b0183b2c09bf0860095d5e932bcf972d029/torchdynamo/allowed_functions.py#L18

2) 
```
"/data/users/ezyang/torchdynamo/torchdynamo/variables/misc.py", line 262, in call_function            
    return self.obj.call_method(tx, self.name, args, kwargs).add_options(self)                               
  File "/data/users/ezyang/torchdynamo/torchdynamo/variables/tensor.py", line 228, in call_method            
    constant_result = ConstantVariable(product(self.size), **options)            
TypeError: reduce() of empty sequence with no initial value  
```

Fix:
Our product() should default to 1 on an empty list of sizes.  Test case would be something like `tensor(1).numel()`

3) 
```
"/data/users/ezyang/torchdynamo/torchdynamo/variables/builtin.py", line 347, in call_isinstance
    arg_type = arg.python_type()
  File "/data/users/ezyang/torchdynamo/torchdynamo/variables/base.py", line 133, in python_type
    raise NotImplementedError(f"{self} has no type")
NotImplementedError: NumpyVariable() has no type
```

Fix:
We can add `python_type()` method to NumpyVariable() (since we will guard on the type of numpy tensors anyway, so it just a constant).


All those should be quick 1-line-ish fixes.  Though, definitely demonstrates we can get some good data from this test suite!

**Comment by ezyang** [comment]
There are TONS of warnings, there isn't any particular reason to prioritize these, I think some triage will be necessary first

**Comment by jansel** [comment]
Note, status updates this effort are over in #69 

https://github.com/pytorch/torchdynamo/issues/69#issuecomment-1126591497

**Comment by anijain2305** [comment]
Closing this as this is not so relevant right now.
