### ISSUE TITLE
[fx2trt] TRT issue

### ISSUE THREAD

**Issue by frank-wei** [pytorch/torchdynamo#121]
~hf_Reformer: CUDA error: device-side assert triggered~
fastNLP_Bert: [TRT] [E] 3: [layers.h::setAxis::624] Error Code 3: API Usage Error

**Comment by frank-wei** [comment]
Update: 
hf_Reformer:
1. expand op error
2. nn.functional.linear triggers cublas error
3. torch.cat  CUDA error: device-side assert triggered
4. Some unsupported ops with int64. The workaround is cast to int32
torch.logsumexp: ((torch.float16,), {})
torch.functional.einsum: ((None, torch.float16, torch.float16), {})
torch.argmax: ((torch.float16,), {})
acc_ops.add: ((), {'input': torch.int64, 'other': torch.int64})
acc_ops.flatten: ((), {'input': torch.int64})
acc_ops.mul: ((), {'other': torch.int64})
torch.argsort: ((torch.int64,), {})
new: ((torch.int64,), {})
_operator.mod: ((torch.int64,), {})
acc_ops.unsqueeze: ((), {'input': torch.int64})
acc_ops.expand: ((), {'input': torch.int64})
acc_ops.gather: ((), {'input': torch.float16, 'index': torch.int64})
_operator.pow: ((torch.float16,), {})
acc_ops.reshape: ((), {'input': torch.int64})
acc_ops.getitem: ((), {'input': torch.int64})
acc_ops.cat: ((), {})
acc_ops.ne: ((), {'input': torch.int64, 'other': torch.int64})

**Comment by anijain2305** [comment]
Closing the issue as this seems stale. Feel free to reopen.
