### ISSUE TITLE
[fx2trt] unclear issues

### ISSUE THREAD

**Issue by frank-wei** [pytorch/torchdynamo#122]
vision_maskrcnn: Error
detectron2_maskrcnn: various tracing issues
Super_SloMo: various tracing issues
opacus_cifar10: tracing issues
hf_BigBird: op support, tracing issues,  shape '[1, 12, 62, 192]' is invalid for input of size 11904
pyhpc_equation_of_state: nan output

**Comment by anijain2305** [comment]
Closing the issue as this seems stale. Feel free to reopen.
