### ISSUE TITLE
Mutation bug

### ISSUE THREAD

**Issue by aazzolini** [pytorch/torchdynamo#1374]
Modifying an output after use creates a cyclical reference. E.g in the code below:
```

def forward(self, arg0_1, arg1_1, arg2_1):
    relu = torch.ops.aten.relu.default(arg2_1);  arg2_1 = None
    permute = torch.ops.aten.permute.default(arg0_1, [1, 0])
    addmm = torch.ops.aten.addmm.default(arg1_1, relu, permute);  permute = None
   ....
    copy__1 = torch.ops.aten.copy_.default(arg1_1, add_1);  arg1_1 = add_1 = None
    return ()

```
This triggers a bug in the scheduler while computing dependencies.

Chatted with @jansel about this and he suggested I remove this code block: 
https://github.com/pytorch/torchdynamo/blob/64980a6c55e39f4a727f5b16b781478167300c59/torchinductor/lowering.py#L2853

Removing the code above fixed the issue.

**Comment by ngimel** [comment]
Should functionalization get rid of those? We turn on functionalization only when backward is required though, cc @Chillee

**Comment by Chillee** [comment]
Yeah, we currently only use functionalization for autograd (so we can partition haha).

Should we turn on functionalization for forwards only as well?

**Comment by jansel** [comment]
Yeah, I think we should.  I'd expect it to be faster in most (but not all) cases.

**Comment by ngimel** [comment]
This goes back to our discussion of "should different parts of the stack be able to handle whatever is thrown at them, or are there conditions that inductor/aot/ expect to be satisfied"
