### ISSUE TITLE
Inductor cuda codegen generating wrong argument name 

### ISSUE THREAD

**Issue by SherlockNoMad** [pytorch/torchdynamo#1404]
Hi folks, I found that the inductor codegen for the ’tmp’ variable name is stateful accross unit tests

For example, when I run all the cuda opinfo tests all together, neg_cuda_float32 is generating a tmp42, which is not defined in the context. 
```
FAILED OP neg on cuda with torch.float32, at 7:59:
def kernel(in_ptr0, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK])
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + x0, xmask)
    tl.store(out_ptr0 + x0 + tl.zeros([XBLOCK], tl.int32), tmp42, xmask)
                                                           ^
```

However, when I try to run this single test in isolation, I am getting a correct kernel, 
```
@pointwise_heuristics(size_hints=[512], filename=__file__)
@triton.jit
def kernel(in_ptr0, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK])
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + x0, xmask)
    tmp1 = -tmp0
    [tl.store](http://tl.store/)(out_ptr0 + x0 + tl.zeros([XBLOCK], tl.int32), tmp1, xmask)
).kernel
```
Notice that the wrong kernel missing the compute line ‘tmp1 = -tmp0’ 

I am wondering if there anything stateful thing about the variable name codegen in Inductor?

**Comment by desertfire** [comment]
https://github.com/pytorch/torchdynamo/blob/3eb350f6870f01e42918df245318a78c8b5d016b/torchinductor/codegen/common.py#L435 is how a new tmp variable is named. I don't think `CSE` should be carried between tests. Can you give `torchdynamo.config.raise_on_assertion_error=True` a try to see if the problem still exists?

**Comment by voznesenskym** [comment]
CSE being carried between tests is just a vague simulation of CSE being carried across multiple inductor calls in the process. If it produced tmp42, it should correctly be assigning the other tmpX variable names. The concerning delta to me is the missing compute line `tmp1 = -tmp0` - that should says `tmp42 = -tmp0`.

**Comment by ngimel** [comment]
It looks like the kernel-level CSE and it definitely should not be carried between kernels, it's interesting we haven't hit these bugs earlier.

**Comment by desertfire** [comment]
This looks like some memory management issue because of previous failed cases. In our model bench script, we use subprocess so the problem is not exposed there. In our hand-written unit tests, all the tests pass so there is also no problem. I am trying to find where to add proper recovery code so that the cse cache is not messed up.

**Comment by voznesenskym** [comment]
> This looks like some memory management issue because of previous failed cases. In our model bench script, we use subprocess so the problem is not exposed there. In our hand-written unit tests, all the tests pass so there is also no problem. I am trying to find where to add proper recovery code so that the cse cache is not messed up.

Just guessing here from first principles... I would also consider wrapping the current itertools call we use to get the number in a util to help track where the increments grow - it might be a kernel object getting reused or something...
