### ISSUE TITLE
Make `TorchDynamoNNModuleWrapper` a subclass of `torch.nn.Module`

### ISSUE THREAD

**Issue by xwang233** [pytorch/torchdynamo#1458]
`TorchDynamoNNModuleWrapper` is defined at https://github.com/pytorch/torchdynamo/blob/a043fcc8dfa47b8d18b615b5d79860c2af170af5/torchdynamo/eval_frame.py#L131

cc @ngimel @ptrblck @csarofeen

**Comment by voznesenskym** [comment]
Thanks for filing an issue, can you add some more details as to why we want this?

**Comment by xwang233** [comment]
User code like this in TIMM checks if an instance is `torch.nn.Module`, https://github.com/rwightman/pytorch-image-models/blob/d4ea5c7d7d55967a8bedbfbb58962131d8aba776/timm/optim/optim_factory.py#L215.

A `torchdynamo.optimize()` wrapped module is not an instance of torch.nn.Module and may cause issue in many user code.

**Comment by voznesenskym** [comment]
Is it causing issues somewhere?

**Comment by xwang233** [comment]
https://github.com/pytorch/pytorch/issues/86020#issuecomment-1264123277 recommends to use torchdynamo instead of functorch in the future. It _will_ cause issue.

**Comment by voznesenskym** [comment]
When it does, let's reopen this. I hesitate to solve a problem we do not yet have.

**Comment by ngimel** [comment]
Perhaps the reason it's not causing issues yet is because we don't capture optimizers yet? cc @mlazos

**Comment by voznesenskym** [comment]
> Perhaps the reason it's not causing issues yet is because we don't capture optimizers yet? cc @mlazos

There's probably a few reasons, but I'd like to have a clear error case where we have a repro to know when the problem is solved.

**Comment by xwang233** [comment]
The current TIMM implementation uses functorch's memory_efficient_fusion. However, https://github.com/pytorch/pytorch/issues/86020#issuecomment-1264123277 recommends to use torchdynamo's optimize in the future and I'm working on this. TIMM script will be blocked by this issue on this line https://github.com/rwightman/pytorch-image-models/blob/d4ea5c7d7d55967a8bedbfbb58962131d8aba776/timm/optim/optim_factory.py#L215.

**Comment by voznesenskym** [comment]
> The current TIMM implementation uses functorch's memory_efficient_fusion. However, https://github.com/pytorch/pytorch/issues/86020#issuecomment-1264123277 recommends to use torchdynamo's optimize in the future and I'm working on this. TIMM script will be blocked by this issue on this line https://github.com/rwightman/pytorch-image-models/blob/d4ea5c7d7d55967a8bedbfbb58962131d8aba776/timm/optim/optim_factory.py#L215.

Understood! Thank you. Let me know when you have a repro, happy to take a look.

**Comment by Chillee** [comment]
This was also causing issues in some user code as well.

User code had something like

```
mod = Foo()
mod = torchdynamo.optimize("inductor")(mod)
assert isinstance(mod, Foo)
```

I chatted a bit with @anijain2305 about this.

**Comment by voznesenskym** [comment]
> This was also causing issues in some user code as well.
> 
> User code had something like
> 
> ```
> mod = Foo()
> mod = torchdynamo.optimize("inductor")(mod)
> assert isinstance(mod, Foo)
> ```
> 
> I chatted a bit with @anijain2305 about this.

I see. I don't have strong opinions on us not doing this, fwiw. I do not think it's a bad change, per se - just that changes for "future" fixes that change the return type of a public contract should not be made lightly.

**Comment by xwang233** [comment]
> Understood! Thank you. Let me know when you have a repro, happy to take a look.

Hi @voznesenskym , you can try my changes here https://github.com/xwang233/pytorch-image-models/tree/aot-autograd-update

If you do a benchmark with
```
python benchmark.py --model resnet50 -b 1 --bench train --aot-autograd
```

You may see an error
```python
INFO:validate:Benchmarking in float32 precision. NCHW layout. torchscript disabled
Benchmarking in float32 precision. NCHW layout. torchscript disabled
INFO:validate:Model resnet50 created, param count: 25557032
Model resnet50 created, param count: 25557032
Traceback (most recent call last):
  File "benchmark.py", line 662, in <module>
    main()
  File "benchmark.py", line 646, in main
    results = benchmark(args)
  File "benchmark.py", line 578, in benchmark
    run_results = _try_run(
  File "benchmark.py", line 524, in _try_run
    bench = bench_fn(model_name=model_name, batch_size=batch_size, **bench_kwargs)
  File "benchmark.py", line 360, in __init__
    self.optimizer = create_optimizer_v2(
  File "/workspace/timm-models/pytorch-image-models/timm/optim/optim_factory.py", line 253, in create_optimizer_v2
    optimizer = optim.SGD(parameters, momentum=momentum, nesterov=True, **opt_args)
  File "/opt/pytorch/pytorch/torch/optim/sgd.py", line 109, in __init__
    super(SGD, self).__init__(params, defaults)
  File "/opt/pytorch/pytorch/torch/optim/optimizer.py", line 59, in __init__
    param_groups = list(params)
TypeError: 'TorchDynamoNNModuleWrapper' object is not iterable
```

which points to `TorchDynamoNNModuleWrapper` here https://github.com/rwightman/pytorch-image-models/blob/d4ea5c7d7d55967a8bedbfbb58962131d8aba776/timm/optim/optim_factory.py#L215

**Comment by xwang233** [comment]
This is no longer an issue.
