### ISSUE TITLE
Add divisibility by 16 annotations to `numel` arguments in Inductor.

### ISSUE THREAD

**Issue by Chillee** [pytorch/torchdynamo#1527]
Today, we don't add `divisible_by_16` annotations to the `numel` arguments.

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/6355099/194457035-48461d60-7a83-413e-956c-d67fb3981f48.png">

The issue is that we add the `numel` args after we set annotations (https://github.com/pytorch/torchdynamo/blob/main/torchinductor/codegen/triton.py#L58).

**Comment by ngimel** [comment]
We also need to create proper guards if we set those annotations
