### ISSUE TITLE
aot_cudagraphs backend is broken

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/torchdynamo#1557]
This PR https://github.com/pytorch/torchdynamo/pull/1395 changed `.add_submodule` to `.register_attr_or_module` in `apply_cuda_graphs` function.

This change results in an error:
```py
AttributeError: 'GraphModule' object has no attribute 'register_attr_or_module'
```

On latest commit (baa40211981c9927776bde92581339ee6d8abe14) try `python benchmarks/torchbench.py --training -d cuda --fast --backend=aot_cudagraphs --skip-accuracy-check  --performance --generate-aot-autograd-stats --only mnasnet1_0`.

**Comment by voznesenskym** [comment]
Thanks for filing the issue. I can take a look. Sounds just like a rename oversight.
