### ISSUE TITLE
Run TorchDynamo on nn.Modules crawled from github

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#156]
Back in 2020 I did this project: 
https://github.com/jansel/pytorch-jit-paritybench

Which contains 8k `nn.Modules` crawled from 1k github projects.

At the time I used it to find that TorchScript worked on ~30% of projects crawled from github.  

We should run TorchDynamo on those testcases to 
1) get more datapoints on model coverage levels
2) find and fix more bugs in TorchDynamo

**Comment by yanboliang** [comment]
Woohoo, it seems we have a good coverage:
```
TorchDynamo ParityBench:
          total  passing  score
projects   1111     1035  93.2%
tests      7549     7399  98.0%
```
I'll dig into the errors and check the missing features.

**Comment by anijain2305** [comment]
Pretty awesome numbers for the first run :)

**Comment by jansel** [comment]
Wow, awesome!  For context of those reading, TorchScript was ~30% projects and ~60% tests. So more than 3x the number of projects passing.

I assume that is allowing Python fallbacks (`nopython=False`, the default)?  

Seems like 100% might be in reach!

**Comment by yanboliang** [comment]
> I assume that is allowing Python fallbacks (`nopython=False`, the default)?

That's right!

**Comment by Chillee** [comment]
I'm curious about other stats, like "how big are the graphs", "how many graphs does it get split into", etc.

**Comment by soumith** [comment]
this is pretty cool, and yea 100% with nopython=False seems like a no-brainer to aim for.

**Comment by xuzhao9** [comment]
interesting! Curious what are the errors and we should include some delegates in torchbench to further improve coverage

**Comment by yanboliang** [comment]
We hit our 100% goal! To whom might be interested in details of the errors, graph and graph break characteristics, model complexity, etc, please check our post [TorchDynamo Update 8: TorchDynamo passed correctness check on 7k+ github models](https://dev-discuss.pytorch.org/t/torchdynamo-update-8-torchdynamo-passed-correctness-check-on-7k-github-models/663).

**Comment by voznesenskym** [comment]
> We hit our 100% goal! To whom might be interested in details of the errors, graph and graph break characteristics, model complexity, etc, please check our post [TorchDynamo Update 8: TorchDynamo passed correctness check on 7k+ github models](https://fb.workplace.com/notes/755492628976297).

Fantastic! There's also a lot of good low hanging fruit in nopython=True, fwiw, do we have plans to run that and group the most common errors?

**Comment by yanboliang** [comment]
> Fantastic! There's also a lot of good low hanging fruit in nopython=True, fwiw, do we have plans to run that and group the most common errors?

Yes, that's exactly what I mentioned at "Future Work" section!

**Comment by anijain2305** [comment]
@yanboliang Can we close this thread?
