### ISSUE TITLE
pytorch core test failure: LLVM ERROR: Broken function found, compilation aborted!

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#1638]
Repro:
```
PYTORCH_TEST_WITH_INDUCTOR=1  python test/test_torch.py   -k  test_nondeterministic_alert_grid_sample_2d_cuda
```
Error:
```
due to: 
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/variables/tensor.py", line 283, in create
    assert (
AssertionError: torch.* op returned non-Tensor bool call_function <built-in function _cuda_isInBadFork>

from user code:
   File "/fsx/users/binbao/pytorch/torch/random.py", line 39, in manual_seed
    if not torch.cuda._is_in_bad_fork():

Set torchdynamo.config.verbose=True for more information
==========
Operand is null
  %7 = call float @__nv_floorf(<null operand!>)
in function kernel_0d1
LLVM ERROR: Broken function found, compilation aborted!
Aborted (core dumped)
```

**Comment by jansel** [comment]
Should handle this similar to `torch.is_grad_enabled`:
https://github.com/pytorch/torchdynamo/blob/dc16a9e8e575e4f9e6eec37cc200ff9e42e03815/torchdynamo/variables/torch.py#L246-L250

By turning it into a guard + `ConstantVariable`.

**Comment by jansel** [comment]
Though perhaps we shouldn't be inlining in `manual_seed()` and just capture it in the graph.

**Comment by voznesenskym** [comment]
> Though perhaps we shouldn't be inlining in `manual_seed()` and just capture it in the graph.

IIRC I was going to add support for this for some opinfo tests, but then hacked around not needing to. manual_seed() returning a `torch._C.Generator` object was kind of annoying to deal with. 

Quick scan of the failing test, where are we calling `manual_seed`?

**Comment by voznesenskym** [comment]
_is_in_bad_fork is a red herring here, fixing that graph break still leaders to this broken function.

**Comment by desertfire** [comment]
Close in favor of https://github.com/pytorch/torchdynamo/issues/1772
