### ISSUE TITLE
printing an optimized model is not pretty

### ISSUE THREAD

**Issue by soumith** [pytorch/torchdynamo#1691]
Eager mode print looks like this:

```python
>>> print(model)

Net(
  (fc1): Linear(in_features=10, out_features=20, bias=True)
  (fc2): Linear(in_features=20, out_features=30, bias=True)
)
```

Optimized looks like this
```python
>>> print(dynamo.optimize()(model))
<torch._dynamo.eval_frame._TorchDynamoContext.__call__.<locals>.TorchDynamoNNModuleWrapper object at 0x7f155ba76580
```

**Comment by Chillee** [comment]
@anijain2305 The root of this problem is that we're not returning an `nn.Module`

**Comment by anijain2305** [comment]
Agreed. I think we need a larger discussion on what the return type should be. Not comprehensive, but some options that I have heard from talking to multiple ppl are

1) Return the existing wrapper. And override the `__repr__` function to pretty print (just fixes print problem).
2) Make the existing wrapper a subclass of torch.nn.Module.
3) Shallow copy original module, overwrite forward with `dynamo.optimize` and return `torch.nn.Module` object.
4) Something totally different, e.g., first-class integration with `nn.Module`. Add option optimize similar to train/eval. However, this means bigger API change.

**Comment by Chillee** [comment]
I vote for 3.

**Comment by msaroufim** [comment]
Waiting for source build on pytorch/pytorch but just to double check, option 3 essentially boils down to in https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/eval_frame.py#L82 change the below

```python

    def __call__(self, fn):
        fn = innermost_fn(fn)
        # Optimize the forward method of torch.nn.Module object
        if isinstance(fn, torch.nn.Module):
            mod = fn
            optimized_forward = self(mod.forward)
            new_mod = copy.copy(fn)
            new_mod.forward = optimized_forward
            
            # Save the function pointer to find the original callable while nesting
            # of decorators.
            new_mod._torchdynamo_orig_callable = mod
            return new_mod
```

With the tradeoff being that if people are running benchmarks they now need to make sure they run the preoptimized model before optimizing it

**Comment by anijain2305** [comment]
This is working on master
