### ISSUE TITLE
minifier is writing repro.py to pytorch install's root directory

### ISSUE THREAD

**Issue by soumith** [pytorch/torchdynamo#1705]
This seems totally incorrect, repro.py should be written to the current working directory or to `/tmp`.

```
Writing checkpoint with 4 nodes to /tmp/minifier_soumith/checkpoints/4.py
Copying repro file for convenience to /home/soumith/code/pytorch/repro.py
Wrote minimal repro out to repro.py
```

`/home/soumith/code/pytorch/repro.py` is my PyTorch from-source install that I installed in `python setup.py develop` mode.

My current working directory is `/home/soumith/code/examples/imagenet`

**Comment by anijain2305** [comment]
@williamwen42 @mlazos Do you want to take this task?

**Comment by mlazos** [comment]
Yeah I can take this, I've been meaning to remove the random directory in the config that points to the project root for some reason.
