### ISSUE TITLE
examples/word_language_model is failing

### ISSUE THREAD

**Issue by soumith** [pytorch/torchdynamo#1712]
Here's the diff:

```python
git diff main.py
diff --git a/word_language_model/main.py b/word_language_model/main.py
index 3e13e2b..9114324 100644
--- a/word_language_model/main.py
+++ b/word_language_model/main.py
@@ -6,6 +6,7 @@ import os
 import torch
 import torch.nn as nn
 import torch.onnx
+import torch._dynamo as dynamo

 import data
 import model
@@ -112,6 +113,7 @@ if args.model == 'Transformer':
 else:
     model = model.RNNModel(args.model, ntokens, args.emsize, args.nhid, args.nlayers, args.dropout, args.tied).to(device)

+model = dynamo.optimize()(model)
 criterion = nn.NLLLoss()

 ###############################################################################
```

Here's the error:

```python
~/code/examples/word_language_model$ python main.py --cuda --model Transformer
make_fallback(aten.unfold): a decomposition exists, we should switch to it
make_fallback(aten.unfold_backward): a decomposition exists, we should switch to it
[2022-10-19 01:43:58,680] torch._inductor.lowering: [WARNING] using triton random, expect difference from eager
[2022-10-19 01:44:02,860] torch._inductor.lowering: [WARNING] using triton random, expect difference from eager
Traceback (most recent call last):
  File "/home/soumith/code/examples/word_language_model/main.py", line 227, in <module>
    train()
  File "/home/soumith/code/examples/word_language_model/main.py", line 189, in train
    loss.backward()
  File "/home/soumith/code/pytorch/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/soumith/code/pytorch/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/soumith/code/pytorch/torch/autograd/function.py", line 270, in apply
    return user_fn(self, *args)
  File "/home/soumith/code/pytorch/functorch/_src/aot_autograd.py", line 460, in backward
    all_args = list(ctx.symints) + list(ctx.saved_tensors) + list(contiguous_args)
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```

Tried using the minifier, but there's no sign of life from the minifier despite trying to enable the env flag `TORCHDYNAMO_REPRO_AFTER="aot" `  or `TORCHDYNAMO_REPRO_AFTER="dynamo" `. It does not spit out any output about `minifier_launcher` or anything at all.

**Comment by soumith** [comment]
- Working: `dynamo.optimize('eager')(model)`
- NOT Working: `dynamo.optimize('aot_eager')(model)`
- NOT Working: `dynamo.optimize('inductor')(model)`

**Comment by soumith** [comment]
I'm pretty sure (from gdb/pdb attempts) this is tripping on something in `aot_autograd.py` calling `backward` of the CompiledFunction twice in quick succession.
Because it crosses the C++-Python boundary, haven't been able to nail a full trace of what's going on.

cc: @Chillee

**Comment by soumith** [comment]
@anijain2305 if this doesn't fail in the dashboard, with the 2-iter change we put in, that's suspicious and we need to investigate. (actually, I'm not sure if we're running `examples` in dashboard as part of TorchBench or not)

**Comment by penguinwu** [comment]
@desertfire Should we add examples/ to our CI to make sure they are always working?

**Comment by soumith** [comment]
minimized example incoming.

**Comment by anijain2305** [comment]
> @anijain2305 if this doesn't fail in the dashboard, with the 2-iter change we put in, that's suspicious and we need to investigate. (actually, I'm not sure if we're running `examples` in dashboard as part of TorchBench or not)

We do not run `examples` as part of dashboard. But, let me remove a couple of fixes locally and see if the 2-iter change triggers the error.

**Comment by soumith** [comment]
```python
import torch
import torch.nn as nn
import torch._dynamo as dynamo

device = torch.device("cpu") # FAILS for both cpu and cuda

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.weight = nn.Parameter(torch.randn(3))
        self.src_mask = None

    # @torch.no_grad() # uncommenting this line fixes the error
    def _generate_mask(self, sz):
        mask = torch.ones(sz, sz)
        mask = mask.float().masked_fill(mask == 0, float('-inf'))
        return mask

    def forward(self, src):
        device = src.device
        if self.src_mask is None:
            mask = self._generate_mask(len(src)).to(device)
            self.src_mask = mask
        return self.weight * self.src_mask

model = Model().to(device)
model = dynamo.optimize('aot_eager')(model)
data = torch.tensor([[    0,   3],
                     [    1,   2],
                     [    2, 1]], device=device)
model.zero_grad()

with torch.autograd.set_multithreading_enabled(False):
    with torch.autograd.detect_anomaly(check_nan=False):
        for i in range(2):
            print("start_iter")
            output = model(data)
            output.sum().backward()
            print("end_iter")
```

**Comment by soumith** [comment]
Maybe AOT is being naughty and setting requires_grad=True on things that it shouldn't

**Comment by soumith** [comment]
This is another variant that produces a different error:

```python
import torch
import torch.nn as nn
import torch._dynamo as dynamo

device = torch.device("cpu") # FAILS for both cpu and cuda

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.weight = nn.Parameter(torch.randn(3))
        self.src_mask = None

    def forward(self):
        if self.src_mask is None:
            with torch.no_grad():
                self.src_mask = torch.ones(3)
        return self.weight * self.src_mask

model = Model().to(device)
model = dynamo.optimize('aot_eager')(model)
model.zero_grad()

for i in range(2):
    print("start_iter")
    output = model()
    output.sum().backward()
    print("end_iter")
```

```
python main.py
start_iter
(Parameter containing:
tensor([-0.3672,  1.3672, -0.1196], requires_grad=True),)
Traceback (most recent call last):
  File "/home/soumith/code/examples/word_language_model/main.py", line 27, in <module>
    output.sum().backward()
  File "/home/soumith/code/pytorch/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/soumith/code/pytorch/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

**Comment by Chillee** [comment]
@soumith AOT is definitely setting requires_grad on outputs that don’t require grad.

see discussion here: https://github.com/pytorch/pytorch/pull/86838

**Comment by ezyang** [comment]
I checked and Brian's patch fixes variant 1 but not variant 2

**Comment by soumith** [comment]
cc: @bdhirsh

**Comment by ezyang** [comment]
My guess is that in the second example, we're "losing" the no grad between the first and second trace, but the first trace didn't insert enough detaches to simulate the effect of no grad.

**Comment by bdhirsh** [comment]
Repro'd locally - It looks like somewhere in the first trace, our fake tensor's `requires_grad` info is incorrect: the node that came from `aten.mul(primals_1, ones.detach())` is (incorrectly) showing up as having `requires_grad=False`. Digging a bit more.

**Comment by bdhirsh** [comment]
Hmm looks like when dynamo traces the module, there's a `torch.set_enable_grad(False)` at the top level, in the beginning of the trace. That seems wrong:
```
def forward(self, self_weight : torch.nn.parameter.Parameter):
    set_grad_enabled = torch.set_grad_enabled(False)
    ones = torch.ones(3)
    set_grad_enabled_1 = torch.set_grad_enabled(False)
    mul = self_weight * ones;  self_weight = None
    return (mul, ones)

```

**Comment by bdhirsh** [comment]
Confirmed - looks like when I comment out that logic in dynamo ([here](https://github.com/pytorch/pytorch/blob/f3cc588d09f62471a46d555368f1627932e1812f/torch/_dynamo/variables/misc.py#L278)), the repro passes.

Two options I can think of are:

(1) (harder) dynamo should be able to tell where the no_grad() context manager ends, and insert a `set_grad_enabled(True)` later on in the graph

(2) (easier) Does dynamo... actually need to emit `set_requires_grad()` into the graph? It would be nice if no global state was necessary, and the right `.detach()` calls just showed up in the graph while dynamo traces. I'm not sure if that's realistic though.

**Comment by ezyang** [comment]
@yanboliang

**Comment by yanboliang** [comment]
This should be the same reason as https://github.com/pytorch/torchdynamo/issues/1446, and I think the culprit is where we did [special handling before graph break](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/symbolic_convert.py#L203-L217). I'm thinking how to handle this in a more systematic and elegant way, as we fixed several issues around grad mode recently.
