### ISSUE TITLE
[Bug]: "torchdynamo.logging.CODE print compiled functions + graphs" doesn't work

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#1718]
### 🐛 Describe the bug

```
# torchdynamo.logging.CODE print compiled functions + graphs
# logging.INFO print the steps that dynamo is running
# logging.WARN print warnings (including graph breaks)
# logging.ERROR print exceptions (and what user code was being processed when it occurred)
# NOTE: changing log_level will automatically update the levels of all torchdynamo loggers
log_level = tdl.CODE
```

in torch/_dynamo/config.py

torchdynamo doesn't exist anymore

even if you change to torch._dynamo it doesn't work due to recursive module import problem

### Error logs

n

### Did Dynamo succeed?

- [ ] Does dynamo.optimize("eager") succeed?

### Did AOT succeed?

- [ ] Did dynamo.optimize("aot_eager") succeed?

### Did Inductor succeed?

- [ ] Does dynamo.optimize("inductor") succeed?

### Minified repro

n

**Comment by mlazos** [comment]
cc @williamwen42, can you take look? Let me know if you need me to instead.
