### ISSUE TITLE
tacotron2 fails without suppress_errors with: RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#1748]
### 🐛 Describe the bug

Patch in https://github.com/pytorch/pytorch/pull/87440 and then run tacotron2

```
python benchmarks/dynamo/torchbench.py  --accuracy --backend eager --training --only tacotron2
```

This looks similar to https://github.com/pytorch/torchdynamo/issues/1301 but it's actually not the same thing, as this failure triggers with eager (no AOTAutograd)

### Error logs

https://gist.github.com/ezyang/7be54e5c0097d03e06a471fb5a6c2cac

### Minified repro

minifier never triggered

**Comment by anijain2305** [comment]
Still debugging. Setting `fake_tensor_propagation = False` in dynamo passes it. Minifiers  are unlikely to help here, because the cause and effect are probably in different python frames.

**Comment by ezyang** [comment]
Feels like a minifier on record replay might work

**Comment by bdhirsh** [comment]
FWIW, I see this error with `hf_Longformer` too. I've been looking into this a bit, I'll update if I make some more progress.

It looks like when dynamo takes outputs from a previous graph and uses them to create example inputs to trace the next graph, we lose the `is_leaf()` property on the inputs (probably because we're creating fresh "example" inputs that don't have autograd history. I think we need to do something similar to what fake tensor does to fake up autograd history.

**Comment by anijain2305** [comment]
record-replay is able to repro this on a python frame. But I suspect the inputs to the frame are already broken. There is not much in replay, 2 inputs and inplace add. Its the problem with 2 inputs.

Their requires_grad field is set to True, but they were intermediate tensors in the original model. For this subgraph, they become leaf tensors.

**Comment by ezyang** [comment]
Then the other thing that would help is something like AOT_FAKE_CROSSREF (cc @eellison), but on a frame by frame level, where we check metadata on frame exit matches what eager would have given you.

**Comment by anijain2305** [comment]
Thanks @bdhirsh your explanation made me check the real tensors on the boundary of subgraphs. I think this should fix https://github.com/pytorch/pytorch/pull/87513

**Comment by anijain2305** [comment]
https://github.com/pytorch/pytorch/pull/88045 solves this problem
