### ISSUE TITLE
mobilenet_v2_quantized_qat fails with accuracy error on aot_eager

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#1773]
### 🐛 Describe the bug

```
Running mobilenet_v2_quantized_qat...
WARNING:common:fp64 golden ref were not generated for mobilenet_v2_quantized_qat
[2022-10-26 15:13:25,770] torch._dynamo.utils: [ERROR] Accuracy failed for key name classifier.1.bias.grad
```

**Comment by bdhirsh** [comment]
I ran this locally on my (slightly out of date) master. First, I got an error about our `aten._fused_moving_avg_obs_fq_helper.default` meta function, which has a fix on the symbolic shapes branch but isn't in master yet.

I patched in that fix and re-ran, and the model passed.

That was on a version of master that was a day or two old though - I'm pulling latest and rebuilding, will confirm if it still fails.

**Comment by bdhirsh** [comment]
@ezyang I don't see an accuracy failure - when I patch in the fix to `_fused_moving_avg_obs_fq_helper`'s meta, I get a pass

**Comment by bdhirsh** [comment]
Could be a striding inconsistency issue that got fixed recently?

**Comment by ezyang** [comment]
Yes if it passes on master we close this
