### ISSUE TITLE
PyTorch Distributed: next level of tests

### ISSUE THREAD

**Issue by msaroufim** [pytorch/torchdynamo#1779]
The HuggingFace accelerate integrations provides a good list of the all potential libraries that need to be tested to claim that dynamo/inductor works just fine on single node and in the distributed setting https://github.com/huggingface/accelerate#supported-integrations.

So far @wconstab's efforts have been focused on getting DDP and FSDP to work but what we should also test are more end to end libraries that wrap DDP or FSDP.

Here's an example from PyTorch Lightning, does this already work? Probably? Might be worth testing though.

### Lightning
`trainer = Trainer(devices=4, accelerator="gpu",strategy="ddp")`

Specifically for Lightning I'm curious whether their callbacks have a strange interaction with an optimized `nn.Module`

### Accelerate
Another one is from the accelerate repo itself, where we have a popular pattern `def prepare(nn.Module) -> nn.Module`

`model, optimizer, data = accelerator.prepare(model, optimizer, data)`

And in this case a top level application of the dynamo decorator might optimize both the model that needs to be prepared and the final model. Should we make it clearer instead in documentation that these library maintainers need to leverage the dynamo decorator inside the prepare function. In which case what happens if a user wraps a a model with a dynamo decorator that itself is wrapped with another dynamo decorator.

### Ray
Ray Train has a similar wrapper that prepares models by wrapping with DDP

`model = ray.train.torch.prepare_model(nn.Linear(4, 1))`

### torchrun
Finally end to end workflows might include scripts that: setup a cluster, ssh into machines, setup some environment variables so as a good proxy having an example of `torchrun train_script.py` working would derisk things quite a bit in more real world scenarios.

### Next steps
Once the above workflow is nailed it then makes sense to take a look at supporting DeepSpeed, XLA and Megatron. Specifically for DeepSpeed for now should we just recommend users optimize the model pre wrapping strategy?

**Comment by wconstab** [comment]
### Lightning:

**First, basic compatibility with Lightning + Dynamo**
If wrapping a lightning module with torchdynamo optimize, you'll get an OptimizedModule.  Lightning doesn't like that:
```
model = LitMNIST()
model = torch._dynamo.optimize()(model)
```
```TypeError: `Trainer.fit()` requires a `LightningModule`, got: OptimizedModule```
Full repro: [litmnist_1.py](https://gist.github.com/wconstab/cd9bb67ee96dbc97040ea034db136f22#file-litmnist_1-py)

Applying dynamo as a decorator to the LightningModule's forward method seems to work (but isn't as idiomatic):
```
    @torch._dynamo.optimize()
    def forward(self, x):
        x = self.model(x)
        return F.log_softmax(x, dim=1)
```
Full repro: [litmnist_2.py](https://gist.github.com/wconstab/cd9bb67ee96dbc97040ea034db136f22#file-litmnist_2-py)

**Second, Trying it with DDP**
(WIP)

**Comment by wconstab** [comment]
### Accelerate
I tested this recently on a cv_example from accelerate repo, and it works with Dynamo+DDPOptimizer.  See details on [this github issue comment](https://github.com/pytorch/torchdynamo/issues/1835#issuecomment-1306523662)

**Comment by wconstab** [comment]
### Ray Train
Applying torchdynamo to the model after ray train.prepare seems to be the way to go, and it works without issue:
```
    # Create model.
    model = NeuralNetwork()
    model = train.torch.prepare_model(model)
    import torch._dynamo
    import logging
    torch._dynamo.config.optimize_ddp = True
    torch._dynamo.config.log_level = logging.INFO
    model = torch._dynamo.optimize()(model)
```
Example output:

```
(RayTrainWorker pid=98151) [2022-11-16 00:48:46,998] torch._dynamo.optimizations.distributed: [INFO] DDPOptimizer used buc[65/12025]214400 and produced the following buckets:                                           
(RayTrainWorker pid=98151) [2022-11-16 00:48:46,999] torch._dynamo.optimizations.distributed: [INFO]                                (RayTrainWorker pid=98151) DDPOptimizer bucket assignments                           
(RayTrainWorker pid=98151) ┌─────────┬────────────┬─────────────────────────────────┐
(RayTrainWorker pid=98151) │   Index │   Size (b) │ Param Names                     │                                               (RayTrainWorker pid=98151) ├─────────┼────────────┼─────────────────────────────────┤
(RayTrainWorker pid=98151) │       0 │    1071144 │ self_linear_relu_stack_4_weight │                                               (RayTrainWorker pid=98151) ├─────────┼────────────┼─────────────────────────────────┤
(RayTrainWorker pid=98151) │         │            │ self_linear_relu_stack_4_bias   │
(RayTrainWorker pid=98151) ├─────────┼────────────┼─────────────────────────────────┤                                               
(RayTrainWorker pid=98151) │         │            │ self_linear_relu_stack_2_weight │
(RayTrainWorker pid=98151) ├─────────┼────────────┼─────────────────────────────────┤                                               
(RayTrainWorker pid=98151) │         │            │ self_linear_relu_stack_2_bias   │
(RayTrainWorker pid=98151) ├─────────┼────────────┼─────────────────────────────────┤                                               
(RayTrainWorker pid=98151) │       1 │    1607680 │ self_linear_relu_stack_0_weight │
(RayTrainWorker pid=98151) ├─────────┼────────────┼─────────────────────────────────┤                                               
(RayTrainWorker pid=98151) │         │            │ self_linear_relu_stack_0_bias   │
(RayTrainWorker pid=98151) └─────────┴────────────┴─────────────────────────────────┘  
```
Full repro [ray_torch_fashion_mnist_example.py](https://gist.github.com/wconstab/159ac7bdcf4c1732ccb548d73f99b8c2#file-ray_torch_fashion_mnist_example-py)
taken from [this ray example](https://docs.ray.io/en/latest/train/examples/torch_fashion_mnist_example.html)

**Comment by wconstab** [comment]
### Torchrun

Torchrun also works- I enabled it for the dynamo/distributed benchmark in https://github.com/pytorch/pytorch/pull/89149

`torchrun --nproc_per_gpu 2 benchmarks/dynamo/distributed.py --toy_model --dynamo inductor --verbose`

```
[default0]:[2022-11-16 18:30:16,537] torch._dynamo.optimizations.distributed: [INFO] DDPOptimizer used bucket cap 26214400 and produced the following buckets:
[default0]:[2022-11-16 18:30:16,539] torch._dynamo.optimizations.distributed: [INFO]
[default0]:DDPOptimizer bucket assignments
[default0]:┌─────────┬────────────┬──────────────────────────┐
[default0]:│   Index │   Size (b) │ Param Names              │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│       0 │    4024020 │ self_net_13_weight       │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_13_bias         │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_12_net_0_weight │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_12_net_0_bias   │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│       1 │   64028000 │ self_net_11_net_0_weight │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_11_net_0_bias   │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_10_net_0_weight │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_10_net_0_bias   │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_9_net_0_weight  │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_9_net_0_bias    │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_8_net_0_weight  │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_8_net_0_bias    │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_7_net_0_weight  │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_7_net_0_bias    │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_6_net_0_weight  │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_6_net_0_bias    │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_5_net_0_weight  │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_5_net_0_bias    │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│       2 │  400040000 │ self_net_4_net_0_weight  │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_4_net_0_bias    │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│       3 │  400040000 │ self_net_2_weight        │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_2_bias          │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│       4 │     440000 │ self_net_0_weight        │
[default0]:├─────────┼────────────┼──────────────────────────┤
[default0]:│         │            │ self_net_0_bias          │
[default0]:└─────────┴────────────┴──────────────────────────┘
```

**Comment by wconstab** [comment]
@msaroufim I think we should start a new issue for DeepSpeed and start working with the msft team (i sent an opener out on slack, will follow up).  XLA enablement also makes sense to track via separate issues (there are multiple XLA distriuted features to tackle).  I'm not sure what to do for Megatron - do you have a suggestion there?

**Comment by msaroufim** [comment]
SGTM, might be worth incorporating the above in a blog at some point - otherwise agreed will track in separate issues
