### ISSUE TITLE
Add a backend verification mode

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#179]
We should have a mode where we perform more thorough testing of backend correctness on a graph-by-graph level as a debugging tool.

Some [specific backends include correctness checking](https://github.com/jansel/torchdynamo/blob/8db8efc7681e4ae5851c3a298250993660d16e55/torchdynamo/optimizations/inference.py#L156), though currently it is up to the backends to check this themselves. 

I'd suggest adding a wrapper class that takes a backend and returns a new backend that checks correctness and raises exceptions on correctness failures.

This should be a mode that users can enable to help debug the issue where they get the wrong answer.

**Comment by anijain2305** [comment]
This one is already completed by @pyjhzwh
