### ISSUE TITLE
Fix thread safety of _eval_frame.c

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#180]
We have a thread safety issue if someone tries to use TorchDynamo from multiple threads in a single python process.

The issue is `tstate->interp->eval_frame` is global, so threads might clobber each other when the change the eval_frame function.

There is some [unfinished code to make the callback thread local](https://github.com/facebookresearch/torchdynamo/blob/8db8efc7681e4ae5851c3a298250993660d16e55/torchdynamo/_eval_frame.c#L65), but we need to extend that to simulate having a thread local `tstate->interp->eval_frame`.

- We should have a global counter (protected by the GIL?) of how many threads are inside `torchdynamo.optimize`.
- When that counter goes from 0 to 1, we should install our `_custom_eval_frame`
- When that counter goes from 1 to 0, we should uninstall our `_custom_eval_frame`, and restore the default Python behavior
- If the thread-local callback is None (the default), our `_custom_eval_frame` should just call `_PyEval_EvalFrameDefault`.
- We should remove `_custom_eval_frame_run_only` and emulate its behavior from within `_custom_eval_frame` when callback is `False`

**Comment by ezyang** [comment]
fixed by @voznesenskym
