### ISSUE TITLE
LLVM ERROR: inconsistency in registered CommandLine options

### ISSUE THREAD

**Issue by stephen-youn** [pytorch/torchdynamo#1818]
### 🐛 Describe the bug

when trying to run test_torchinductor.py under the torch._Dynamo.test_case I got the following error

: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

it's the nightly pytorch with the version '1.14.0.dev20221031'
it's the VM with 18.04.1-Ubuntu SMP that has a100 that I am using.
i can sucessfully run all the triton examples from triton repo but not from torch-inductor due to the error here

### Error logs

pytorch/test/inductor$ python test_torchinductor.py
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered C

**Comment by desertfire** [comment]
Can't reproduce locally. Which triton version are you using? With https://github.com/pytorch/pytorch/pull/88318, you can run `make triton` to install the pinned version of triton.

**Comment by stephen-youn** [comment]
i just used the version that's instructed here
https://github.com/pytorch/torchdynamo
pip3 install -U "git+https://github.com/openai/triton@af76c989eb4799b015f8b288ccd8421558772e56#subdirectory=python"
shouldn't it work?

**Comment by desertfire** [comment]
I think you are using an old version of README. We do need to update triton periodically. `https://github.com/pytorch/pytorch/blob/master/.github/ci_commit_pins/triton.txt` would be a reliable source for checking the current version we are using. If you pytorch from source, you can also use `make triton` in the pytorch source directory.

**Comment by desertfire** [comment]
cc @msaroufim , I think you removed the trition install instruction from README recently. Can you help to add some updated instruction based on the last comment? I do feel our user need a clear instruction on this one. Thanks a lot!

**Comment by msaroufim** [comment]
So another idea is at the very last step of source installation instructions for pytorch instead of running `python setup.py install` https://github.com/pytorch/pytorch

We could instead recommend users run something like `pip install -e .[dynamo] --extra-index-url https://download.pytorch.org/whl/nightly/cu117/` which should automatically pull the latest pin https://github.com/pytorch/pytorch/blob/master/setup.py#L988

I also wonder why pytorch official docs calls `python setup.py` directly my understanding is `pip install` is the standard 

cc: @williamwen42 @malfet

**Comment by williamwen42** [comment]
Triton should be included in the current install command `pip3 install numpy --pre torch[dynamo] --force-reinstall --extra-index-url https://download.pytorch.org/whl/nightly/cu117`.

As for building from source, `python setup.py` seems fairly standard. The confusion here is that we don't have an instruction for installing triton if user is building from source, correct? We can add into the dynamo readme to run `make triton` or `pip install --pre torchtriton --extra-index-url https://download.pytorch.org/whl/nightly/cu117`

**Comment by soumith** [comment]
> I also wonder why pytorch official docs calls python setup.py directly my understanding is pip install is the standard

Because `pip install ` will not print the build log to stdout until after it has finished building the wheel or runs into an error.
Considering how long pytorch takes to build, you'd be wondering if things are still working or not

**Comment by desertfire** [comment]
Close due to inactivity. Feel free to reopen if needed.
