### ISSUE TITLE
AttributeError: 'DDPMPipeline' object has no attribute '__code__'

### ISSUE THREAD

**Issue by mreso** [pytorch/torchdynamo#1825]
### 🐛 Describe the bug

Hi,

Optimizing a DiffuserPipeline (e.g. DDPMPipeline, StableDiffusionPipeline) with dynamo fails with:

```
AttributeError: 'DDPMPipeline' object has no attribute '__code__'
```

Here is a simple repro:
```
import torch
import torch._dynamo as dynamo
from diffusers import DDPMPipeline, DDPMScheduler, UNet2DModel

model = UNet2DModel(
    sample_size=128,  # the target image resolution
    in_channels=3,  # the number of input channels, 3 for RGB images
    out_channels=3,  # the number of output channels
    layers_per_block=2,  # how many ResNet layers to use per UNet block
    block_out_channels=(128, 128, 256, 256, 512, 512),  # the number of output channes for each UNet block
    down_block_types=( 
        "DownBlock2D",  # a regular ResNet downsampling block
        "DownBlock2D", 
        "DownBlock2D", 
        "DownBlock2D", 
        "AttnDownBlock2D",  # a ResNet downsampling block with spatial self-attention
        "DownBlock2D",
    ), 
    up_block_types=(
        "UpBlock2D",  # a regular ResNet upsampling block
        "AttnUpBlock2D",  # a ResNet upsampling block with spatial self-attention
        "UpBlock2D", 
        "UpBlock2D", 
        "UpBlock2D", 
        "UpBlock2D"  
      ),
)

noise_scheduler = DDPMScheduler(num_train_timesteps=1000)

pipeline = DDPMPipeline(unet=model, scheduler=noise_scheduler)

pipeline = torch._dynamo.optimize('inductor')(pipeline)
```

For a StableDiffusionPipeline (which fails as well when using the compiler directly) we can use the decorator on a trivial function like:
```
@dynamo.optimize('inductor')
def apply(x):
   pipeline(x)
```
But this does not work for DDPMPipeline. Will create a separate issue for this.

### Error logs

```
Traceback (most recent call last):
  File "/data/home/mreso/torchdynamo/no_code_property.py", line 49, in <module>
    pipeline = torch._dynamo.optimize('inductor')(pipeline)
  File "/fsx/users/mreso/conda/envs/tdn/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 175, in __call__
    always_optimize_code_objects[fn.__code__] = True
AttributeError: 'DDPMPipeline' object has no attribute '__code__'
```

### Minified repro

not applicable

**Comment by anijain2305** [comment]
Can you also add the code to invoke the pipeline with some input?

Basically, changing the last line to 

~~~

pipeline.__call__ = torch._dynamo.optimize('inductor')(pipeline.__call__)
~~~

works for me. But, it would be good to actually see the invocation to come up with a better solution.

**Comment by mreso** [comment]
Thanks @anijain2305 [88293](https://github.com/pytorch/pytorch/pull/88293) fixes this indeed. 

Just for completion an invocation of the pipeline could looks like this:
```
pipeline(
    batch_size = 16, 
    generator=torch.manual_seed(42),
    )
```

Another work-around for me was to only compile the model and not the complete pipeline, but I thought I flag it as users might want to just wrap the whole thing. And there are cases (like when loading a pretrained pipeline) where we need to jump through some hoops and access pipeline internals to compile the model only.

**Comment by anijain2305** [comment]
@mreso I think we should rely on the user to explicitly call dynamo.optimize on __call__. Its not clear otherwise what to optimize. For example, user class can have hundreds of methods, should we call optimize on all methods, or should we just call it on `__call__`. Given this ambiguity, it might be cleaner to ask user to inplace modify the relevant method.

I have added a runtime exception here - https://github.com/pytorch/pytorch/pull/88629

**Comment by anijain2305** [comment]
Hi Mathias, can we close this one? The decision for now is to wrap it up it a separate function.

**Comment by mreso** [comment]
Sure, works for me
