### ISSUE TITLE
incorrect arg count <bound method BuiltinVariable.call_dict of BuiltinVariable(dict)> missing a required argument: 'arg'

### ISSUE THREAD

**Issue by SeaOfOcean** [pytorch/torchdynamo#1832]
### 🐛 Describe the bug

call dict throws warning incorrect arg count <bound method BuiltinVariable.call_dict of BuiltinVariable(dict)> missing a required argument: 'arg'

### Error logs

torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable.call_dict of BuiltinVariable(dict)> missing a required argument: 'arg'
{}

### Minified repro

```
import torch._dynamo

@torch._dynamo.optimize('eager')
def test_call_dict():
    a = dict()
    return a

res = test_call_dict()
print(res)
```

**Comment by yanboliang** [comment]
@SeaOfOcean This is not a bug, this is a warning to indicate we switch into another branch in the internal implementation. In this case, it fall into [this branch](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/variables/builtin.py#L343) and works well. I think we should improve the log in case it confuses users.

**Comment by yanboliang** [comment]
Sent https://github.com/pytorch/pytorch/pull/88409 to improve log.
