### ISSUE TITLE
With fixed index_add decomposition, compile_fx produces wrong graph

### ISSUE THREAD

**Issue by ngimel** [pytorch/torchdynamo#1863]
With patched https://github.com/pytorch/pytorch/pull/87183, the following script produces wrong results, the returned value is same as input, nothing is added, `index_put_` from index_add decomposition is DCE'd. The relevant change in unsqueezing 0d input in index_add decomposition, which is necessary because otherwise index_put should error out. It doesn't currently in inductor, but that's a different bug. 
```
import torch
import torch._dynamo

@torch._dynamo.optimize("inductor")
def fn(x, index, src):
    return torch.index_add(x, 0, index, src)


x = torch.ones((), device="cuda")
index = torch.tensor([0], device="cuda")
src = torch.tensor(2.3, device="cuda", requires_grad=True) #requires_grad=False produces correct answer

print(fn(x, index, src))
```
Note, if `src` doesn't require grad, the answer is correct, and, in fact, fx graph that inductor is getting is already wrong (no `index_put`) if `requires_grad`=True

cc @chillee, @bdhirsh for ideas what's going wrong

**Comment by ngimel** [comment]
Also cc @ezyang in case https://github.com/pytorch/pytorch/pull/88063 has something to do with it.

**Comment by ezyang** [comment]
@bdhirsh this is the thing where if a decomposition mutates, it needs to get functionalized again, right? The original code accidentally works because mutating a non-view has a special hack to avoid DCE; but in this case the view thwarts that hack. The workaround is to redo the decomposition so it doesn't have mutation.

**Comment by ngimel** [comment]
The decomposition is for inplace op (`inded_add_`) so I don't see how we can redo it without mutation. I'd gladly have decompositions for out-of-place ops (`index_add`, `index_put` etc) and hope that compiler will do the right thing, but that's not what I'm getting from trace, even if user calls `index_add` the trace will have `.clone(); index_add_()`

**Comment by eellison** [comment]
We could also defer some decompositions post aot autograd ?

**Comment by ezyang** [comment]
Yeah. The only downside is you can no longer partition through the (now) decomposed op, but idk how often that helps. Maybe @Chillee knows

**Comment by lezcano** [comment]
I like the approach that Inductor took of implementing `aten.index_put_` and implementing most the other things in terms of it. 

In general, we could end up having a (small) subset of "admissible in-place ops" which could be made into prims. Of course, if there are subsystems that do not support in-place mutation, they could always implement these by implementing them in an out-of-place fashion and then copying the result into the original tensor.

**Comment by eellison** [comment]
@lezcano are you working on this ?

**Comment by lezcano** [comment]
Sorry, this week and the next one are somewhat packed for me. I will try to put together a PR with the necessary fixes to land this one this week though.
