### ISSUE TITLE
Accuracy degradation on hf text classification fine tuning

### ISSUE THREAD

**Issue by msaroufim** [pytorch/torchdynamo#1869]
Repro from @sgugger from this repo https://github.com/sgugger/torchdynamo-tests/tree/main#scripts

1. Install dependencies https://github.com/sgugger/torchdynamo-tests/pull/1
2. Launch the script `accelerate launch --config_file configs/base_fp32.yaml scripts/text_classification.py --task_name mrpc`

**Comment by msaroufim** [comment]
I haven't checked if this is a 1 step vs n step issue. Regardless @anijain2305 do we have any longer accuracy benchmarks we could use as a baseline?

**Comment by eellison** [comment]
@msaroufim would it be possible for you to run the accuracy minifier on this ?

**Comment by msaroufim** [comment]
Accuracy minifier did not work

A simpler repro is `TORCHDYNAMO_REPRO_AFTER="aot" TORCHDYNAMO_REPRO_LEVEL=4 accelerate launch --config_file configs/base_fp32.yaml scripts/text_classification.py --task_name mrpc --dynamo_backend inductor`

Then try running the launcher and it won't error out

**Comment by anijain2305** [comment]
Is the accuracy issue resolved?

**Comment by msaroufim** [comment]
Yes, after averaging over 50 runs and enabling random fallback the accuracy degradation goes away but it's very possible to pick unlucky seeds for torch. There isn't a good way to pick a global accuracy seed for triton yet. Even though this was resolved this was kind of a pain to analyze so we probably need some better tooling. Discussing with @vkuzo first week of Jan on what we could do better here
