### ISSUE TITLE
Getting started example is not fused? (sequential pointwise ops)

### ISSUE THREAD

**Issue by msaroufim** [pytorch/torchdynamo#1871]
I'm sanity checking all the docs and I noticed that when I run the hello world example (I made a few tweaks now) the two pointwise sin ops don't actually get fused

```python

from torch._dynamo import optimize
import torch

def fn(x):
    a = torch.sin(x)
    b = torch.sin(a)
    return b

input_tensor = torch.randn(10000).to(device="cuda:0")
opt_fn = optimize("inductor")(fn)
a = opt_fn(input_tensor)
```

When I run this

```python
TORCHINDUCTOR_TRACE=1 python trig.py 
```

I get

```python
@triton.jit
def kernel(in_ptr0, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xnumel = 10000
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK])
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (x0), xmask)
    tmp1 = tl.sin(tmp0)
    tmp2 = tl.sin(tmp1)
    tl.store(out_ptr0 + (x0 + tl.zeros([XBLOCK], tl.int32)), tmp2, xmask)
```

Where you can see that the sin ops are not fused since there's two tmp variables created if you scroll further down there is a function indicating that these two sins should be fused

` triton_fused_sin_1_sin0.run(arg0_1, buf0, 10000, grid=grid(10000), stream=stream0)`

My bad for merging this example in the first place but I figured `cos,sin` where a good way to showcase how a simple fusion works and it was this example that made me get it https://horace.io/brrr_intro.html cc @Chillee

Maybe this is expected behavior and Triton does the fusing? idk. But would appreciate pointers on how to visually showcase any fusion to a user

EDIT: I did the same thing with `torch.relu` and they're also not fused  `tmp1 = tl.maximum(0, tmp0)
    tmp2 = tl.maximum(0, tmp1)`

**Comment by ngimel** [comment]
This example demonstrates fusion, triton does the fusing. The important thing is that both `sin` ops happen inside a single kernel, and `tmp` variables are held in registers with a very fast access.

**Comment by msaroufim** [comment]
Thank you that clarifies things a lot
