### ISSUE TITLE
[fake_tensor] hf_Longformer, AllenaiLongformer

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#1887]
### Error logs

~~~
Traceback (most recent call last):
  File "/scratch/anijain/work/pytorch/torch/_dynamo/utils.py", line 1086, in run_node
    return getattr(args[0], node.target)(*args[1:], **kwargs)
  File "/scratch/anijain/work/pytorch/torch/_subclasses/fake_tensor.py", line 879, in __torch_dispatch__
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/scratch/anijain/work/pytorch/torch/_subclasses/fake_tensor.py", line 366, in data_dep
    raise DataDependentOutputException(func)
torch._subclasses.fake_tensor.DataDependentOutputException: aten._local_scalar_dense.default

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/anijain/work/pytorch/torch/_dynamo/utils.py", line 1050, in get_fake_value
    return wrap_fake_exception(
  File "/scratch/anijain/work/pytorch/torch/_dynamo/utils.py", line 729, in wrap_fake_exception
    return fn()
  File "/scratch/anijain/work/pytorch/torch/_dynamo/utils.py", line 1051, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/scratch/anijain/work/pytorch/torch/_dynamo/utils.py", line 1093, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_method view(*(FakeTensor(FakeTensor(..., device='meta', size=(12, 1024, 64)), cpu), 12, FakeTensor(FakeTensor(..., device='meta', size=(), dtype=torch.int64), cpu), 512, 64), **{}):
aten._local_scalar_dense.default
(scroll up for backtrace)
~~~

### Minified repro

~~~

def fn(x):
    return x.view(
        12,
        torch.div(1024, 512, rounding_mode="trunc"),
        512,
        64,
    )
x = torch.randn(torch.Size([12, 1024, 64]))
opt_fn = torch._dynamo.optimize("eager")(fn)
opt_fn(x)

~~~

**Comment by bdhirsh** [comment]
Not sure about the error message, but the fact that the repro involves an output that is a view of the input makes me think that https://github.com/pytorch/pytorch/pull/88817 will solve it. I'm still refactoring / fixing stuff but when the PR is in a better state I'll check this repro with it.

**Comment by bdhirsh** [comment]
Nevermind, this is unrelated. It looks like `tmp = torch.div(int, int)` returns a scalar-tensor, and fake tensor doesn't support const prop on it for some reason (we later try to call `tmp.item()` to pass the scalar-tensor into a view op, which requires grabbing the constant value from it).

I'm not sure what the state of const-prop in fake tensor is, but we can either fix it, or get dynamo to graph break on it (i'm doing something similar as a stop-gap for torch.div(symint, symint) here: https://github.com/pytorch/pytorch/pull/88817/files#diff-7bd43c6b174845f3450be42c8460ed021d1b39a98510cbea5d4e7e3a0b9d8d4fR384)

**Comment by eellison** [comment]
We should be able to handle this without graph breaking, but the real bug is that no graph break is forced. I think this is a recent bug that was introduced - we used to graph break.

There is logic for that [here](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/utils.py#L1056), I'm bisecting why it's not being triggered.

**Comment by eellison** [comment]
Dupe issue of https://github.com/pytorch/torchdynamo/issues/1886
