### ISSUE TITLE
tensor.new doesn't work well if not enable dynamic shapes mode

### ISSUE THREAD

**Issue by yanboliang** [pytorch/torchdynamo#191]
*This is the 1/N issue found from https://github.com/facebookresearch/torchdynamo/issues/156.*

Problem:
* Failed test example: [```test_DingKe_pytorch_workplace.py:BinaryTanh```](https://github.com/yanboliang/pytorch-jit-paritybench/blob/master/generated/test_DingKe_pytorch_workplace.py)
* Error: ``` IndexError: too many indices for tensor of dimension 1```

Minimal code to reproduce:
```
def fn(x):
   return x.new(x.size())

with torchdynamo.optimize(my_compiler):
    y = fn(torch.rand((3, 2)))
    print(y.size())
```
* The above code's output is:
  * Correct result ```torch.Size([3, 2])``` if enable dynamic shapes. 
  * Incorrect result ```torch.Size([2])``` if don't enable dynamic shapes.

* However, it works well in pytorch:
```
def fn(x):
   return x.new(x.size())

y = fn(torch.rand((3, 2)))
print(y.size())
```
* The above code outputs correct result: ```torch.Size([3, 2])```.

Proposed solutions & discussions:
* It seems [```tensor.repeat```](https://github.com/facebookresearch/torchdynamo/blob/main/torchdynamo/variables/tensor.py#L299) and [```tensor.nonzero```](https://github.com/facebookresearch/torchdynamo/blob/main/torchdynamo/variables/tensor.py#L309) function raise unimplemented if not enable dynamic shapes mode, we can have similar handling for ```tensor.new```.
  * It will break one test case [```test_reformer_sorting```](https://github.com/facebookresearch/torchdynamo/blob/main/tests/test_repros.py#L1020), as we compare the result between torchdynamo and native pytorch, need to skip this check if we go with this way.
* It works well on pytorch, so I suspect ```OutputGraph``` which extends from ```fx.Tracer``` has bug when encountering ```torch.Size```. I manually create a proxy for ```torch.Size``` and insert it into the graph can fix this error, but it's definitely not the right solution. I just bring this observation here to provide more details. Or are there bugs at ```fx.Tracer``` side when handling ```tensor.new```? 

Do you have any suggestion on this issue? @jansel

**Comment by jansel** [comment]
This reads like just a bug.

In static shape mode `x.size()` should return the constant `(3,2)`. So I'd expect this to do the same thing as `x.new((3,2))`, if it doesn't, we should figure out why that is the case.

**Comment by yanboliang** [comment]
Update: more evidence shows it may be a bug in ```fx.Tracer```. I wrote down the bellow code to simulate the result after torchdynamo calling ```fx.Tracer.create_proxy``` at [here]():
```
import torch.fx


class MyTracer(torch.fx.Tracer):
    def __init__(self):
        super(MyTracer, self).__init__()
        self.graph = torch.fx.Graph()

tracer1 = MyTracer()
input_x_node = tracer1.create_proxy("placeholder", "x", (), {}, type_expr=torch.Tensor)
result_node = tracer1.create_proxy("call_method", "new", (input_x_node, torch.Size((3, 2))), {})
tracer1.create_node("output", "output", (tracer1.create_arg(result_node),), {})

root = torch.nn.Module()
gm = torch.fx.GraphModule(root, tracer1.graph)
gm.recompile()
print(gm)
print(gm(torch.rand([3, 2])))
```
The output is:
```
GraphModule()



def forward(self, x : torch.Tensor):
    new = x.new((3, 2));  x = None
    return new
    
tensor([3., 2.])
```
So ```fx.Tracer``` recognizes ```torch.Size``` type as ```tuple```, passes ```tuple (3, 2)``` as argument and finally generates a new ```tensor([3., 2.])``` rather than a tensor with size (3, 2). 

As I'm new to ```fx.Tracer```, feel free to correct me if I'm wrong.

**Comment by jansel** [comment]
I think the root of the problem is:
```
>>> torch.tensor([]).new((2,3))
tensor([2., 3.])
>>> torch.tensor([]).new(torch.Size((2,3)))
tensor([[-6.7989e-06,  3.0757e-41, -3.5433e-04],
        [ 3.0757e-41,  1.1210e-43,  0.0000e+00]])
>>> 
```

`torch.Tensor.new` acts differently with a `Size` input versus a `tuple` input.

Size/Tuple are usually interchangeable.

As a workaround, I'd suggest detecting calls to `x.new(s)` with a `torch.Size` arg, and just rewriting them to:
```
torch.empty(s, dtype=x.dtype, device=x.device, ...)
```

`Tensor.new` is deprecated anyway.
