### ISSUE TITLE
[Inductor] [CPU] Crash failure in timm_model dla102

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/torchdynamo#1945]
### 🐛 Describe the bug

This failure found in the latest [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/torchdynamo/issues/1617#issuecomment-1330427371) refresh test with below error log

SW information

|  SW   | Nightly commit  |  Master/Main commit |
|  ----  | ----  | ---- |
| Pytorch  | [f8506fb](https://github.com/pytorch/pytorch/commit/f8506fb3417db6d5f162fc09960aaa0bc80441ac) | [39449ea](https://github.com/pytorch/pytorch/commit/39449ea61d9a6644731687219282f610cbf7cf54) |
| Torchbench  | / |[2e5d723](https://github.com/pytorch/benchmark/commit/2e5d7237935aa95a5c028d1d84be785d173bff95) |
| torchaudio  | [c44b576](https://github.com/pytorch/audio/commit/c44b5766461640986780debd4f62b27deae22407) | [8ba323b](https://github.com/pytorch/audio/commit/8ba323bbf8e30e838ce0f6278412f0decd44c520) |
| torchtext  | [ebcfed5](https://github.com/pytorch/text/commit/ebcfed5e52f5e5f9246f1560b31377838fc9a234) |[b3390fb](https://github.com/pytorch/text/commit/b3390fb21f9d1855f4c282036701c717c0f9b335) |
| torchvision  | [d0f2888](https://github.com/pytorch/vision/commit/d0f28881acba3ea7f739f96fcf9eafc68b0d2f7c) | [5b4f79d](https://github.com/pytorch/vision/commit/5b4f79d9ba8cbeeb8d6f0fbba3ba5757b718888b) |

### Error logs

```
Traceback (most recent call last):
  File "benchmarks/dynamo/timm_models.py", line 322, in <module>
    main(TimmRunnner())
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 1669, in main
    return maybe_fresh_cache(run, args.cold_start_latency and args.only)(
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 850, in inner
    return fn(*args, **kwargs)
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2007, in run
    ) = runner.load_model(device, model_name, batch_size=batch_size)
  File "benchmarks/dynamo/timm_models.py", line 207, in load_model
    model.to(
UnboundLocalError: local variable 'model' referenced before assignment

```

### Minified repro

```
Not see repro.py generated after set ENV TORCHDYNAMO_REPRO_AFTER

Reproduce cmd:

python benchmarks/dynamo/timm_models.py --performance --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only=dla102   --batch_size 1 --threads 1 --cold_start_latency

```

**Comment by williamwen42** [comment]
Test runs fine locally.

**Comment by ESI-SYD** [comment]
Thanks, passed in latest benchmark, close now.
