### ISSUE TITLE
RuntimeError: Failed running call_function aten.uniform(...

### ISSUE THREAD

**Issue by silvasean** [pytorch/torchdynamo#1954]
### 🐛 Describe the bug

```
import torch
import torch._dynamo as dynamo

@dynamo.optimize()
def forward(x):
    return torch.ops.aten.uniform(x)

forward(torch.rand(1000))
```

Error
```
RuntimeError: Failed running call_function aten.uniform(*(FakeTensor(FakeTensor(..., device='meta', size=(1000,)), cpu),), **{}):
uniform() missing 2 required keyword-only arguments: 'dtype' and 'device'
```

### Error logs

Ful log: https://gist.github.com/silvasean/c502b2a4df4feb97403cdbd8b56eb1b5

### Minified repro

See above

**Comment by yanboliang** [comment]
I think this is a bug about the [uniform ref implementation](https://github.com/pytorch/pytorch/blob/master/torch/_refs/__init__.py#L4689), working on a PR to fix it.

**Comment by kvathupo** [comment]
I'm not sure this is a bug: `torch.ops.aten.uniform()` just fills a tensor of the input shape with values from some uniform distribution. `torch.ops.aten.uniform(x.size(), dtype=x.dtype, device=my_device)` should work to generate a tensor of the input dimensions.

That said, I suppose it's reasonable to expect to be able to call it like `torch.ops.aten.randn`.

**Comment by yanboliang** [comment]
The fix has been merged, @silvasean can we close this?

**Comment by silvasean** [comment]
Feel free to close when the test case in the OP passes!
