### ISSUE TITLE
Minifier fails for wav2vec

### ISSUE THREAD

**Issue by wconstab** [pytorch/torchdynamo#1959]
### 🐛 Describe the bug

Building on https://github.com/pytorch/torchdynamo/issues/1956,

the whole-model repro for wav2vec posted there fails to run with the minifier for me on master @ 2ea32f41f4b4c3d0cbb9834186fdfe404e0d4c2a

my w2v.py here is copied from #1956, namely 

```
 from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC
 from datasets import load_dataset
 import torch
 
 # load model and processor
 processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-large-960h-lv60-self")
 model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-large-960h-lv60-self")
 model=torch.compile(model)
     
 # load dummy dataset and read soundfiles
 ds = load_dataset("patrickvonplaten/librispeech_asr_dummy", "clean", split="validation")
 
 # tokenize
 input_values = processor(ds[0]["audio"]["array"], return_tensors="pt", padding="longest").input_values
 
 # retrieve logits
 logits = model(input_values).logits
 
 # take argmax and decode
 predicted_ids = torch.argmax(logits, dim=-1)
 transcription = processor.batch_decode(predicted_ids)
 ```

### Minified repro

`TORCHDYNAMO_REPRO_AFTER="aot" python w2v.py` produces a minifier_launcher, but running it claims 
`python torchdynamo_debug/run_2022_12_05_23_06_50_594983/minifier/minifier_launcher.py`
```
Traceback (most recent call last):
  File "torchdynamo_debug/run_2022_12_05_23_06_50_594983/minifier/minifier_launcher.py", line 205, in <module>
    minifier(
  File "/scratch/whc/work/pytorch/torch/_functorch/fx_minifier.py", line 96, in minifier
    raise RuntimeError("Input graph did not fail the tester")
RuntimeError: Input graph did not fail the tester
```

`TORCHDYNAMO_REPRO_AFTER="dynamo" python w2v.py` actually segfaults for me

**Comment by wconstab** [comment]
oops, i forgot to use `TORCHDYNAMO_REPRO_LEVEL=4`.

**Comment by anijain2305** [comment]
You don't need level 4. Level 4 is for accuracy. The command that you have is correct.

Your observation is still correct. There is a minifier_launcher.py but it does not fail.

I can assign it to myself.

**Comment by anijain2305** [comment]
Real bug for the model - https://github.com/pytorch/pytorch/issues/90260

Why does minifier (repro_after="aot") does not work? Again the same reason as above issue. The small difference in code path between minified_repro and compiler led to this rare divergence.
