### ISSUE TITLE
[Inductor] [CPU] Accuracy failure in huggingface model XLNetLMHeadModel on WW03.2

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/torchdynamo#2036]
### 🐛 Describe the bug

Compare with the ww02.4, there is a accuracy failure on Huggingface model XLNetLMHeadModel on [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/torchdynamo/issues/1617#issuecomment-1384851687) on ww03.2:

WW03.2 SW info:

SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[868797a](https://github.com/pytorch/pytorch/commit/868797ac1f173cfe188a0d0641297f9ddb372348)|[d41b5d7](https://github.com/pytorch/pytorch/commit/d41b5d7c145f3e09c7223c2b707933266241ec9b)
Torchbench|/|[bbdc777](https://github.com/pytorch/benchmark/commit/bbdc777837bf0c02b00e20b9178a0f6a9595bda4)
torchaudio|[ecc2781](https://github.com/pytorch/audio/commit/ecc2781b5b5c353e85a8ca9f16741cf92dd08344)|[4a037b0](https://github.com/pytorch/audio/commit/4a037b03915c4f6f81407e697fb11a7e7ace27fa)
torchtext|[112d757](https://github.com/pytorch/text/commit/112d757efd2482ea5f60bc23d85c2c09f0cfde61)	| [c7cc5fc](https://github.com/pytorch/text/commit/c7cc5fc1e669f548eef619ae055690831d6cc75e)
torchvision|[ac06efe](https://github.com/pytorch/vision/commit/ac06efed4ad2867c68e6b49ac31b554fcbbaa472)|[35f68a0](https://github.com/pytorch/vision/commit/35f68a09f94b2d7afb3f6adc2ba850216413f28e)
torchdata|[049fb62](https://github.com/pytorch/data/commit/049fb626615e6cd965897af8fea2fa73cecd6a2a)|[c0934b9](https://github.com/pytorch/data/commit/c0934b9afa96458c0f8aa3bef528830835c22195)
dynamo_benchmarks|[fac4361](https://github.com/pytorch/pytorch/commit/fac4361e840f6da36ba8c83359c7d0ab5e00cf37)|/

WW02.4 SW info:

SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[466be3f](https://github.com/pytorch/pytorch/commit/466be3f2ad598da2cb3432b1ab213c8a184ca377)|[364f526](https://github.com/pytorch/pytorch/commit/364f526b9cdf9818a7647b5e637efdee825d61a1)
Torchbench|/|[bbdc777](https://github.com/pytorch/benchmark/commit/bbdc777837bf0c02b00e20b9178a0f6a9595bda4)
torchaudio|[ecc2781](https://github.com/pytorch/audio/commit/ecc2781b5b5c353e85a8ca9f16741cf92dd08344)|[4a037b0](https://github.com/pytorch/audio/commit/4a037b03915c4f6f81407e697fb11a7e7ace27fa)
torchtext|[112d757](https://github.com/pytorch/text/commit/112d757efd2482ea5f60bc23d85c2c09f0cfde61)	| [c7cc5fc](https://github.com/pytorch/text/commit/c7cc5fc1e669f548eef619ae055690831d6cc75e)
torchvision|[ac06efe](https://github.com/pytorch/vision/commit/ac06efed4ad2867c68e6b49ac31b554fcbbaa472)|[35f68a0](https://github.com/pytorch/vision/commit/35f68a09f94b2d7afb3f6adc2ba850216413f28e)
torchdata|[049fb62](https://github.com/pytorch/data/commit/049fb626615e6cd965897af8fea2fa73cecd6a2a)|[c0934b9](https://github.com/pytorch/data/commit/c0934b9afa96458c0f8aa3bef528830835c22195)
dynamo_benchmarks|[fac4361](https://github.com/pytorch/pytorch/commit/fac4361e840f6da36ba8c83359c7d0ab5e00cf37)|/

### Error logs

```
cpu  eval  XLNetLMHeadModel                   [2023-01-16 07:53:30,105] torch._dynamo.utils: [ERROR] RMSE (res-fp64): 0.01949, (ref-fp64): 0.00000 and shape=torch.Size([])
[2023-01-16 07:53:30,106] torch._dynamo.utils: [ERROR] Accuracy failed for key name loss
FAIL

```

### Minified repro

```
python -m torch.backends.xeon.run_cpu --core_list 0 --ncores_per_instance 1 benchmarks/dynamo/huggingface.py --accuracy --float32 -dcpu --inductor  --no-skip --dashboard --only XLNetLMHeadModel --batch_size 1 --threads 1


```

**Comment by Guobing-Chen** [comment]
Fixed with PR#92299
