### ISSUE TITLE
torch._inductor.lowering: [WARNING] using triton random, expect difference from eager

### ISSUE THREAD

**Issue by vgoklani** [pytorch/torchdynamo#2042]
### 🐛 Describe the bug

Can someone please explain what this error means:

    torch._inductor.lowering: [WARNING] using triton random, expect difference from eager

thanks

**Comment by jansel** [comment]
TorchInductor (backend for torch.compile) uses a different random number generator than non-torch.compile pytorch (eager mode).

It is safe to ignore that message and perhaps we should even lower it to an INFO.  It was mainly useful for correctness internal testing.
