### ISSUE TITLE
dead links in README and TROUBLESHOOTING.

### ISSUE THREAD

**Issue by kevint324** [pytorch/torchdynamo#2051]
all the links in

https://github.com/pytorch/torchdynamo/blob/main/documentation/TROUBLESHOOTING.md

and 

https://github.com/pytorch/torchdynamo/blob/main/README.md

are dead

like https://pytorch.org/docs/master/dynamo/

**Comment by mlazos** [comment]
The current troubleshooting doc is [here](https://pytorch.org/docs/stable/dynamo/troubleshooting.html#diagnosing-runtime-errors)

I can take a look at updating these links.

**Comment by mlazos** [comment]
fixed by https://github.com/pytorch/torchdynamo/pull/2052
