### ISSUE TITLE
torch.compile cannot accelerate GPTBigCode inference process

### ISSUE THREAD

**Issue by Xingxiangrui** [pytorch/torchdynamo#2053]
As your team desecribed,  Torch.compile is an useful tool to accelerate models that it can accelerate tests across 163 open-source models from [Hugging Face Transformers](https://huggingface.co/docs/transformers/index),

However I found it can not accelearte GPTBigCode model. 

I just want to accelerate the inference process:

## the benchmark inference process is like this: 

```
from transformers import GPTBigCodeForCausalLM, GPTBigCodeConfig, Autotokenizer

chekcpoint = "bigcode/starcoder"

tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForCausalLM.from_pretrained(checkpoint).to(device)

inputs = tokenizer.encode("def print_hello_world():", return_tensors="pt").to(device)
outputs = model.generate(inputs)
print(tokenizer.decode(outputs[0]))

```

## accelerated model should be like this:

```
compiled_model = torch.compile(model, mode='max-autotune') # I also tried 'default' and 'reduce-overhead'

with torch.no_grad():  # this is added because I just want to inference the model. I tried with and without this line
    outputs = compiled_model .generate(inputs)

print(tokenizer.decode(outputs[0]))

```

## problem

* I already know that there are three mode like 'max-autotune' and tried them all;
* I also know that model will be very slow at the first time, so I shoud run it repeatly to warm up.

However, the upper steps seem to have no effect. 
I just want to accelerate the Inference process using model.generate in transformer. accelerate the training process is useless for me.

I have seen some cases that other people tried about the torch.compile to accelerate the Transformer inference process, some cases indicates that torch.compile are useful the some cases indicates torch.compile is useless.

Here is my question: 

* How can I accelerate GPTBigCode inference process ? 
* Is the torch.compile tested on these kinds of Language models? 
* Is torch.compile matched model.generate process ?
* Could you please give us a support list or examples ?

Thanks for you answer.

**Comment by jansel** [comment]
If you want to compile the `.generate()` function you need to do something like:
```
model.generate = torch.compile(model.generate)
```
