### ISSUE TITLE
Support `enum.Enum` comparisons without graph breaks

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#211]
From @vkuzo 

```
class Foo(enum.Enum):        
    FOO = 0                  
                             
def fn(x, foo):              
    if foo is Foo.FOO:       
        x = torch.add(x, 1.0)
    return x                 
```

> Currently the enum gets resolved to UserDefinedObjectVariable which doesn't work for comparisons, do you recommend that a new variable type is needed for an enum value (or could it conceptually map to some existing one), or that we add some logic to UserDefinedObjectVariable to enable comparisons for an allowlist of types?

This seems like something reasonable to support.  I think mapping it to a new variable type (perhaps a subclass of an existing one) would be the easiest approach.

**Comment by vkuzo** [comment]
I tried this: https://gist.github.com/vkuzo/a5f5f5c7f96c31dbccd378a27bc87e80

and getting this error when running the test case: https://gist.github.com/vkuzo/3c39d8f9ecb3523232edf6bf7fc87f34

```
GUARDS:
 - local 'x' TENSOR_MATCH
 - local 'foo' FUNCTION_MATCH
 - global 'Foo' TYPE_MATCH
 - global 'torch' FUNCTION_MATCH
 - global 'Foo.FOO' FUNCTION_MATCH

libc++abi: terminating with uncaught exception of type c10::Error: Tensors of type TensorImpl do not have sizes
Exception raised from sizes_custom at ../c10/core/TensorImpl.cpp:362 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::_
_1::allocator<char> >) + 98 (0x105977162 in libc10.dylib)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__1::basic_string<char, std::_
_1::char_traits<char>, std::__1::allocator<char> > const&) + 106 (0x10597587a in libc10.dylib)
frame #2: c10::TensorImpl::sizes_custom() const + 92 (0x10595ec8c in libc10.dylib)
frame #3: (anonymous namespace)::TensorGuards_init((anonymous namespace)::TensorGuards*, _object*, _object*) + 93
7 (0x106187179 in _guards.cpython-38-darwin.so)
...
frame #37: start + 462 (0x1092bf51e in dyld)

Abort trap: 6
```

the stack trace is not super informative, any tips on what could be wrong here?

**Comment by jansel** [comment]
I believe python key tracing is broken on PyTorch master.  @Chillee @ezyang might have more info on a coming fix.

I have been running on an older pytorch @ 7311390d355eb0cdbfa127cbcb3b08f8cd06738b as a workaround.

**Comment by Chillee** [comment]
@vkuzo I had this issue previously, but the issue went away after I repulled/rebuilt PyTorch/Functorch/TorchDynamo/domain libraries.

@ezyang couldn't repro on a fresh build of dynamo/domain libraries, I believe.

I'm currently split on whether this is a real bug or build issue. The fact that I previously had this issue, but at some point while rebuilding things it started working again makes me suspicious it's a build issue.

**Comment by ezyang** [comment]
PyTorch TensorImpl had a subtle ABI change recently so make sure you rebuilt everything

**Comment by vkuzo** [comment]
thanks!  vanilla rebuilding pytorch, torchvision, torchdynamo did not fix it, but adding a `std::cout`in `torchdynamo/_guards.cpp::TensorGuards_init` and rebuilding after that did fix it.  Perhaps `python setup.py clean` was not cleaning that artifact properly.

**Comment by ezyang** [comment]
It sounds like recompilation avoidance in torchdynamo is not being done correctly.

**Comment by vkuzo** [comment]
https://github.com/pytorch/torchdynamo/pull/245 fixes the original issue
