### ISSUE TITLE
Support for torch.autograd.profiler.record_function

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#219]
The [PyTorch profiler](https://pytorch.org/tutorials/beginner/profiler.html) allows users to add `profiler.record_function` to their code like this:
```
class MyModule(nn.Module):
    def __init__(self, in_features: int, out_features: int, bias: bool = True):
        super(MyModule, self).__init__()
        self.linear = nn.Linear(in_features, out_features, bias)

    def forward(self, input, mask):
        with profiler.record_function("LINEAR PASS"):
            out = self.linear(input)

        with profiler.record_function("MASK INDICES"):
            threshold = out.sum(axis=1).mean()
            hi_idx = (mask > threshold).nonzero(as_tuple=True)

        return out, hi_idx
```

Currently, TorchDynamo does not support this will break on the graph on this and fallback.

One simple thing we could do is just have TorchDynamo ignore `record_function`.

Meta Internal Link: https://fb.quip.com/fdd0AW8dYtPW

**Comment by voznesenskym** [comment]
This should be working now. @jansel to close upon confirmation.
