### ISSUE TITLE
Guards - Support inf

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#260]
Test repro from running TorchDynamo on Pytorch tests

~~~
pytest -v -s test/test_decomp.py::TestDecompCPU::test_comprehensive__masked_normalize_cpu_float64
~~~

The test fails with the following error

~~~

Traceback (most recent call last):
  File "<string>", line 3, in <lambda>
NameError: name 'inf' is not defined
ERROR RUNNING GUARDS diff_arg /fsx/users/anijain/pytorch/test/test_decomp.py:49
  ___guarded_code.valid and
  ___check_type_id(arg, 94852061388224) and
  arg == inf
NULL ERROR: torchdynamo/_eval_frame.c:240
Fatal Python error: Aborted

~~~

This is failing while executing the guard, so this is the problem with generating the guard.

The solution is to emit `float("inf")` when we see an `inf` during guard building. And similarly `-inf`

**Comment by jansel** [comment]
Another possible fix here would be to install a variable named "inf" in the scope we create for the guards.
