### ISSUE TITLE
Unify "python-key" tracing in TorchDynamo with AOTAutograd

### ISSUE THREAD

**Issue by Chillee** [pytorch/torchdynamo#271]
These are ... more or less the same underlying tracing mechanism. There's a couple of differences. Note that in all of these cases I'm referring to the specific python-key tracing used in TorchDynamo.

1. Python-key tracing doesn't support autograd, while AOTAutograd does.
2. Python-key tracing probably has less overhead since it doesn't construct an autograd.Function.
3. Python-key tracing traces factory functions, while AOTAutograd doesn't.
4. Python-key tracing actually runs the original Dynamo FX graph a node at a time, which should allow us to better preserve original line info.

As we generalize AOTAutograd to just be AOTDispatcher, it seems pretty easy to handle 1/2 (by just defaulting to the case if none of our tensors require autograd). 3 should be handled by the `__torch_dispatch__` mode tracing @samdow added. 4 is probably the trickiest one... I'm not totally sure how to handle that.

cc: @zou3519 @anjali411

**Comment by zou3519** [comment]
> Python-key tracing actually runs the original Dynamo FX graph a node at a time, which should allow us to better preserve original line info.

What's the goal here? Is it that errors being thrown should reference a line number in the source code?

**Comment by Chillee** [comment]
@zou3519 yeah - we'd like to be able to preserve line numbers through our entire tracing/compilation process.

**Comment by jansel** [comment]
Hopefully it will be easy to merge these.  They are mostly the same code.  The python-key tracing is a pretty thin wrapper above functorch that uses a `torch.fx.Interpreter`.

**Comment by zou3519** [comment]
If we have something like 
```
y = torch.sin(x)
y.backward()
```
do we want the line number information for "grad_output = x.cos()` to point to y.backward(), or torch.sin, or does it not matter because autograd is supposed to not throw any errors in the backward pass as long as the forward pass is valid?

**Comment by ezyang** [comment]
For backwards, the usual Python semantics would require us to report backward(), but knowing what forward call generated the backward node would help too

**Comment by Chillee** [comment]
This has been finished.
