### ISSUE TITLE
Slow on some small models

### ISSUE THREAD

**Issue by jiayisunx** [pytorch/torchdynamo#293]
TorchDynamo IPEX backend is slower (11%) than IPEX Graph-mode on mnasnet0_5(torchvision model) with fp32 data type and the whole process doesn’t meet guard fail. and we found that if we only run with TorchDynamo IPEX backend at first step, the performance recover to be consistent with IPEX in TorchDynamo run mode.

**Comment by voznesenskym** [comment]
Hey! I hate to nag, but this task has been open for 20 mins with no detail - would you be able to drop some detail (benchmarks, scripts, etc)?

**Comment by jiayisunx** [comment]
@voznesenskym, sorry for the late, so do you have any insights about this issue? Based on our understanding, torchdynamo.run() will also check the guard and lookup the cache, right?

**Comment by voznesenskym** [comment]
> @voznesenskym, sorry for the late, so do you have any insights about this issue? Based on our understanding, torchdynamo.run() will also check the guard and lookup the cache, right?

Sorry no, I was merely pointing out that at the time that I responded, the top level comment was empty.

**Comment by jansel** [comment]
Have you done any profiling?  Is this an overhead issue (you could try running with "eager" backend to check TorchDynamo overheads)?  A guard failing issue (try setting `torchdynamo.config.cache_size_limit=1`)?

**Comment by anijain2305** [comment]
@jiayisunx Do you still see the slowdown issue?
