### ISSUE TITLE
Dynamic module inside dynamo context is not evaluated correctly?

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/torchdynamo#319]
Minimum repro:

```
# -*- coding: utf-8 -*-
import torch
import math
import torchdynamo
from typing import List
import torchdynamo.testing
from torch import nn

class Polynomial3(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return 1 + x

with torchdynamo.optimize("eager"):
    model = Polynomial3()
    x = 10
    for t in range(2000):
        y_pred = model(x)
    print(y_pred)
```

Produces:

```
AttributeError: 'Polynomial3' object has no attribute 'training'
```

From:
```
    def NN_MODULE(self, guard: Guard):
        self.ID_MATCH(guard)
        ref = self.arg_ref(guard)
        val = self.get(guard.name)
        assert istype(val.training, bool)
        if val.training:
            self.code.append(f"{ref}.training")
        else:
            self.code.append(f"not {ref}.training"
```

I believe this is due to incorrect determination as to what is, and is not a dynamic module.

Hardcoding `def is_dynamic_nn_module(obj):` to return `True` gets me past the bug. This is not a real fix, but is indicative of us not tracking this module as dynamic correctly.

**Comment by voznesenskym** [comment]
cc: @mlazos (who reprod, huge ty) @anijain2305 @jansel

**Comment by anijain2305** [comment]
Ok, I can repro. I think this might be related to recent PR - https://github.com/pytorch/torchdynamo/pull/305. Removing the `tagging_init` passes the test.

All `torch.nn.Module` instances have a `training` member. I think monkey patching `__init__` might be upsetting it.

**Comment by voznesenskym** [comment]
It's actually not monkey patching init. It's more subtle/ annoying, but also easier to hack fix :P

So, the order of critical events is:

1) install_generation_tagging_init
2) VariableBuilder's __call__
3) _convert_frame_assert
4) NN_MODULE guard creation (which calls assert istype(val.training, bool))

Now... what's missing? We have not yet actually called init on the object! We cannot read properties off something that is not instantiated.

Adding:

```
    def __new__(cls):
        super(Polynomial3, cls).__new__(cls)
```

To the model above fixes it. This is not a real fix, but it helps us understand the root cause and how to get it around it. I am going to look into make this work correctly for inits.

**Comment by voznesenskym** [comment]
Looking at #305 (Thanks @anijain2305), I think new is more correct. We could roll back #305 but before we do so, let me see if we can maybe do something more elegant...

**Comment by yanboliang** [comment]
I hit this issue as well...

**Comment by anijain2305** [comment]
Yes, I am hitting at other places as well.

Should we revert #305 for now? As this may take some time to fix.

@mlazos
