### ISSUE TITLE
Test TorchDynamo on a wider variety of models

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#32]
Now that TorchDynamo is [working on most TorchBench models](https://dev-discuss.pytorch.org/t/torchdynamo-update-5-improved-capture-bigger-graphs/556), we should start looking for additional models to test on to continue improving coverage and robustness.

All models are welcome here, so if you have specific models in mind from a use case you are familiar with please test them and report your experiences.

For testing on Meta models, @dzhulgakov suggested that @houseroad and @divchenko would be able to provide pointers to increasingly complex models to test on.

**Comment by jansel** [comment]
@frank-wei to try applying this with fx2trt?

**Comment by ciciewang** [comment]
Victor connect to Wei to internal models. Will expand beyond Torch Bench and FAM Bench after may.

**Comment by xuzhao9** [comment]
We are also open to add more open source models to TorchBench, since that will make the test easier and is beneficial to TorchBench as well.

**Comment by anijain2305** [comment]
Closing as this is stale.
