### ISSUE TITLE
codegen doesn't works well on list variable with side effect

### ISSUE THREAD

**Issue by yanboliang** [pytorch/torchdynamo#329]
*This is the 8/N issue found from https://github.com/pytorch/torchdynamo/issues/156.*

Failed test cases: [```test_wutianyiRosun_CGNet.py```](https://github.com/jansel/pytorch-jit-paritybench/blob/570400b612332ecaec0cf850cdc70a6d4ddc374b/generated/test_wutianyiRosun_CGNet.py#L1364)

Minimal code to reproduce:
```
from typing import List
import torch
import torchdynamo

def f1(x):
    alist = []
    y = x + 1
    alist.append(y)
    print("break1") # break graph
    res = alist.pop()
    print("break2")  # break graph
    return res

def my_compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    return gm.forward

x = torch.tensor([10])

with torchdynamo.optimize(my_compiler):
    print(f1(x))
```
It throws the following error:
```
Traceback (most recent call last):
  File "example2.py", line 42, in <module>
    print(f1(x))
  File "example2.py", line 9, in f1
    def f1(x):
  File "example2.py", line 9, in f1
    def f1(x):
IndexError: list index out of range
```
It was caused by the generated code trying to access an empty list, see the generated code segment:
```
MODIFIED BYTECODE
  9           0 BUILD_LIST               0
              2 LOAD_FAST                1 (alist)
              4 LOAD_CONST               0 (None)
              6 LOAD_CONST               0 (None)
              8 BUILD_SLICE              2
             10 STORE_SUBSCR
             12 LOAD_GLOBAL              1 (print)
             14 LOAD_CONST               3 ('break2')
             16 LOAD_FAST                1 (alist)
             18 LOAD_CONST               4 (0)
             20 BINARY_SUBSCR
             22 STORE_FAST               4 (res)
             24 CALL_FUNCTION            1
             26 LOAD_GLOBAL              3 (__resume_at_48_2)
             28 ROT_TWO
             30 LOAD_FAST                4 (res)
             32 CALL_FUNCTION            2
             34 RETURN_VALUE
```
bytecode 0-10 are generated from [```self.side_effects.codegen(pass2)```](https://github.com/pytorch/torchdynamo/blob/main/torchdynamo/output_graph.py#L260) which is assigning ```alist``` to empty list.
16-20 are generated from [```pass2.foreach(stack_values)```](https://github.com/pytorch/torchdynamo/blob/main/torchdynamo/output_graph.py#L261) which is trying to rebuild the TensorVariable ```y```. As the source of ```y``` is ```GetItemSource(base=LocalSource(local_name='alist'), index=0)```, so it generates line 16-20 and causes the ```list index out of range```.

I'm thinking as the reconstruction of ```y``` depends on ```alist```, so it seems ```alist``` was used twice, so should be added into ```tempvars```? Then ```alist``` will be saved as a tmp variable before the side effects codegen, and later the tmp variable will be used. If follow this way, we should identify each element's source variable during ```self.side_effects.codegen(pass1)``` and increase corresponding [```self.uses[value]```](https://github.com/pytorch/torchdynamo/blob/main/torchdynamo/codegen.py#L124). Not sure if this is the right direction, any thought? @jansel 

BTW, I checked several other unit tests related to side effects, and found if there is graph break between any two mutation, it will throw the same error.

**Comment by jansel** [comment]
Yes this seems like a bug.  I think your hypothesis that tempvars is getting the aliasing wrong is correct.
