### ISSUE TITLE
tacotron2 hit recompilation cache limit

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#330]
```
$ ./torchbench.py -dcuda -k tacotron2
cuda eval  tacotron2                          WARNING:torchdynamo.convert_frame:torchdynamo hit recompilation cache limit (64) for function 'forward' (/home/jansel/torchbenchmark/torchbenchmark/models/tacotron2/model.py:381), due to the following guard failures: [['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0'], ['len(alignments) == 0']]
STAGE:2022-06-06 19:17:47 1113020:1113020 ActivityProfilerController.cpp:294] Completed Stage: Warm Up
STAGE:2022-06-06 19:17:48 1113020:1113020 ActivityProfilerController.cpp:300] Completed Stage: Collection
100/101 +0 frames  11s 88 graphs 3449 graph calls 27055/32825 =  82% ops  91% time
```

This warning looks a bit suspect.  Perhaps we are generating an incorrect guard in this case?

**Comment by jansel** [comment]
A similar issue is in vision_maskrcnn:
```
cuda eval  vision_maskrcnn                    WARNING:torchdynamo.convert_frame:torchdynamo hit recompilation cache limit (64) for function 'paste_mask_in_image' (/home/jansel/torchvision/torchvision/models/detection/roi_heads.py:403), due to the following guard failures: [['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118'], ['w == 118']]to diagnose recompilation issues, try using torchdynamo.utils.CompileProfiler.
WARNING:torchdynamo.convert_frame:torchdynamo hit recompilation cache limit (64) for function 'paste_mask_in_image' (/home/jansel/torchvision/torchvision/models/detection/roi_heads.py:403), due to the following guard failures: [['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118'], ['___stack0 == 118']]to diagnose recompilation issues, try using torchdynamo.utils.CompileProfiler.

```

**Comment by voznesenskym** [comment]
Small aside **orthogonal** but will help debug this kinda stuff in the future.

So I noticed something weird: 

`['len(alignments) == 0']` was being printed 64 times, when the guards were being setup as `['len(alignments) == 0']` `['len(alignments) == 1']` `['len(alignments) == 2'] ... etc etc. 

This is because of the logic here:

```
def guard_fail_hook(
    guard_fn: Callable, code: types.CodeType, f_locals: Dict[str, Any], last: bool
):
    """
    called whenever a guard fails.
    """
    if not last:
        return
```

invoked from:

```
static void call_guard_fail_hook(PyObject *hook, CacheEntry *e,
                                 PyObject *f_locals) {
  // call debugging logic when a guard fails
  PyObject *args = PyTuple_Pack(4, e->check_fn, e->code, f_locals,
                                (e->next == NULL ? Py_True : Py_False));
  NULL_CHECK(args);
  PyObject *result = PyObject_CallObject(hook, args);
  NULL_CHECK(result);
  Py_DECREF(result);
  Py_DECREF(args);
}
````
So we actually want to call this on the first, I think, not the last. 

Thoughts @anijain2305 @jansel ?

**Comment by anijain2305** [comment]
So, these cache limit breaches have been there for a while. Just that they are exposed by @wconstab recent PR which flags excessive recompiles.

* Tacotron2 recompiles is because of a while loop and graph break

<img width="955" alt="image" src="https://user-images.githubusercontent.com/13822661/172457385-9c9b69e4-d7c1-4e32-b406-07d3dbfa0a75.png">

In the above loop, inlining `self.decode` causes a graph break and the remaining 3 lines form a Fx Graph (basically 2 squeeze ops). However, there is a guard on `alignments` array, which is appended on each iteration of the while loop.

* VisonMaskRCNN - This is coming from this piece of code
<img width="499" alt="image" src="https://user-images.githubusercontent.com/13822661/172458930-fbd0fc36-7532-4bbc-8b2f-053a58217b2f.png">

The line 406 results in an integer `w`. cc @yanboliang as he is working on removing specialization in integers (though, this  one might be trickly as we are reading from tensor `box` to get `w`).

cc @jansel @wconstab let me know what you think.

**Comment by anijain2305** [comment]
@voznesenskym Agree that the error message can do with improvements like you mentioned. It was little odd to me as well.

**Comment by jansel** [comment]
Hrm, maybe this is a case we could detect earlier and not compile.  We should avoid generating guards we know will fail right away.

**Comment by wconstab** [comment]
> So we actually want to call this on the first, I think, not the last.

I am probably misunderstanding things, but my intention was to capture the guard failure reasons that triggered recompiles and then print those reasons all at the same time when we hit the cache limit.

So, (1) i was thinking that the `if last -> return` logic would mean that in a case where there are already 2 compiled versions of this function and we fail the guards for the first but maybe pass them for the second, we would not log anything.  Hence i thought we only want to store statistics on guards failing when 'last=True'

Regarding the actual log message, i agree it is crappy that it includes the same condition over and over, but i did not know if coalescing them would be reliable.

**Comment by wconstab** [comment]
>  guard on alignments array, which is appended

what are our options for this case?  If we read from the array it's hard to avoid guarding, but if we only append to it can we safely omit the guard?  I think it would also be just as good if we graph break before the append and still only compile the 2 ops above it.  But either way we'd have to detect that it's this special 'append only' case i think

**Comment by voznesenskym** [comment]
> > So we actually want to call this on the first, I think, not the last.
> 
> I am probably misunderstanding things, but my intention was to capture the guard failure reasons that triggered recompiles and then print those reasons all at the same time when we hit the cache limit.
> 
> So, (1) i was thinking that the `if last -> return` logic would mean that in a case where there are already 2 compiled versions of this function and we fail the guards for the first but maybe pass them for the second, we would not log anything. Hence i thought we only want to store statistics on guards failing when 'last=True'
> 
> Regarding the actual log message, i agree it is crappy that it includes the same condition over and over, but i did not know if coalescing them would be reliable.

It's okay, I think for the majority of recompilations your logic is spot on - logging the entire set of failures should be something we can config. However, for some cases, it's useful to see the entire chain we walked. Let me open a PR rq to address that and see what you think :)

**Comment by voznesenskym** [comment]
> > guard on alignments array, which is appended
> 
> what are our options for this case? If we read from the array it's hard to avoid guarding, but if we only append to it can we safely omit the guard? I think it would also be just as good if we graph break before the append and still only compile the 2 ops above it. But either way we'd have to detect that it's this special 'append only' case i think

Why is appending only safe? I can see cases where appending should invalidate the graph as it will change (hypothetical logic of `if len (accumlated_thing) > x do blah()`. 

And in the case of the VisonMaskRCNN  model, thats not an array at all! That's just a value (w) that's read from a tensor. It seems like to @jansel point we may need to do something more clever around introspecting the context to understand that "hey, this value we are about to guard on? its pretty likely to change on any subsequent invocations, so let's not produce any guards".

**Comment by anijain2305** [comment]
tacotron2 is temporarily fixed. Smaller examples are now tracked in - https://github.com/pytorch/torchdynamo/issues/1940
