### ISSUE TITLE
Triaging PyTorch Tests - WIP

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#336]
Master issue to triage the Pytorch tests. Will be updating this one over the next few weeks.

## test/ao/sparsity 

Failure categories - 1
####  test/ao/sparsity/test_pruner.py::TestBasePruner::test_step_conv2d
* Sparsification-related changes to the module are not tracked in Dynamo.

## test/autograd

Failure categories - 1
#### test/autograd/test_functional.py::TestAutogradFunctional::test_hessian_vectorize_raises_no_warnings_base_tensor
* Command to repro (2 tests have to be run together to repro this)
~~~
pytest -v -s test/autograd/test_functional.py::TestAutogradFunctional::test_hessian_vectorize_correctness_unrelated_outputs_logging_tensor test/autograd/test_functional.py::TestAutogradFunctional::test_hessian_vectorize_raises_no_warnings_base_tensor
~~~
* Might be harmless or might be something to do with `torch.vmap`

## test/fx

Total failures- 29
Failures categories - 3 or 4

Repro - Most failures can be repro'd at https://github.com/pytorch/torchdynamo/issues/343

### test/fx/test_dce_pass.py::TestDCE::test_keep_module_with_side_effects
* `RuntimeError: __class__ not set defining 'TestModule' as <class 'test_dce_pass.TestModule'>. Was __classcell__ propagated to type.__new__?` error. Many tests fail with this error.

#### test/fx/test_gradual_type.py::TypeCheckerTest::test_symbolic_add_with_broadcast_2
* `NotImplementedError: Module [M] is missing the required "forward" function`

## test/jit
Total failures - 7
Failures categories - Most likely 2

#### test/jit/test_tracer.py::TestTracer::test_trace_export_fns
* Captured in this repro - https://github.com/pytorch/torchdynamo/issues/376

#### test/jit/test_class_type.py::TestClassType::test_imported_classes
* Fails with import errors. Seems like weird test and we can safely skip this one.

## test/package
Total failures - 5
Categories - 1

#### test/package/test_misc.py::TestMisc::test_inspect_class
* For some reason, TorchDynamo is not able to find the correct packages. Quick hack might be to just to skip torch.Package. But, we need to dig deeper.

#### test/quantization/core/test_quantized_module.py::TestStaticQuantizedModule::test_conv2d_api
* Related to https://github.com/pytorch/torchdynamo/issues/376

## test/distributions

Num failures - 35
Category - 1
#### test/distributions/test_distributions.py::TestDistributionShapes::test_one_hot_categorical_shape
* This is not a Dynamo bug. If we comment this [line](https://github.com/pytorch/torchdynamo/blob/main/torchdynamo/eval_frame.py#L282)  - `torch.distributions.Distribution.set_default_validate_args(False)`, all the tests pass. So, we should figure out why we need this line. Jason told that he found a lot of annoying issues when he was dealing with Torchbench early on, and therefore added this line. We should revisit. cc @voznesenskym as he was interested in looking at the `test_distributions.py`

**Comment by ezyang** [comment]
Hey @anijain2305 now that dynamo is being installed in PT CI we can start running dynamo on the tests where they are passing. Do you need help turning this on?

**Comment by anijain2305** [comment]
@ezyang Yes, I would need some help here. And maybe for first few iterations, we could just run all of PyTorch tests with TorchDynamo. It would be really helpful if we could track the success rate (hopefully improving :-) ) over time.

**Comment by anijain2305** [comment]
This work is also in early maintenance mode. Closing this. Will reopen for new issues.
