### ISSUE TITLE
TorchDynamo bug - Class creation not handled/propagated correctly

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#343]
Many Pytorch Fx tests fail because of the issues in the following repro 

EDIT - The repro has been edited to be shorter
~~~
import torch
import torch.fx
import torchdynamo
from torch.fx.tensor_type import TensorType, Dyn


@torchdynamo.skip
def fn():
    class M:
        def add(self, x, y=torch.randn(4)):
            return torch.add(x, y)

    mod = M()

    a = torch.zeros(4)
    b = torch.ones(4)

    return mod.add(a, b)

ref = fn()
print("EAGER DONE")

torchdynamo.config.debug = True
torchdynamo.config.trace = True
with torchdynamo.optimize("eager"):
    res = fn()
assert torch.allclose(ref, res)

~~~

cc @voznesenskym @mlazos @jansel

**Comment by jansel** [comment]
Is this just an FX issue or is there some FX+Dynamo interaction?  Do we break the graph on the call to symbolic_trace?

**Comment by voznesenskym** [comment]
Setting FX aside, I think we just don't treat default args properly?

```
import torch
import torch.fx
import torchdynamo

def fn():
    class M(torch.nn.Module):
        def forward(self, x: torch.tensor([1, 2]), y: torch.tensor([0, 2])):
            return torch.add(x, y)

    mod = M()

    a = torch.zeros(4)
    b = torch.ones(4)

    return mod(a, b)

ref = fn()

torchdynamo.config.debug = True
torchdynamo.config.trace = True
with torchdynamo.optimize("eager"):
    res = fn()
assert torch.allclose(ref, res)

```

**Comment by voznesenskym** [comment]
Fwiw - pulling the class def out of the func fixes it.

```
import torch
import torch.fx
import torchdynamo
from torch.fx.tensor_type import TensorType, Dyn


class M(torch.nn.Module):
    # Commenting this is fine
    def __init__(self):
        super().__init__()

    def forward(self, x: TensorType((1, 2)), y: TensorType((Dyn, 2))):
        return torch.add(x, y)

def fn():
    mod = M()

    a = torch.zeros(4)
    b = torch.ones(4)

    return mod(a, b)

ref = fn()

torchdynamo.config.debug = True
torchdynamo.config.trace = True
with torchdynamo.optimize("eager"):
    res = fn()
assert torch.allclose(ref, res)

```

Works just fine.


I think what's actually happening here is not so much around typing / type annotations as it is about dynamo handling definitions within an optimize well. Let me look into this further.

**Comment by voznesenskym** [comment]
Small update, I think we are mangling some naming somewhere.

With dynamo, if we log self's class in pytorch, we get:

 `<class '__main__.M'>`
 
 But without dynamo its:
 
`<class '__main__.fn.<locals>.M'>`

Which made me realize that we are probably doing something funky w/ locals. Tracing up, I saw we had no locals, and looking a step further, no guards.

This PR fixes both my repro, and yours: https://github.com/pytorch/torchdynamo/pull/346

**Comment by jansel** [comment]
I feel like the correct behavior for that is either a graph containing:
```
    a = torch.zeros(4)
    b = torch.ones(4)
    return torch.add(a,b)
```
(With the class creation optimized away.)

Or calling `unimplemented()` on the class definition.

No guards seems spurious.

**Comment by voznesenskym** [comment]
That makes sense. I think my PR is far too heavy handed - it uses no guards
as a poor proxy for this.

**Comment by anijain2305** [comment]
I updated the repro to be shorter

~~~
import torch
import torch.fx
import torchdynamo
from torch.fx.tensor_type import TensorType, Dyn


@torchdynamo.skip
def fn():
    class M:
        def add(self, x, y=torch.randn(4)):
            return torch.add(x, y)

    mod = M()

    a = torch.zeros(4)
    b = torch.ones(4)

    return mod.add(a, b)

ref = fn()
print("EAGER DONE")

torchdynamo.config.debug = True
torchdynamo.config.trace = True
with torchdynamo.optimize("eager"):
    res = fn()
assert torch.allclose(ref, res)

~~~


Error

~~~
AttributeError: 'M' object has no attribute 'add'
~~~


Note the `fn` is annotated with `skip` decorator.

The only frame going through TorchDynamo is `class` creation frame

~~~

ORIGINAL BYTECODE M /scratch/anijain/torchdynamo/failures/test_module.py 9
  9           0 LOAD_NAME                0 (__name__)
              2 STORE_NAME               1 (__module__)
              4 LOAD_CONST               0 ('fn.<locals>.M')
              6 STORE_NAME               2 (__qualname__)

 10           8 LOAD_NAME                3 (torch)
             10 LOAD_METHOD              4 (randn)
             12 LOAD_CONST               1 (4)
             14 CALL_METHOD              1
             16 BUILD_TUPLE              1
             18 LOAD_CONST               2 (<code object add at 0x7fc618e352f0, file "/scratch/anijain/torchdynamo/failures/test_module.py", line 10>)
             20 LOAD_CONST               3 ('fn.<locals>.M.add')
             22 MAKE_FUNCTION            1 (defaults)
             24 STORE_NAME               5 (add)
             26 LOAD_CONST               4 (None)
             28 RETURN_VALUE

MODIFIED BYTECODE
  9           0 LOAD_NAME                0 (__name__)
              2 STORE_NAME               1 (__module__)
              4 LOAD_CONST               0 ('fn.<locals>.M')
              6 STORE_NAME               2 (__qualname__)

 10           8 LOAD_NAME                3 (torch)
             10 LOAD_ATTR                4 (randn)
             12 LOAD_CONST               1 (4)
             14 CALL_FUNCTION            1
             16 BUILD_TUPLE              1
             18 LOAD_CONST               2 (<code object add at 0x7fc618e352f0, file "/scratch/anijain/torchdynamo/failures/test_module.py", line 10>)
             20 LOAD_CONST               3 ('fn.<locals>.M.add')
             22 MAKE_FUNCTION            1 (defaults)
             24 STORE_NAME               5 (add)
             26 LOAD_CONST               4 (None)
             28 RETURN_VALUE


GUARDS:
~~~

Even though the code looks exactly same here, somehow Python is not updating the namespace of the class objects properly here. If I force graph break or anything that results in `WONT CONVERT`, the test passes.

I read this - http://www.matusiak.eu/numerodix/blog/2013/8/11/python-bytecode-classes/. But still don't understand why there would be an issue here.

We could somehow identify if the frame is due to class creation and skip Dynamo on that, or do something like @voznesenskym has done. But, there is still fundamental concept that we are missing here.

**Comment by anijain2305** [comment]
https://github.com/pytorch/torchdynamo/pull/351 passes this test. However, as mentioned earlier, this root cause is still unclear. My PR raises the `unimplemented` all the way to `convert_frame` s.t. Dynamo gives up on the frame. Since class creation always start with `LOAD_NAME`, it causes Dynamo to give up on the frame in this test.

**Comment by ezyang** [comment]
This is a problem with locals right? It's an underlying FX problem where locals don't get compiled correctly. FX will guess that the module and the name together give a valid identifier to reference the function, but if it's a local it won't work.

Relevant logic is

```
def _get_qualified_name(func: Callable[..., Any]) -> str:
    # things like getattr just appear in builtins
    if getattr(builtins, func.__name__, None) is func:
        return func.__name__
    name = func.__name__
    module = _find_module_of_method(func)
    module = module.replace('torch._ops', 'torch.ops')  # WAR for bug in how torch.ops assigns module
    return f'{module}.{name}'
```

in torch.fx.node

dynamo is making things worse by actually putting these locals in the graph; it really shouldn't but it gets a bit too eager when the function lives in torch namespace

**Comment by anijain2305** [comment]
Unable to repro now. Closing this.
