### ISSUE TITLE
Improve line number tracking and exceptions/error messages

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#36]
Currently, TorchDynamo does not preserve line numbers in generated code in most cases, though it does in a few cases and in the case where the error happens at compile time.  It supports [generating line numbers](https://github.com/facebookresearch/torchdynamo/blob/052b8dab6df5f027a34edb00dee73870433883d5/torchdynamo/bytecode_transformation.py#L58) in output code, so fixing this is just a matter of populating the line numbers on the Instruction() objects.

We should improve this and carry line numbers through our transformations.  We should also test TorchDynamo on deliberately buggy programs and make sure it produces good error messages.

**Comment by jansel** [comment]
A related thing to this would be putting line numbers on the nodes in the generated FX graph.

That would be double, but require threading them through multiple layers of the stack:
- Copy the value of `InstructionTranslator().lineno` to FX nodes as they are added to the graph.  Perhaps this can be done in TensorVariable.create.
- Make [normalize_ir](https://github.com/facebookresearch/torchdynamo/blob/86a2bea62cebedb51d5a1f2230e7817ff2f786fb/torchdynamo/optimizations/normalize.py#L421) preserve line numbers
- Copy line numbers from the [interpreted graph](https://github.com/facebookresearch/torchdynamo/blob/86a2bea62cebedb51d5a1f2230e7817ff2f786fb/torchdynamo/optimizations/python_key.py#L77) to the generated graph in python key tracing.

Once these are done, downstream compilers could use those line numbers.

**Comment by mlazos** [comment]
closing, #891 + #1224 + #754 + #678 together add this feature
