### ISSUE TITLE
Dynamo should maintain and reconstruct stack trace of bytecode it is symbolically interpreting

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#368]
This will make it possible to directly say what the user python code that caused an error was without requiring trace to be turned on

**Comment by jansel** [comment]
If you hit `unsupported()` it already does this, it builds the stack here:
https://github.com/pytorch/torchdynamo/blob/85561d0f4f656af71e0f3fa9f56af61466ac8f7c/torchdynamo/symbolic_convert.py#L288

Then it prints out the stack trace using `traceback` here:
https://github.com/pytorch/torchdynamo/blob/85561d0f4f656af71e0f3fa9f56af61466ac8f7c/torchdynamo/exc.py#L36

We should extend this to other types of exceptions though.

**Comment by mlazos** [comment]
Update: #793 adds a stack trace
#36 is needed to make the line numbers of dynamo-compiled functions accurate

**Comment by mlazos** [comment]
Closed with the stack trace + line numbers above
