### ISSUE TITLE
[Torchinductor] TritonScheduling codegen pop_group() may miss opportunity for adding pointwise with compatible dimensions to reduction

### ISSUE THREAD

**Issue by pyjhzwh** [pytorch/torchdynamo#399]
https://github.com/pytorch/torchdynamo/blob/c30f2364c6ac2767d92da8ef1408ec3b6d7c7630/torchinductor/codegen/triton.py#L617-L620
Should it be 
```
pop_group( 
     (group, reduction_group, sympy.Integer(1))
```
? Because for pointwise operator, for example pointwise add for 2d tensor, the group is (s0, s0, 1) rather than (s0 * s0, 1). So the other reduction operator may miss the opportunity to fuse them.

**Comment by jansel** [comment]
https://github.com/pytorch/torchdynamo/blob/c30f2364c6ac2767d92da8ef1408ec3b6d7c7630/torchinductor/codegen/triton.py#L576

For the Triton backend, we group by `product()`.  So the group for a 2D pointwise will be `(s0 * s0, 1)`.  4D iteration will become: `(s0*s1*s2*s4, 1)`.

The only way to get `len(groups)>2` is if tiling kicks in, which will typically be for transpose kernels.
https://github.com/pytorch/torchdynamo/blob/c30f2364c6ac2767d92da8ef1408ec3b6d7c7630/torchinductor/ir.py#L1262

**Comment by pyjhzwh** [comment]
`pytest tests/test_torchinductor.py -vsk test_sum3_cuda`
The generated code is 
```

from ctypes import c_void_p, c_long
import torch
from torch import empty_strided, as_strided
from torchinductor.codecache import CppCodeCache, TritonCodeCache
from torchinductor.codecache import grid, pointwise_heuristics, reduction_heuristics

try:
    import triton
    import triton.language as tl
except ImportError:
    pass

aten = torch.ops.aten

@pointwise_heuristics(size_hints=[16, 16])
@triton.jit
def kernel0(in_ptr0, in_ptr1, out_ptr0, ks0, xnumel, ynumel, XBLOCK : tl.constexpr, YBLOCK : tl.constexpr):
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK, 1])
    xmask = xindex < xnumel
    yoffset = tl.program_id(1) * YBLOCK
    yindex = yoffset + tl.reshape(tl.arange(0, YBLOCK), [1, YBLOCK])
    ymask = yindex < ynumel
    x0 = xindex
    y1 = yindex
    tmp0 = tl.load(in_ptr0 + ks0*x0 + y1, xmask & ymask).to(tl.float32)
    tmp1 = tl.load(in_ptr1 + y1, ymask).to(tl.float32)
    tmp2 = tmp0 + tmp1
    tl.store(out_ptr0 + ks0*x0 + y1, tmp2, xmask & ymask)

@reduction_heuristics(size_hints=[16, 16])
@triton.jit
def kernel1(in_ptr0, in_ptr1, out_ptr0, out_ptr1, ks0, xnumel, rnumel, XBLOCK : tl.constexpr, RBLOCK : tl.constexpr):
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK, 1])
    xmask = xindex < xnumel
    roffset = 0
    rindex = roffset + tl.reshape(tl.arange(0, RBLOCK), [1, RBLOCK])
    rmask = rindex < rnumel
    x0 = xindex
    r1 = rindex
    tmp0 = tl.load(in_ptr0 + ks0*x0 + r1, xmask & rmask).to(tl.float32)
    tmp4 = tl.load(in_ptr1 + x0, xmask).to(tl.float32)
    tmp1 = 0
    tmp2 = tl.where(xmask & rmask, tmp0, tmp1)
    tmp3 = tl.reshape(tl.sum(tmp2, 1), [XBLOCK, 1])
    tmp5 = 10
    tmp6 = tmp4 + tmp5
    tl.store(out_ptr0 + x0, tmp3, xmask)
    tl.store(out_ptr1 + x0, tmp6, xmask)


def call(arg0, arg1):
    arg0_size = arg0.size()
    s0 = arg0_size[0]
    buf0 = empty_strided((s0, s0), (s0, 1), device='cuda', dtype=torch.float16)
    kernel0[grid(s0, s0)](arg0, arg1, buf0, s0, s0, s0)
    buf1 = empty_strided((s0, ), (1, ), device='cuda', dtype=torch.float16)
    buf2 = empty_strided((s0, ), (1, ), device='cuda', dtype=torch.float16)
    kernel1[grid(s0)](buf0, arg1, buf1, buf2, s0, s0, s0)
    return (buf0, buf1, buf2, )


if __name__ == "__main__":
    from torchdynamo.testing import rand_strided
    from torchinductor.microbench import print_performance
    arg0 = rand_strided((10, 10), (10, 1), device='cuda', dtype=torch.float16)
    arg1 = rand_strided((1, 10), (10, 1), device='cuda', dtype=torch.float16)
    print_performance(lambda: call(arg0, arg1))
```
So kernel0 and kernel 1 did not fuse together

**Comment by jansel** [comment]
https://github.com/pytorch/torchdynamo/pull/314 disables tiling, so if you pull you should see something different.

You are correct that it would be valid to merge a `(s0, s1, 1)` pointwise into a `(s0, s1)` reduction.  If you want, you could try making a PR to enable that.

**Comment by pyjhzwh** [comment]
My bad. I did not pull the lasted upstream

**Comment by pyjhzwh** [comment]
In this case, is this redundant? since len(group)==2
https://github.com/pytorch/torchdynamo/blob/c30f2364c6ac2767d92da8ef1408ec3b6d7c7630/torchinductor/codegen/triton.py#L640

**Comment by pyjhzwh** [comment]
And in test_sum3_cuda of test_torchinductor.py
```
def fn(a, b):
            r1 = a + b
            r2 = r1.sum(-1)
            r3 = torch.squeeze(b) + 10
            return (r1, r2, r3)
```
Do we expect these 3 operators fused or not together? Currently the pointwise add (a+b) run first, making the following sum reduction (r1.sum(-1)) failed to fused with a+b. Should we give reduction larger priority to pointwise operators?

**Comment by jansel** [comment]
@pyjhzwh can you try in [my branch](https://github.com/jansel/torchdynamo/tree/inductor) and see it is fixed?

I suspect this will be fixed if you merge #401, #402, and possibly #404.

**Comment by pyjhzwh** [comment]
test_sum3_cuda is fixed, code-gen only one kernel now. But for test_sum4_cuda, it generates 5 kernels, seems to miss the fusing opportunities of point-wise add and sum reduction. I have not looked into this example, though.

**Comment by pyjhzwh** [comment]
Solved by recent PRs
