### ISSUE TITLE
Guards evaluated in the wrong order if inner function generates shape guard

### ISSUE THREAD

**Issue by mlazos** [pytorch/torchdynamo#412]
Below code:

`inner_fn` causes a shape guard to be generated which is propagated to `fn`. 

On the first run, `fn` has a tensor match guard and a shape guard, but currently tensor match guards are evaluated last. On the next call, calling `.shape` on an int causes guard evaluation to crash.

Code:
```import torch

import torchdynamo
import torchdynamo.testing

torchdynamo.config.trace = True
torchdynamo.config.debug = True


class TestModule(torch.nn.Module):
    def inner_fn(self, left, right):
        return tuple(left) == tuple(right)

    def fn(self, tensor):
        if type(tensor) is int:
            return False

        torch.add(tensor, tensor)
        return self.inner_fn(tensor.shape, (1, 2, 3))


def test_guard_break():
    m = TestModule()
    with torchdynamo.optimize("eager"):
        m.fn(torch.ones(5, 5))
        m.fn(-3)


test_guard_break()```


Terminal output:
GUARDS:
 - local 'self' NN_MODULE
 - local 'tensor' TENSOR_MATCH
 - local 'tensor.shape' LIST_LENGTH
 - local 'type(tensor)' FUNCTION_MATCH
 - global 'int' BUILTIN_MATCH
 - global 'type' BUILTIN_MATCH
 - global 'torch' FUNCTION_MATCH
 - global 'tuple' BUILTIN_MATCH

skipping _fn /scratch/mlazos/torchdynamo/torchdynamo/eval_frame.py
skipping nothing /scratch/mlazos/torchdynamo/torchdynamo/eval_frame.py
skipping __exit__ /scratch/mlazos/py39/lib/python3.9/contextlib.py
Traceback (most recent call last):
  File "<string>", line 3, in <lambda>
AttributeError: 'int' object has no attribute 'shape'
ERROR RUNNING GUARDS fn /scratch/mlazos/torchdynamo/../test/script.py:14
  ___guarded_code.valid and
  ___check_obj_id(self, 140015741341648) and
  self.training == True and
  ___check_type_id(tensor.shape, 140015596845312) and
  len(tensor.shape) == 2 and
  ___check_type_id(tensor, 94614246866912) and
  ___check_tensors(tensor)
NULL ERROR: torchdynamo/_eval_frame.c:215
zsh: abort (core dumped)  python ../test/script.py

**Comment by voznesenskym** [comment]
Just to clarify - Are you saying `___check_type_id(tensor, 94614246866912)` should be before the other checks?

**Comment by mlazos** [comment]
Yes exactly, but you can't put a blanket "check types before others" ordering because the specific test I was looking at the instance to be checked was part of a list, so you also need to check the length of the list before running the check. My solution was to just add a type guard whenever accessing the shape, and (I think) that was enough to guarantee that it is run before the other shape guards. Still checking that though

**Comment by voznesenskym** [comment]
Not 100% sure, but I think, well, that tensor `___check_type_id` check comes from: `TENSOR_MATCH`. 

So, I *wonder* if the .shape comes through as a `ShapeVariable`, would this potentially arise for any property/ any specialization of tensor (`def specialize(value: torch.Tensor):` on TensorVariable`)? 

If so, maybe we should ensure that before we write a guard for a tensor property, we always write that property's type_id check in?

**Comment by anijain2305** [comment]
I think @voznesenskym is right. It might be because of that `ShapeVariable` which I recently introduced here - https://github.com/pytorch/torchdynamo/pull/387. 

Can you try reverting that PR and see if it passes? I might have overlooked the guards here.

**Comment by mlazos** [comment]
Yes I agree, I haven't been able to get it to happen with other attributes, but only tried for a little a while, but the fix is easy enough in my PR, I can move the type guard so that it adds it for any attribute.
