### ISSUE TITLE
tacotron2 and pytorch_struct not giving any output

### ISSUE THREAD

**Issue by shingjan** [pytorch/torchdynamo#416]
My repro:
```
./torchbench.py --only "tacotron2"
./torchbench.py --only "pytorch_struct"
```

All dependencies are installed as tacotron2 requires librosa and soundfile additionally. There is no standard out/error for the above two models with both `eager` and `--speedup-ts`. Is this expected?

**Comment by jansel** [comment]
`tacotron2` is GPU-only you may need to add `-d cuda`.  You are likely hitting this line in torchbench:
https://github.com/pytorch/benchmark/blob/92c20c6aeea7a5c9301c9ec1c3d22178f6533cf7/torchbenchmark/models/tacotron2/__init__.py#L27

What exact command are you running for pytorch_struct?  It seems to work for me.
```
(torchdynamo) empire:~/torchdynamo$ ./torchbench.py --only "pytorch_struct"
cpu  eval  pytorch_struct                     1/  1 +0 frames   1s  1 graphs  1 graph calls   42/  42 = 100% ops 100% time
(torchdynamo) empire:~/torchdynamo$ ./torchbench.py --only "pytorch_struct" --backend=eager
cpu  eval  pytorch_struct                     1.000x SAME
(torchdynamo) empire:~/torchdynamo$ ./torchbench.py --only "pytorch_struct" --speedup-ts
cpu  eval  pytorch_struct                     ERROR ERROR
````

No output usually means you are hitting this line:
https://github.com/pytorch/torchdynamo/blob/17af4807ba16c72dc25595280d583c03eb539a2f/torchbench.py#L1239

Try adding:
```
raise
```
To re-raise the exception or remove the try/except block.  That might make the issues more clear.

**Comment by shingjan** [comment]
Thanks for the prompt reply @jansel! I tried raising the error and got the following:
```
NotImplementedError: Test eval is not implemented.
``` 

This actually seems to align with what I saw on the torchbenchmark side while testing. Do you have a fix for this on your torchbench branch?

**Comment by jansel** [comment]
Perhaps it is fixed in [my branch](https://github.com/jansel/benchmark/) by the changes to `torchbenchmark/util/model.py`.

**Comment by xuzhao9** [comment]
`pytorch_struct` doesn't have eval test because it is a self-supervised learning model.

**Comment by shingjan** [comment]
@xuzhao9 Thanks for the pointer! @jansel Is that the case that [pplbench_beanmachine](https://github.com/pytorch/benchmark/issues/898) is expected to be skipped in benchmark as well? Just wonder if there is any update on that thread.

**Comment by xuzhao9** [comment]
> @xuzhao9 Thanks for the pointer! @jansel Is that the case that [pplbench_beanmachine](https://github.com/pytorch/benchmark/issues/898) is expected to be skipped in benchmark as well? Just wonder if there is any update on that thread.

@shingjan pplbench_beanmachine has been removed from torchbench because of low quality (https://github.com/pytorch/benchmark/pull/968)
