### ISSUE TITLE
Support distributed training

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#43]
This is a placeholer task to make distributed training work with TorchDynamo + AOT Autograd.  The main work seems to be making sure the relevant ops can be traced with AOT Autograd and are properly added to the FX graph by TorchDynamo.

I expect most of the issues will be at the AOT Autograd level, because TorchDynamo treats most torch.* ops as black box.  We should test and verify this though.

@alanwaketan can fill in details.

**Comment by Jack47** [comment]
any updates on this? I'm wondering DDP is supported yet

**Comment by jansel** [comment]
@wconstab has this prototype: https://github.com/pytorch/torchdynamo/pull/628

So it should be possible to get things working.  Though we still have work to do to make the experience more smooth and performant.

**Comment by carmocca** [comment]
Does the limitation only apply to training? Or is distributed inference supported?

**Comment by wconstab** [comment]
DDP should be functional with  dynamo today.  What we're working on is profiling the performance and optimizing it as needed.  The concern is that DDP's optimization which overlaps allreduce communication with backward computation is undone by dynamo+aot-autograd fusing the whole graph into one compiled forward and one compiled backward function.  Depending on your cluster size, model and interconnect bandwidth, you may still see performance gains by using dynamo+ddp over eager+ddp.

**Comment by anijain2305** [comment]
Closing this as there is a separate workstream for PT2 Distributed.
