### ISSUE TITLE
Graph differences from imports 

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/torchdynamo#440]
Running tests with different pytest commands results in different graphs, different bytecode, etc.

I suspect monkeypatching.

Details: https://www.internalfb.com/intern/bigdiff/?original=P511019172&modified=P511019243&language=python

My apologies to the non Meta folks reading this, I know of no good free online paste-diff tool.

**Comment by voznesenskym** [comment]
The "skipping cross_entropy /data/home/voz/.local/lib/python3.8/site-packages/functorch/_src/monkey_patching.py" is suspicious, its certainly causing cross_entropy to not be in the graph

**Comment by jansel** [comment]
Ah interesting.  cc @Chillee @zou3519

**Comment by voznesenskym** [comment]
> Oh yeah. functorch monkeypatches a couple of functions. We can plan to delete all the monkeypatches by 1.13; the cross_entropy one should be deletable right now (but I'll go and check that)

That might fix it, but that's just a symptom of a bigger underlying issue, which is that imports and inclusions change the graph that is produced in unexpected ways.

**Comment by voznesenskym** [comment]
I believe https://github.com/pytorch/torchdynamo/pull/444/files alleviates current test weirdness, but it's by no means a good long term solution.

**Comment by jansel** [comment]
IMO functorch should not do monkeypatching on import.  People don't expect `import X` to have side effects.  Doing it on first call seems cleaner.

**Comment by zou3519** [comment]
> IMO functorch should not do monkeypatching on import. People don't expect `import X` to have side effects. Doing it on first call seems cleaner.

I agree. functorch (and other libraries in general) shouldn't be doing monkeypatching at all. The monkeypatching is tech debt left over from our early prototype days

**Comment by zou3519** [comment]
We've deleted the cross_entropy monkeypatch from functorch (https://github.com/pytorch/functorch/pull/901). There are two more (`_tensor_str` and Tensor.backward) that are a bit tricker to delete (we need to upstream some logic into pytorch/pytorch). We can plan to fix them for 1.13, but if those are also blocking you we can prioritize them.

**Comment by zou3519** [comment]
Fwiw functorch has removed all of its monkey patching, so this issue can probably be closed
