### ISSUE TITLE
TypeError: <lambda>() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#481]
Steps to reproduce:
1. checkout https://github.com/ezyang/torchdynamo/tree/weirdlambda
2. run `python tests/test_recompile_ux.py -k test_drop_cache_on_skip` 

I get this weird error:

```
Exception ignored in: <function Tracker.add.<locals>.<lambda> at 0x12d01dca0>
Traceback (most recent call last):
  File "tests/test_recompile_ux.py", line 52, in test_drop_cache_on_skip
    model(x, i)
TypeError: <lambda>() takes 0 positional arguments but 1 was given
```

It would be good to figure out why the TypeError makes no sense

**Comment by voznesenskym** [comment]
I can take a look at this.

**Comment by ezyang** [comment]
This is a problem in my code! Sorry about false alarm
