### ISSUE TITLE
test_torchinductor failed for RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by pyjhzwh** [pytorch/torchdynamo#495]
`pytest tests/test_torchinductor.py::GpuTests::test_alexnet_prefix_cuda`
It will throw `RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'`

If I set torchdynamo.config.fake_tensor_propagation as False. The error is gone.

python 3.9.12
pytorch 1.13.0
cuda 11.6

**Comment by eellison** [comment]
Should be fixed with https://github.com/pytorch/pytorch/pull/80193. Upgrade to more recent pytorch.
