### ISSUE TITLE
FakeTensor creation doesn't copy grad attribute

### ISSUE THREAD

**Issue by mlazos** [pytorch/torchdynamo#497]
When wrapping a tensor, the grad attribute isn't copied. This can result in some CONSTANT_MATCH guards getting created for tensor variables because the type of the `grad` attribute will be `NoneType` for the FakeTensor, but during guard compilation the type of the `grad` attribute will be `Tensor`. The assertion here: https://github.com/pytorch/torchdynamo/blob/b3c3b9e4d99fad06ef8ec1a90b5321f502c9d53e/torchdynamo/guards.py#:~:text=.name)-,assert%20istype(,)%2C,-)%2C%20type(
fails as a result.

**Comment by eellison** [comment]
Thanks for issue! Should be closed with https://github.com/pytorch/pytorch/pull/82593. If there is a repro or something we can double check.

**Comment by mlazos** [comment]
It works! I have a repro I was actually working on last night

**Comment by eellison** [comment]
Great!
