### ISSUE TITLE
torchbench not running, bug with -dcuda --inductor

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/torchdynamo#503]
```
runner.non_deterministic_models.add("pyhpc_equation_of_state")
AttributeError: 'dict' object has no attribute 'add'
```
This should be `.update("foo", "pyhpc_equation_of_state"). 

I would fix it myself, but I am not sure what the key should be.

**Comment by jansel** [comment]
I believe this was fixed in https://github.com/pytorch/torchdynamo/pull/475/files#diff-e276483f1762edf99982ff35ffe366276f6f00cc6147a1627e544a68e87e22bfR103
