### ISSUE TITLE
torchdynamo.optimize context manager is misleading

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#516]
As we only interpose when a new frame is begun, the directly inlined code inside the context manager will never get dynamo compiled. This can be quite confusing for users. We should encourage use of the decorator or a higher order function that takes a function as argument to be called.

**Comment by voznesenskym** [comment]
For reference: `export`, a new experimental feature, takes the function as an argument to be called.

**Comment by jansel** [comment]
Yeah I agree, switching to the decorator syntax might be better.

**Comment by xuzhao9** [comment]
Should we update the usage of context manager in `torchbench.py` then? E.g., https://github.com/pytorch/torchdynamo/blob/main/benchmarks/common.py#L317 and https://github.com/pytorch/torchdynamo/blob/main/benchmarks/common.py#L234

**Comment by anijain2305** [comment]
Task 70-80% done.

**Comment by wconstab** [comment]
@anijain2305 can you sync up with @xuzhao9 about the right way to update torchbench to align with your changes here?

**Comment by anijain2305** [comment]
Yes, will do.

**Comment by anijain2305** [comment]
Context manager is removed from the repo. Final PR adding a warning message is here - https://github.com/pytorch/torchdynamo/pull/1112

**Comment by anijain2305** [comment]
Task done - https://github.com/pytorch/torchdynamo/pull/1250
