### ISSUE TITLE
2 Torchbench models failed when unspec int/float is default 

### ISSUE THREAD

**Issue by yanboliang** [pytorch/torchdynamo#538]
I run torchbench with the [unspec int/float features](https://github.com/pytorch/torchdynamo/pull/520) and found some bugs. I'm fixing several easy bugs at https://github.com/pytorch/torchdynamo/pull/539, but there are still two models doesn't work well.

* Super_SloMo 
```
SyntaxError: duplicate argument 'self_trainFlowBackWarp_W' in function definition
```

* vision_maskrcnn

Failed the correctness check

**Comment by jansel** [comment]
@yanboliang we should disable #520 until these bugs are fixed.  TorchBench not working will prevent us from running experiments.

**Comment by anijain2305** [comment]
@yanboliang Can we close this?
