### ISSUE TITLE
accuracy issue with resnet50_quantized_qat

### ISSUE THREAD

**Issue by shingjan** [pytorch/torchdynamo#556]
Hi, I am trying to do some benchmark on one of the models from `torchbench` and it seems that both `onnxrt` and `tvm` will throw the `INCORRECT` flag on model `resnet50_quantized_qat`. My repro is as follows:
```
python3 benchmarks/torchbench.py --only resnet50_quantized_qat --backend=tvm/onnxrt
```

For onnxrt, the cosine similarity is 0.9999999403953552. For TVM it is 0.9992556571960449. I wonder if it is expected and if we should use cosine similarity for quantized models like this one. Thanks!

cc: @jansel @xuzhao9

**Comment by jansel** [comment]
Interesting.  I'm assuming these pass if you add the `--cosine` option (which switches to cosine similarity from `torch.allclose`).

Any idea why onnx/tvm require cosine similarity here?  Are there just a few elements in the output tensor that are further off?  What is the maximum difference?

**Comment by shingjan** [comment]
Yes this model will pass on onnxrt and tvm with `--cosine` flag. The reason why those backends will need cosine similarity instead of `np.allclose` is still obscure to me. I am checking the elements in the output tensor to see if there are a few that could be further off but I wonder under what circumstance that we should be using cosine similarity for a specific model. I am sure `cosine similarity > 0.99` is not mathematically equivalent to `np.allclose` but what your take here would be. Thanks!

**Comment by jansel** [comment]
My take here is that allclose is usually a higher bar than cosine similarity.  Allclose requires every element match, while cosine similarity just requires that most match.

For checking if dynamo is correct (when using the eager backends which should be identical) it makes sense to use that higher bar.

For most optimizing backend compilers, allclose is too high a bar for them to meet.  I'd be fine switching the default to cosine similarity for optimizing backends.

**Comment by anijain2305** [comment]
@jansel I see the same behavior for AOT Autograd with eager backend. It passes with cosine but fails otherwise, even though AOT Autograd has no-op compiler. Do you think there can be some bug hiding in AOT tracing here?

**Comment by jansel** [comment]
Yes, I think that could point to an AOT Autograd bug.  That should not affect tvm/onnx though, because they both use TorchScript (not AOT Autograd).
