### ISSUE TITLE
[inductor] hf_Bart training failure

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#557]
Failing with KeyError: torch.float16. This is an issue of CPU tensors appearing in the graph and then failing to codegen float16 CPU backend code. Not sure where the CPU tensors are coming from.

**Comment by desertfire** [comment]
Not reproducible on the main branch (Didn't try Jason's branch). Instead, we have a result comparison failure,
```
Similarity score=0.7666448354721069
Accuracy failed for key name logits
INCORRECT
0.650x p=0.00
speedup gmean=1.00x mean=1.00x
```

**Comment by jansel** [comment]
Confirmed this seems fixed.
