### ISSUE TITLE
[inductor] Background_Matting training failure

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#559]
Failing with RuntimeError: CUDA: Error- invalid value

**Comment by desertfire** [comment]
The problem can be reproduced with the following simplified Triton code,

```
import torch
from torch import empty_strided
import triton
import triton.language as tl

from torchinductor.triton_ops.autotune import pointwise_heuristics
from torchinductor.triton_ops.autotune import grid

@pointwise_heuristics(size_hints=[256, 262144])
@triton.jit
def kernel2(in_ptr0, out_ptr0, xnumel: tl.constexpr, ynumel: tl.constexpr, XBLOCK : tl.constexpr, YBLOCK : tl.constexpr):
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK, 1])
    xmask = xindex < xnumel
    yoffset = tl.program_id(1) * YBLOCK
    yindex = yoffset + tl.reshape(tl.arange(0, YBLOCK), [1, YBLOCK])
    ymask = yindex < ynumel
    y2 = yindex
    x3 = xindex
    tmp0 = tl.load(in_ptr0 + y2 + (262144*x3), xmask & ymask).to(tl.float32)
    tl.store(out_ptr0 + y2 + (262144*x3), tmp0, xmask & ymask)

def call():
    buf1 = empty_strided((3, 64, 512, 512), (16777216, 262144, 512, 1), device='cuda', dtype=torch.float16)
    buf265 = empty_strided((3, 64, 512, 512), (16777216, 262144, 512, 1), device='cuda', dtype=torch.float16)
    kernel2[grid(192, 262144)](buf1, buf265, 192, 262144)
    return (buf265)

if __name__ == "__main__":
    call()
```

**Comment by jansel** [comment]
Is this just a Triton bug?

If so we should remove the `pointwise_heuristics` wrapper and submit a bug to openai/triton.

**Comment by jansel** [comment]
This kernel just looks like a tiled memcpy.  I am surprised it fails.

**Comment by desertfire** [comment]
It has something to do with autotuning config at this line, https://github.com/pytorch/torchdynamo/blob/62e7e1db7ffe6a142dd924e6776772dbe021297f/torchinductor/triton_ops/autotune.py#L134

I suspect it's because YBLOCK is too large, i.e. (262144/4) = 65536 is reaching some limit in Triton. I don't know if we should call it a Triton bug or because we are using an invalid config for auto-tuning.

**Comment by jansel** [comment]
> YBLOCK

In that case it will be `YBLOCK=4`

**Comment by desertfire** [comment]
> In that case it will be `YBLOCK=4`
I am imagining `YBLOCK` is used by Triton to calculate how many "threads" to launch, and then when `ynumel` is 262144, `ynumel/YBLOCK` somehow becomes "too large"?

**Comment by jansel** [comment]
`ynumel/YBLOCK` will become the grid size, not the thread size.

**Comment by desertfire** [comment]
Filed https://github.com/openai/triton/issues/580

**Comment by desertfire** [comment]
https://github.com/pytorch/torchdynamo/pull/562

**Comment by jansel** [comment]
I made some suggestions on how to debug this via chat.  Feel free to setup some time if you want more help.

**Comment by jansel** [comment]
Is this one fixed now?  It runs out of memory on my local machine.

**Comment by desertfire** [comment]
`./benchmarks/torchbench.py -d cuda   --training  --inductor --use-eval-mode  --float32 -k Background_Matting` passes on A100.
