### ISSUE TITLE
ValueError: tmpX is not defined"fastNLP_Bert","vision_maskrcnn","maml",

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#602]
`./torchbench.py -dcuda --inductor --float16 --no-skip -k maml`

```
ValueError: tmp0 is not defined
...

def kernel9(in_ptr0, in_ptr1, in_ptr2, in_ptr3, out_ptr1, xnumel: tl.constexpr, rnumel: tl.constexpr, XBLOCK : tl.constexpr, RBLOCK : tl.constexpr):
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK, 1])
    xmask = xindex < xnumel
    rbase = tl.reshape(tl.arange(0, RBLOCK), [1, RBLOCK])
    tmp2 = tl.load(in_ptr2 + tmp0, None).to(tl.float32)
                             ^
    _tmp9 = tl.zeros([XBLOCK, RBLOCK], tl.float32) + 0
    for roffset in range(0, rnumel, RBLOCK):
        rindex = roffset + rbase
        rmask = rindex < rnumel
        r0 = rindex
        tmp0 = tl.load(in_ptr0 + r0, rmask)
        tmp4 = tl.load(in_ptr3 + r0, rmask).to(tl.float32)
        tmp1 = tl.load(in_ptr1 + tmp0 + (5*r0) + tl.zeros([XBLOCK, RBLOCK], tl.int32), xmask & rmask).to(tl.float32)
        # Move tmp2 assignment here would make it work
        tmp3 = tmp1 + tmp2
        tmp5 = tl.libdevice.log(tmp4) if tmp4.dtype is tl.float64 else tl.log(tmp4)
        tmp6 = tmp3 - tmp5
        tmp7 = -tmp6
        tmp8 = tmp7.to(tl.float32)
        _tmp9 = tl.where(xmask & rmask, _tmp9 + tmp8, _tmp9)
    tmp9 = tl.reshape(tl.sum(_tmp9, 1), [XBLOCK, 1])
    for roffset in range(0, rnumel, RBLOCK):
        rindex = roffset + rbase
        rmask = rindex < rnumel
        tmp10 = 5
        tmp11 = tmp9 / tmp10
        tmp12 = tmp11.to(tl.float32)
        tl.store(out_ptr1 + 0 + tl.zeros(tmp12.shape, tl.int32), tmp12, xmask)
```

**Comment by desertfire** [comment]
@jansel , from the generated code, it looks like `tmp2 = tl.load(in_ptr2 + tmp0, None).to(tl.float32)` is "hoisted" out of the loop. Do you know any torchinductor optimization may do that?

**Comment by ngimel** [comment]
Most likely this one https://github.com/pytorch/torchdynamo/blob/30ab3e6cb3c39678c366f102a49cfb59f8507b15/torchinductor/codegen/triton.py#L596

**Comment by ngimel** [comment]
I also think this line
```
tmp0 = tl.load(in_ptr0 + r0, rmask)
```
should have `other=0`, without `other` specified masked values can be anything, and then result in IMA when used as an offset for loading `tmp2`
cc @jansel

**Comment by desertfire** [comment]
Latest error: `RuntimeError: CUDA: Error- illegal address`

It is coming from `tl.store(out_ptr1 + 0 + tl.zeros(tmp12.shape, tl.int32), tmp12, xmask)` in the aforementioned `kernel9`.

**Comment by jansel** [comment]
So for this case I would expect the mask to get applied in the load, not in the indexing.

Here
https://github.com/pytorch/torchdynamo/blob/b2e85a8a47b8f26f51bac2da9e7ec884ac47bc89/torchinductor/codegen/triton.py#L516

Should set need_dense=True, which will cause the mask to get applied to the load.

I'm not sure why the load mask is None.

**Comment by ngimel** [comment]
>`tmp0 = tl.where(rmask, tl.load(in_ptr0 + r0, rmask), 0)`
is the same as
`tmp0 = tl.load(in_ptr0+r0, rmask, other=0)` and the latter I think is slightly more readable. Alternatively, `tmp2` read can be masked (its result is later masked anyway, in _tmp9 computation)
