### ISSUE TITLE
Inference error tracking: "timm_efficientdet"

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#603]
Jason reported out of memory on RTX3090.

**Comment by desertfire** [comment]
New error:
```
    kernel28[grid(24000)](buf74, buf76, buf725, 24000, 6400)
NameError: name 'buf76' is not defined
```

**Comment by jansel** [comment]
> Running on A100, and hitting
> 
> ```
> RuntimeError: gather(): Expected dtype int64 for index
> ```

Hitting same thing as today
