### ISSUE TITLE
inconsistent construction of graphmodule

### ISSUE THREAD

**Issue by wconstab** [pytorch/torchdynamo#619]
Problem: the graphmodule passed to 'my_compiler' is missing key information (e.g. parameters, named_parameters is empty) when model object is constructed inside dynamo context, but the information is present when the module is constructed outside dynamo context.

Example:

```
import torch
import torchdynamo

class ToyModel(nn.Module):
  def __init__(self):
    super(ToyModel, self).__init__()
    self.net1 = nn.Linear(10, 10000)

  def forward(self, x):
    return self.net1(x)

def my_compiler(gm, example_inputs):
    for key, value in gm.named_parameters():
        print(key, isinstance(value, torch.nn.Parameter))

    return gm


with torchdynamo.optimize(my_compiler):
  mod = ToyModel().to('cuda')
  x = torch.randn(20, 10).to('cuda')
  mod(x)
 ```
 
 Prints nothing,  whereas modifying the last lines to
 ```
mod = ToyModel().to('cuda')
with torchdynamo.optimize(my_compiler):
  x = torch.randn(20, 10).to('cuda')
  mod(x)
 ```
 
 prints 

> self_net1.weight True
self_net1.bias True

Not sure how strict of a guarantee we make around the consistency of the generated graphmodule, but this seems like a bug to me.

**Comment by anijain2305** [comment]
The above inconsistency is because optimizing through `__init__` results in `self` being an `UnSpecializedNNModule`. And this leads to a different codepath and thus different graphs.

As we move to decorator usage, we wont go through __init__ functions and this will be cleaner.

```
mod = ToyModel().to('cuda')
opt_mod = torchdynamo.optimize(my_compiler)(mod)
opt_mod(x)
```

@jansel @wconstab Is this ok?

**Comment by anijain2305** [comment]
I am closing this because we will encourage users to use decorators similar to FxModule. And this confusion will go away.
