### ISSUE TITLE
calling 2 models yields 2 separate graphs, nopython is silent about it

### ISSUE THREAD

**Issue by wconstab** [pytorch/torchdynamo#625]
I expected model and model2 to both be fused into one graph.  I also expected that setting nopython=True would tell me why that isn't happening.

```
import torch
import torchdynamo

class ToyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, a, b):
        return a / (torch.abs(a) + 1)

class ToyModel2(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, a, b):
        return x * b

def my_compiler(gm, example_inputs):
    print("my_compiler() called with FX graph:")
    gm.graph.print_tabular()
    return gm.forward

model = ToyModel()
model2 = ToyModel2()
x, y, z = torch.randn(10), torch.randn(10), torch.randn(10)
with torchdynamo.optimize(my_compiler, nopython=True):
    out = model(x, y)
    out = model2(out, z)
```

The output I get is the same, whether I use nopython=True or False:
>my_compiler() called with FX graph:
>opcode         name     target                                                  args           kwargs
>-------------  -------  ------------------------------------------------------  -------------  --------
>placeholder    a        a                                                       ()             {}
>call_function  abs_1    <built-in method abs of type object at 0x7f07ec865ac0>  (a,)           {}
>call_function  add      <built-in function add>                                 (abs_1, 1)     {}
>call_function  truediv  <built-in function truediv>                             (a, add)       {}
>output         output   output                                                  ((truediv,),)  {}
>my_compiler() called with FX graph:
>opcode         name    target                   args       kwargs
>-------------  ------  -----------------------  ---------  --------
>placeholder    b       b                        ()         {}
>placeholder    x       x                        ()         {}
>call_function  mul     <built-in function mul>  (x, b)     {}
>output         output  output                   ((mul,),)  {}

**Comment by voznesenskym** [comment]
Smaller repro, still surfaces it:

```
import torch
import torchdynamo

def forward1(a, b):
    q = a / (torch.abs(a) + 1)
    return q

def forward2(a, b):
    z = x * b
    return z

def my_compiler(gm, example_inputs):
    print("my_compiler() called with FX graph:")
    gm.graph.print_tabular()
    return gm.forward

x, y, z = torch.randn(10), torch.randn(10), torch.randn(10)

def func():
    out = forward1(x, y)
    out = forward2(out, z)

with torchdynamo.optimize(my_compiler, nopython=True):
    func()
```

**Comment by anijain2305** [comment]
Try this. I think `func` might be getting skipped, as there are no tensor inputs to it. I am still getting error with the following repro

~~~
import torch
import torchdynamo

def forward1(a, b):
    q = a / (torch.abs(a) + 1)
    return q

def forward2(a, b):
    z = x * b
    return z

def my_compiler(gm, example_inputs):
    print("my_compiler() called with FX graph:")
    gm.graph.print_tabular()
    return gm.forward

x, y, z = torch.randn(10), torch.randn(10), torch.randn(10)

def func(x, y, z):
    out = forward1(x, y)
    out = forward2(out, z)

with torchdynamo.optimize(my_compiler, nopython=True):
    func(x, y, z)
~~~

**Comment by voznesenskym** [comment]
The bug is around context vs annotation, it seems:

```
@torchdynamo.optimize(my_compiler, nopython=True):
def func():
    out = forward1(x, y)
    out = forward2(out, z)

func()
```

Does the right thing.

This seems like https://github.com/pytorch/torchdynamo/issues/516 by another approach. Thoughts @jansel @ezyang ?

**Comment by ezyang** [comment]
Spicy hot take: let's delete the context manager

**Comment by anijain2305** [comment]
Closing as this is duplicated of #516
