### ISSUE TITLE
TorchBench Inference Accuracy Error: "maml"

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#630]
Repro:
```
python ./benchmarks/torchbench.py -dcuda --inductor --float32 --no-skip  -k maml
```

**Comment by jansel** [comment]
There is a decomp for nll_loss_backward is `torch._decomp`

**Comment by desertfire** [comment]
> There is a decomp for nll_loss_backward is `torch._decomp`

Yes, it's a one-line change I have done locally. The PR for `scatter` is pending. `argmax` is more difficult.

**Comment by jansel** [comment]
Note triton now has upstream support for argmax.

**Comment by desertfire** [comment]
All the missing ops are added. The latest error is an accuracy error,

```
cuda eval  maml                               Similarity score=0.0
INCORRECT
ERROR
```

**Comment by desertfire** [comment]
Latest error msg:
```
Similarity score=0.3764550983905792
INCORRECT
ERROR
```

**Comment by desertfire** [comment]
Close this one, track in https://github.com/pytorch/torchdynamo/issues/1305
