### ISSUE TITLE
[inductor] test_round_correctness_cuda AssertionError on A100

### ISSUE THREAD

**Issue by pyjhzwh** [pytorch/torchdynamo#642]
`pytest test/test_torchinductor -vsk test_round_correctness_cuda` failed because of AssertionError on `self.assertTrue(same(actual, correct, tol=tol, equal_nan=True))` with A100.
https://github.com/pytorch/torchdynamo/blob/main/tests/test_torchinductor.py#L620-L623

**Comment by jansel** [comment]
We should debug this.  `tl.libdevice.nearbyint()` matches eager on my RTX3090, but not on A100/V100

**Comment by ngimel** [comment]
Ugh, looks like libdevice is buggy (not surprising), so next step is trying to generate ptx directly. Should we file this as a triton issue?

**Comment by jansel** [comment]
Yeah, it might make sense to make a minimal repro to double check the issue is on the triton end.
