### ISSUE TITLE
inductor generates 1-inclusive distributions for torch.rand

### ISSUE THREAD

**Issue by ngimel** [pytorch/torchdynamo#649]
According to [docs](https://pytorch.org/docs/stable/generated/torch.rand.html?highlight=rand#torch.rand) `torch.rand` should be 1-exclusive, yet tl.rand generates 1-inclusive distribution. Repro
```
import torch
from torchinductor.compile_fx import compile_fx
import torchdynamo
import torchinductor

torchinductor.config.debug=True
torchinductor.config.triton.cudagraphs=False

@torchdynamo.optimize("inductor")
def rand_fn(x):
    a = torch.rand(x.size(-1), device=x.device)
    return x*a


x = torch.ones(2**26, device="cuda")
out=rand_fn(x)
print(out.min(), out.max()-1) #out.max() - 1 is exactly 0
```
The reason for this is `tl.rand` generates 1-inclusive distribution. While this is arguably a triton bug, we can workaround this on our side (or send a fix to triton)

**Comment by voznesenskym** [comment]
I defer to @jansel w/r/t workaround vs triton fix, but I was just working on the rand cpu stuff, so I am happy to take a look here as well if you like. @jansel lmk.

**Comment by ngimel** [comment]
@voznesenskym if you are looking at rand cpu, here's a cpu bug for you with random and broadcast handling:
```
import torch
from torchinductor.compile_fx import compile_fx
import torchdynamo
import torchinductor

torchinductor.config.debug=True
torchinductor.config.triton.cudagraphs=False

@torchdynamo.optimize("inductor")
def rand_fn(x):
    a = torch.rand(x.size(-1), device=x.device)
    return x*a


x = torch.ones(4, 4, device="cpu")
out=rand_fn(x)
print(out) #all different values, instead of broadcasted row
```

**Comment by jansel** [comment]
hrm, this one might be easier to fix on the triton side.

**Comment by voznesenskym** [comment]
> @voznesenskym if you are looking at rand cpu, here's a cpu bug for you with random and broadcast handling:
> 
> ```
> import torch
> from torchinductor.compile_fx import compile_fx
> import torchdynamo
> import torchinductor
> 
> torchinductor.config.debug=True
> torchinductor.config.triton.cudagraphs=False
> 
> @torchdynamo.optimize("inductor")
> def rand_fn(x):
>     a = torch.rand(x.size(-1), device=x.device)
>     return x*a
> 
> 
> x = torch.ones(4, 4, device="cpu")
> out=rand_fn(x)
> print(out) #all different values, instead of broadcasted row
> ```

Are you sure this isn't doing the right thing?

```
import torch
from torchinductor.compile_fx import compile_fx
import torchdynamo
import torchinductor

# torchinductor.config.debug=True
# torchinductor.config.triton.cudagraphs=False


@torchdynamo.optimize("inductor")
def rand_fn(x):
    a_dyn = torch.rand(x.size(-1), device=x.device)
    return x*a_dyn

x = torch.ones(4, 4, device="cpu")

a_no_dyn = torch.rand(x.size(-1), device=x.device)

out=rand_fn(x)
print(out) #all different values, instead of broadcasted row
out2 = x*a_no_dyn
print(out2)
```

Comparing out to out2, they look like they are doing the same thing:

```
tensor([[0.9989, 0.2295, 0.2302, 0.1959],
        [0.9989, 0.2295, 0.2302, 0.1959],
        [0.9989, 0.2295, 0.2302, 0.1959],
        [0.9989, 0.2295, 0.2302, 0.1959]])
tensor([[0.1390, 0.8347, 0.2751, 0.5220],
        [0.1390, 0.8347, 0.2751, 0.5220],
        [0.1390, 0.8347, 0.2751, 0.5220],
        [0.1390, 0.8347, 0.2751, 0.5220]])
```

Are you seeing something different?

**Comment by voznesenskym** [comment]
Oh I see the problem :) I checked out a commit on the main branch behind 6639e0f3945e92765f24ff3f037e362df5faefb6, it has your bug. @ngimel rebase to latest main and it should work as expected

**Comment by jansel** [comment]
Fixed in https://github.com/openai/triton/pull/601

**Comment by jansel** [comment]
@voznesenskym perhaps we should mimic the same logic in the CPU version.
