### ISSUE TITLE
Large spike in peak memory with different backends

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#716]
Following is the peak memory footprint for huggingface models. I ran few warmups and then measured peak memory (after resetting it earlier).

baseline = usual way (w/o any TorchDynamo)
eager = TorchDynamo + eager (to check if Dynamo alone causes spikes)
aot_nop = TorchDynamo + AOT Autograd + eager compiler (or no-op compiler)
aot_nvfuser = TorchDynamo + AOT Autograd + ts-nvfuser

<img width="836" alt="image" src="https://user-images.githubusercontent.com/13822661/183237220-71b466e3-8eb7-42ab-9cde-a5227573d01a.png">

The peak memory footprint creates bad UX, as the batch size that fits in GPU with eager, might not be able to fit anymore during the Dynamo + backend tracing/optimization.

cc @Chillee for the issues for AOTAutograd
cc @bdhirsh for similar issue that I saw earlier with functionalization (here functionalization is turned off)

WIP
* PR to regenerate the numbers
* Inductor numbers

**Comment by soumith** [comment]
is aot_inductor going to be similar to aot_nop or aot_ts_nvfuser?

**Comment by soumith** [comment]
whoops, just saw that the Inductor numbers are WIP -- just ignore my comment
