### ISSUE TITLE
torchinductor doesn't work with latest PyTorch

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#720]
I get this failure when trying to import.

```
Attempting to register a python meta kernel for a view operator: aten.t.default.
We shouldn't do this, because the output will report as not having aliased storages.
All view ops have meta kernels in C++ today, so we should use those instead.

If you're registering an operator through the `@register_decomposition` decorator,
Please set `disable_meta=True`.
```

This error was added in https://github.com/pytorch/pytorch/pull/82007

I think probably we just need to avoid registering meta here.

@bdhirsh @eellison

**Comment by ezyang** [comment]
This would also get fixed by https://github.com/pytorch/pytorch/issues/82331

**Comment by jansel** [comment]
This seems to be fixed now.  Perhaps by @Chillee's latest PR.

**Comment by Chillee** [comment]
Was fixed by https://github.com/pytorch/torchdynamo/commit/3eba0faffecc8b48e61f089fc701ed8f5faefe26
