### ISSUE TITLE
torchinductor should default generating fallback for all custom ops

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#722]
torchinductor has no reason to know about arbitrary custom ops (well, at least until we let people define lowerings for torchinductor custom ops). Thus, even for developers, the default of erroring on unsupported ops is wrong; we should just always fallback in these cases. Custom ops are also irritating to write fallback for because you have to do the "test if you can import" song and dance that we do for torchvision)

**Comment by ezyang** [comment]
The import song and dance is especially annoying as there is not a quick way to work out what import produces registrations for a custom operator, given the custom op name.

**Comment by jansel** [comment]
Would this also be fixed by https://github.com/pytorch/torchdynamo/issues/724#issuecomment-1207422821
