### ISSUE TITLE
Use opinfo testing in TorchInductor

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#727]
We should start using opinfo testing to get more coverage of ops in inductor.

One example of a case where that might help:

> It's possible to use to use `torch.testing._internal.common_methods_invocations.sample_inputs_roll` to get the arguments for testing.
> Then it would match what's being tested in PyTorch in `test/test_ops.py -k roll` tests.

_Originally posted by @IvanYashchuk in https://github.com/pytorch/torchdynamo/pull/725#discussion_r939668338_

**Comment by ngimel** [comment]
cc @ezyang, we should systematically run OpInfo tests with inductor mode, not just get sample inputs.

**Comment by ezyang** [comment]
a lot of failures is fine, we will generate a big xfail list and then slowly buzz through them until they're all gone.

**Comment by eellison** [comment]
Un-assigning for now because I'm getting backed up on fake tensor work.

**Comment by Chillee** [comment]
Might be a good task if you're interested? @lezcano

**Comment by Lezcano** [comment]
I think this one may be better suited for someone that understands TorchInductor a bit better, as they would be able to sort the failures as they happen.
