### ISSUE TITLE
dynamo fails to graph break when it should on some indexing ops.

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/torchdynamo#739]
I ran into this when trying to turn functionalization on by default and seeing a few model failures. The repro looks like this:
```
import torch
import torchdynamo


def forward(y):
    x = torch.ones(8)
    idx = y[0]
    out = x[idx:]
    return out


with torchdynamo.optimize("aot_nop", nopython=False) as ctxt:
    out = forward(torch.ones(8, dtype=torch.long))
```

Which fails with:
```
  File "/raid/hirsheybar/pytorch_dynamoE2E/torch/fx/experimental/proxy_tensor.py", line 155, in proxy_call
    raise RuntimeError("It appears that you're trying to get value out of a tracing tensor - erroring out! "
```

The issue is that:

(1) `y` is a 1-D tensor, so `idx = y[0]` creates a scalar-tensor (this by itself is okay)
(2) We pass `idx` in as an indexing argument into a `slice()` call, which converts the scalar-tensor to a real scalar, and requires inspecting the actual data. `slice()` will internally call `.item()` in this case, which causes proxy-tensor tracing to fail.

It looks like dynamo needs to realize that passing a scalar-tensor argument into `slice()` requires a graph break in this case. Instead, dynamo generates a single graph that looks like this:
```
graph():
    %y : torch.Tensor [#users=1] = placeholder[target=y]
    %ones : [#users=1] = call_function[target=torch.ones](args = (8, 8), kwargs = {})
    %getitem : [#users=1] = call_function[target=operator.getitem](args = (%y, 0), kwargs = {})
    %getitem_1 : [#users=1] = call_function[target=operator.getitem](args = (%ones, (0, slice(getitem, None, None))), kwargs = {})
    return (getitem_1,)
```

As for why this only manifested when I tried to turn on functionalization: It looks like a common pattern is to have code like this:
```
mask[index_tensor[i]:] = 0
```

Dynamos' built-in functionalization isn't able to remove that mutation, so dynamo will just fall back to eager. But once I turn on functionalization, which successfully removes that mutation, dynamo will try to pass the entire graph on to AOTAutograd, which is where the failure shows up

**Comment by bdhirsh** [comment]
I'd like to take a stab at this one, since I'm trying to understand dynamo internals a bit better :)

**Comment by ezyang** [comment]
Related https://github.com/pytorch/pytorch/issues/81529

**Comment by anijain2305** [comment]
We graph break on this now. So, we can close this one.
