### ISSUE TITLE
Redo config modules so we can error if users try to set non-existent configuration values

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#767]
The current idiom for defining config modules makes it easy for users to set nonexistent config values. This is especially troublesome if we delete configuration values in the future. We should have some alternative idiom for defining config modules.

My preference is we turn the config modules into a dataclass, which is minimal boilerplate, and then add a `__setattr__` to error when you try to set a config value doesn't exist. The main downside is that you need to use `field()` syntax to initialize configs with nontrivial mutable objects. It also means module syntax no longer works. We can also use the module replacement trick to preserve the module syntax.

Does anyone else want to paint the bikeshed a different color?

cc @jansel @anijain2305 @voznesenskym

**Comment by jansel** [comment]
Some black magic that might solve this without any refactoring:
```
>>> import types
>>> class SealedModule(types.ModuleType):
...     def __setattr__(self, name, val):
...         assert name in self.__dict__, "Cannot add new attributes to torchdynamo.config"
...         return super().__setattr__(name, val)
... 
>>> import torchdynamo.config
>>> torchdynamo.config.__class__ = SealedModule
>>> 
>>> torchdynamo.config.dynamic_shapes = True
>>> torchdynamo.config.dynamic_shapes2 = True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in __setattr__
AssertionError: Cannot add new attributes to torchdynamo.config
>>> 
```


That said refactoring how configuration is handled to take more options as kwargs to `torchdynamo.optimize` and remove the need for global mutation seems like a good idea to me.
