### ISSUE TITLE
Investigate issue with python key tracing and LSTM

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#78]
Repro:
```
env PYTHONKEY_VERBOSE=1 ./torchbench.py --no-skip --python-key -n 1 -k demucs
```
Python key tracing produces the following warning:
```
WARNING:torchdynamo.optimizations.python_key:returning real tensor? call_function _operator.getitem <built-in function getitem> (mod_model_lstm_lstm, 0) {}
```
which is coming from this line:
https://github.com/facebookresearch/torchdynamo/blob/e84f9fee18ae5ab7bfca5504e200503de174efb5/torchdynamo/optimizations/python_key.py#L97

This makes me worries we are missing some operators.  While python key tracing, everything should be a `functorch._src.python_key.PythonTensor`, yet somehow an unwrapped tensor is leaking through.

I suspect our pytree walk of the module hierarchy might be missing some LSTM-related wrapper class.  Though I haven't confirmed this.  

cc @Chillee

**Comment by Chillee** [comment]
Oh, there’s one exception to the “everything is a tensor” rule - when an operator returns a tuple of tensors. We’ll immediately unpack the tuples with operator.getitem.

**Comment by jansel** [comment]
This `getitem` call is generated by TorchDynamo.  TorchDynamo actually does similar unpacking of tuples.  From the user code, it unpacked the tuple and found an unwrapped tensor.

You think this case is correct @Chillee?

**Comment by Chillee** [comment]
I looked into this... LSTMs seem to behave very strangely.

Indeed, there appears to be a parameter that shows up in the graph that, for some reason, isn't covered by pulling out the `named_parameters` and using the functionalization pass.

**Comment by ezyang** [comment]
This passes now.

**Comment by Chillee** [comment]
What was the issue?

**Comment by ezyang** [comment]
I don't know, but if I had to guess it might be from the lift fresh changes
