### ISSUE TITLE
Add Timers for major components

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#795]
Add a simple timer for

* Dynamo bytecode transformation time
* Backend compilation time
* Inductor compilation time
* Triton compilation time
* Triton-autotuning time

cc @ezyang @ngimel

**Comment by anijain2305** [comment]
@wconstab already has this working. The missing items are

1) Figure out a suitable aggregate to track the health of compilation time.
2) Add that to nightly benchmarks

**Comment by wconstab** [comment]
other wish-list items from me
* aggregating specific function names (aot_autograd.locals.blah.blah) into categories we care about (dynamo, aot, inductor, triton) -  may not be a big problem 
* dealing with overlapping timings (one function actually includes another but it isn't clear in the flat list)
* making sure we aren't missing any hot areas (if an expensive function isn't annotated, we simply miss it)

**Comment by anijain2305** [comment]
@wconstab Can we close this one?
