### ISSUE TITLE
Inductor runs in CI

### ISSUE THREAD

**Issue by anijain2305** [pytorch/torchdynamo#798]
@pyjhzwh mentioned that there was a torchbench model that used to pass earlier with Inductor for inference and now failing.

Suggest to add a CircleCI GPU job to test inductor on Torchbench. If compilation time is the problem, we can cherry-pick 8-10 models and add a job.

An example is here - https://github.com/pytorch/torchdynamo/pull/703

cc @desertfire @Chillee

**Comment by anijain2305** [comment]
xref - https://github.com/pytorch/torchdynamo/issues/799

**Comment by desertfire** [comment]
https://github.com/pytorch/torchdynamo/pull/866 enables caching for CircleCI.

**Comment by desertfire** [comment]
https://github.com/pytorch/torchdynamo/pull/919 adds TorchBench inference and training.

**Comment by desertfire** [comment]
https://github.com/pytorch/torchdynamo/pull/963 adds Huggingface inference and training.

**Comment by desertfire** [comment]
https://github.com/pytorch/torchdynamo/pull/1028 adds TIMM
