### ISSUE TITLE
Deduplicate constants in TorchInductor

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#816]
In some models (Super_SlowMo) I have noticed many duplicate constants all with the same values.

We should add some logic here:
https://github.com/pytorch/torchdynamo/blob/10b4dc031453b3282a3a4c07da212b01fb9e859a/torchinductor/graph.py#L151

That more aggressively checks for constants containing the same values and folds them into a single copy.

**Comment by voznesenskym** [comment]
@jansel mind if I take this one? Would be good for me to get more familiar with inductor.

**Comment by voznesenskym** [comment]
#820
