### ISSUE TITLE
Revisit inplace_buffers=True for TorchInductor

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#823]
TorchInductor has support for inplacing operations, but it is currently disabled:
https://github.com/pytorch/torchdynamo/blob/8e4abe3f66fb6b8d97d6461d64f9c3be323a523e/torchinductor/config.py#L28
due to some bugs in the past.

We should turn this back on and fix any issues it causes on our benchmark suites.

This could help with #822

**Comment by Chillee** [comment]
Seems like this is currently quite broken.

Turning it on with resnet18 (`time ./benchmarks/torchbench.py -dcuda --inductor --training --no-skip --float16 -k resnet18 --batch_size 32`) results in 
```
  File "/scratch/chilli/fresh/torchdynamo/torchinductor/scheduler.py", line 348, in mark_run
    self.allocate()
  File "/scratch/chilli/fresh/torchdynamo/torchinductor/scheduler.py", line 336, in allocate
    V.kernel.args.make_inplace(
AttributeError: 'NullHandler' object has no attribute 'args'
```

**Comment by jansel** [comment]
Yeah, I'm not surprised.  The code might a bit rotted a bit.
