### ISSUE TITLE
FusedSchedulerNode does not consider the index of MemoryDep edges

### ISSUE THREAD

**Issue by jansel** [pytorch/torchdynamo#828]
Spinning this off into its own issue:

_Originally posted by @jansel in https://github.com/pytorch/torchdynamo/issues/810#issuecomment-1216001216_

In `test_index_put_issue` you have:
```
# sum
SchedulerNode(name='buf0').unmet_dependencies = set()
# zero the buffer
SchedulerNode(name='buf1').unmet_dependencies = set()
# index_put_ to mutate buf1
SchedulerNode(name='buf2').unmet_dependencies = {
    StarDep(name='buf1'),
    MemoryDep(name='buf0', index=c0, size=(393216,))
}
```

Note the `StarDep()` is actually generated correctly.  Which should force `buf1` and `buf2` into separate kernels, since every element of `buf1` must be computed before `buf2` is runnable.

The pre-fusion pass then merges buf1 and buf2 into:
```
FusedSchedulerNode(nodes=buf1_buf2).unmet_dependencies = {
    MemoryDep(name='buf0', index=c0, size=(393216,))
}
```
This pre-fusion is incorrect, because `StarDep(name='buf1')`  does not match `MemoryDep(name='buf1', index=c0, ...)`.  We should modify pre-fusion to include the `MemoryDep` on its edges and check those.

#811 works around this issue by checking the dependencies on `buf2` at the time `buf1_buf2` is unpacked.  This causes `pop_fusable()` to only return `buf1` and not `buf2`.  However, the `FusedSchedulerNode` is still incorrectly generated.

cc @Chillee

**Comment by Chillee** [comment]
I wouldn't really say #811 is working around the issue - my understanding of the root of the issue that's being resolved there is this.

Let's say A and B are both pointwise ops, A => B, and we decide to prefuse A and B. Then, if we `pop_fusable`, we might pop B and then A, and then call codegen on B and then A, which leads to issues.

I agree the pre-fusion is still incorrect, but with #811, my understanding is that prefusion should pretty much never lead to correctness issues.

Regarding pre-fusion, are you saying that if one node has a StarDep to another node, they should never be fused?

**Comment by pyjhzwh** [comment]
> B and then A, and then call codegen on B and then A, which leads to issues.

I think this is fixed by https://github.com/pytorch/torchdynamo/pull/794

>  if one node has a StarDep to another node, they should never be fused?

I think so. For InputsKernel class, its read and writes are StarDep. For example, ExternKernel is a subclass of InputsKernel. We must wait for the whole buffer (buf1) to be computed before the buf2 reads from buf1.

**Comment by jansel** [comment]
> Let's say A and B are both pointwise ops, A => B, and we decide to prefuse A and B. Then, if we `pop_fusable`, we might pop B and then A, and then call codegen on B and then A, which leads to issues.

#811 fixes this.  B will not be popped on the first call to `pop_fusable`.  First A will get popped, then B will only be popped after `A.mark_fusable()` is called.

> I agree the pre-fusion is still incorrect, but with #811, my understanding is that prefusion should pretty much never lead to correctness issues.

#811 fixes the correctness issue, but we are now generating a pointless FusedSchedulerNode that could prevent legal fusions from happening.

> Regarding pre-fusion, are you saying that if one node has a StarDep to another node, they should never be fused?

`StarDep("A")` means the node depends on `A[*]` (all elements of A).  The entire A buffer must be fully computed before the node with that dep is scheduled.  You can still fuse it with other things, just not with A.

This is similar to something like `B[::-1]` which reads something in reverse order.  Or with different transpose/permutes/views.  You can only fuse two buffers if the "write" MemoryDep matches the "read" MemoryDep.

**Comment by Chillee** [comment]
> You can only fuse two buffers if the "write" MemoryDep matches the "read" MemoryDep.

So currently I assume 2 buffers are vertically fusable if they have the same group and have a direct edge between them. I suppose I should instead be checking if all of the reads align with all of the writes?

**Comment by jansel** [comment]
> So currently I assume 2 buffers are vertically fusable if they have the same group and have a direct edge between them. I suppose I should instead be checking if all of the reads align with all of the writes?

Correct.  Note there can be multiple edges between two nodes (for things like pooling ops that read multiple elements).

**Comment by jansel** [comment]
I plan to take a look at prefusion to take into account dependency types.
