### ISSUE TITLE
NotImplementedError: fastNLP_Bert

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#837]
Repro:
```
./benchmarks/torchbench.py -dcuda --inductor --float32 --no-skip  -k fastNLP_Bert
```

Error msg:
```
  File "pytorch/torch/fx/proxy.py", line 157, in create_arg
    raise NotImplementedError(f"argument of type: {type(a)}")
NotImplementedError: argument of type: <class 'numpy.int64'>
```

**Comment by desertfire** [comment]
cc @Chillee

**Comment by ezyang** [comment]
Probably should be graph breaking when we hit numpy operations

**Comment by anijain2305** [comment]
cc @yanboliang

**Comment by jansel** [comment]
> Probably should be graph breaking when we hit numpy operations

I suspect this is a numpy integer type being passed as an arg to pytorch.  E.g.
```
numpy_int = np.int64(10)
...
x=torch.empty(numpy_int)
```

A few options (would need to look at the case to figure out the right thing):
1) Make FX treat numpy integers as python integers
2) Make dynamo convert numpy integers to python integers
3) Convert this to args to the graphs

**Comment by yanboliang** [comment]
I think this has been fixed by https://github.com/pytorch/torchdynamo/pull/806, where we use the option 2 mentioned by @jansel.
The reason that I don't merge is we hit another fake tensor issue, which @eellison is taking a look.

**Comment by yanboliang** [comment]
Depends on https://github.com/pytorch/pytorch/pull/83567

**Comment by yanboliang** [comment]
@eellison I think this still blocks by the fake tensor issue, #1059 seems doesn't fix it yet. I run my PR #806 on the latest main(including #1059), it still failed(search ```fastNLP_Bert ``` in [circle CI log](https://app.circleci.com/pipelines/github/pytorch/torchdynamo/1926/workflows/c54c7010-5983-4618-9e9d-16d3c9165296/jobs/5522/parallel-runs/0/steps/0-111)). But it passed if I turn off fake tensor.

**Comment by voznesenskym** [comment]
> > Probably should be graph breaking when we hit numpy operations
> 
> 
> 
> I suspect this is a numpy integer type being passed as an arg to pytorch.  E.g.
> 
> ```
> 
> numpy_int = np.int64(10)
> 
> ...
> 
> x=torch.empty(numpy_int)
> 
> ```
> 
> 
> 
> A few options (would need to look at the case to figure out the right thing):
> 
> 1) Make FX treat numpy integers as python integers
> 
> 2) Make dynamo convert numpy integers to python integers
> 
> 3) Convert this to args to the graphs

For (2) can we just call .item() to turn numpy types into Python types?

**Comment by yanboliang** [comment]
> Fix sth like torch.LongTensor(list(np.int64, np.int64, ...)) #806

That exactly what https://github.com/pytorch/torchdynamo/pull/806 does. That problem has been resolved(pending PR), here we are talking about another fake tensor issue revealed by that fix.

**Comment by desertfire** [comment]
@yanboliang , this one has been pending for a while. Any progress here?
