### ISSUE TITLE
AttributeError: 'ComputedBuffer' object has no attribute 'iter_reordering_reindex'

### ISSUE THREAD

**Issue by desertfire** [pytorch/torchdynamo#862]
Repro:
```
benchmarks/timm_models.py --training --float32 --use-eval-mode --inductor -k jx_nest_base
```
Error:
```
Traceback (most recent call last):
  File "/fsx/users/binbao/torchdynamo-tip/benchmarks/common.py", line 973, in run_one_model
    new_result = accuracy_model_iter_fn(model, example_inputs)
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 152, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/timm_models.py", line 304, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "benchmarks/timm_models.py", line 304, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "benchmarks/timm_models.py", line 308, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/fsx/users/binbao/pytorch-release/torch/nn/modules/module.py", line 1185, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/users/binbao/conda/envs/release/lib/python3.8/site-packages/timm/models/nest.py", line 371, in forward
    def forward(self, x):
  File "/fsx/users/binbao/torchdynamo-tip/torchdynamo/eval_frame.py", line 152, in _fn
    return fn(*args, **kwargs)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 795, in forward
    return compiled_f(
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 781, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 360, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "/fsx/users/binbao/pytorch-release/functorch/functorch/_src/aot_autograd.py", line 259, in aot_dispatch_autograd
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/compile_fx.py", line 237, in fw_compiler
    return compile_fx_inner(
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/compile_fx.py", line 115, in compile_fx_inner
    compiled_fn = wrap(graph.compile_to_fn())
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/graph.py", line 299, in compile_to_fn
    code = self.codegen()
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/graph.py", line 292, in codegen
    self.scheduler = Scheduler(self.buffers)
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/scheduler.py", line 846, in __init__
    self.nodes.append(SchedulerNode(self, node, group_fn))
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/scheduler.py", line 254, in __init__
    ) = node.simplify_and_reorder()
  File "/fsx/users/binbao/torchdynamo-tip/torchinductor/ir.py", line 1788, in simplify_and_reorder
    reordering_reindex[i] = reads_buf.iter_reordering_reindex
AttributeError: 'ComputedBuffer' object has no attribute 'iter_reordering_reindex'
```

**Comment by Chillee** [comment]
Seems like a good candidate for minifier :)

**Comment by pyjhzwh** [comment]
https://github.com/pytorch/torchdynamo/blob/main/torchinductor/ir.py#L1788
It should be some issue of my code. I think changing this line to 
```
                try:
                    reordering_reindex[i] = reads_buf.iter_reordering_reindex
                except AttributeError:
                    pass
```
would solve this

**Comment by pyjhzwh** [comment]
But on my side, `benchmarks/timm_models.py --training --float32 --use-eval-mode --inductor -k jx_nest_base
` will cause error
```
Traceback (most recent call last):
  File "/scratch/panyj/work/fresh/torchdynamo/benchmarks/common.py", line 1021, in run_one_model
    new_result = accuracy_model_iter_fn(model, example_inputs)
  File "/scratch/panyj/work/fresh/torchdynamo/torchdynamo/eval_frame.py", line 152, in _fn
    return fn(*args, **kwargs)
  File "/scratch/panyj/work/fresh/torchdynamo/benchmarks/timm_models.py", line 304, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "/scratch/panyj/work/fresh/torchdynamo/benchmarks/timm_models.py", line 304, in forward_and_backward_pass
    def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
  File "/scratch/panyj/work/fresh/torchdynamo/benchmarks/timm_models.py", line 308, in forward_and_backward_pass
    pred = mod(*cloned_inputs)
  File "/scratch/panyj/work/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/users/panyj/conda/envs/fresh/lib/python3.9/site-packages/timm/models/nest.py", line 371, in forward
    def forward(self, x):
  File "/scratch/panyj/work/fresh/torchdynamo/torchdynamo/eval_frame.py", line 152, in _fn
    return fn(*args, **kwargs)
  File "/scratch/panyj/work/pytorch/functorch/functorch/_src/aot_autograd.py", line 696, in forward
    return compiled_f(
  File "/scratch/panyj/work/fresh/torchdynamo/torchdynamo/eval_frame.py", line 152, in _fn
    return fn(*args, **kwargs)
  File "/scratch/panyj/work/pytorch/functorch/functorch/_src/aot_autograd.py", line 239, in forward
    fw_module, bw_module = partition_fn(fx_g, joint_inputs)
  File "/scratch/panyj/work/pytorch/functorch/functorch/_src/partitioners.py", line 411, in min_cut_rematerialization_partition
    fw_module, bw_module = _extract_fwd_bwd_modules(joint_module, saved_values)
  File "/scratch/panyj/work/pytorch/functorch/functorch/_src/partitioners.py", line 116, in _extract_fwd_bwd_modules
    bwd_module = fx.GraphModule(joint_module, bwd_graph)
  File "/scratch/panyj/work/pytorch/torch/fx/graph_module.py", line 366, in __init__
    self.graph = graph
  File "/scratch/panyj/work/pytorch/torch/nn/modules/module.py", line 1309, in __setattr__
    super().__setattr__(name, value)
  File "/scratch/panyj/work/pytorch/torch/fx/graph_module.py", line 404, in graph
    self.recompile()
  File "/scratch/panyj/work/pytorch/torch/fx/graph_module.py", line 641, in recompile
    cls.forward = _forward_from_src(self._code, python_code.globals)
  File "/scratch/panyj/work/pytorch/torch/fx/graph_module.py", line 77, in _forward_from_src
    _exec_with_source(src, globals_copy)
  File "/scratch/panyj/work/pytorch/torch/fx/graph_module.py", line 71, in _exec_with_source
    exec(compile(src, key, 'exec'), globals)
  File "<eval_with_key>.10", line 17
    return [view_sym_int, permute_default_190, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, sum_dim_int_list_27, Invalid Node, Invalid Node, Invalid Node, None]
                                                       ^
SyntaxError: invalid syntax
```

**Comment by desertfire** [comment]
> But on my end, `benchmarks/timm_models.py --training --float32 --use-eval-mode --inductor -k jx_nest_base ` will cause error
> 
> ```
> Traceback (most recent call last):
>   File "/scratch/panyj/work/fresh/torchdynamo/benchmarks/common.py", line 1021, in run_one_model
>     new_result = accuracy_model_iter_fn(model, example_inputs)
>   File "/scratch/panyj/work/fresh/torchdynamo/torchdynamo/eval_frame.py", line 152, in _fn
>     return fn(*args, **kwargs)
>   File "/scratch/panyj/work/fresh/torchdynamo/benchmarks/timm_models.py", line 304, in forward_and_backward_pass
>     def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
>   File "/scratch/panyj/work/fresh/torchdynamo/benchmarks/timm_models.py", line 304, in forward_and_backward_pass
>     def forward_and_backward_pass(self, mod, inputs, collect_outputs=True):
>   File "/scratch/panyj/work/fresh/torchdynamo/benchmarks/timm_models.py", line 308, in forward_and_backward_pass
>     pred = mod(*cloned_inputs)
>   File "/scratch/panyj/work/pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/fsx/users/panyj/conda/envs/fresh/lib/python3.9/site-packages/timm/models/nest.py", line 371, in forward
>     def forward(self, x):
>   File "/scratch/panyj/work/fresh/torchdynamo/torchdynamo/eval_frame.py", line 152, in _fn
>     return fn(*args, **kwargs)
>   File "/scratch/panyj/work/pytorch/functorch/functorch/_src/aot_autograd.py", line 696, in forward
>     return compiled_f(
>   File "/scratch/panyj/work/fresh/torchdynamo/torchdynamo/eval_frame.py", line 152, in _fn
>     return fn(*args, **kwargs)
>   File "/scratch/panyj/work/pytorch/functorch/functorch/_src/aot_autograd.py", line 239, in forward
>     fw_module, bw_module = partition_fn(fx_g, joint_inputs)
>   File "/scratch/panyj/work/pytorch/functorch/functorch/_src/partitioners.py", line 411, in min_cut_rematerialization_partition
>     fw_module, bw_module = _extract_fwd_bwd_modules(joint_module, saved_values)
>   File "/scratch/panyj/work/pytorch/functorch/functorch/_src/partitioners.py", line 116, in _extract_fwd_bwd_modules
>     bwd_module = fx.GraphModule(joint_module, bwd_graph)
>   File "/scratch/panyj/work/pytorch/torch/fx/graph_module.py", line 366, in __init__
>     self.graph = graph
>   File "/scratch/panyj/work/pytorch/torch/nn/modules/module.py", line 1309, in __setattr__
>     super().__setattr__(name, value)
>   File "/scratch/panyj/work/pytorch/torch/fx/graph_module.py", line 404, in graph
>     self.recompile()
>   File "/scratch/panyj/work/pytorch/torch/fx/graph_module.py", line 641, in recompile
>     cls.forward = _forward_from_src(self._code, python_code.globals)
>   File "/scratch/panyj/work/pytorch/torch/fx/graph_module.py", line 77, in _forward_from_src
>     _exec_with_source(src, globals_copy)
>   File "/scratch/panyj/work/pytorch/torch/fx/graph_module.py", line 71, in _exec_with_source
>     exec(compile(src, key, 'exec'), globals)
>   File "<eval_with_key>.10", line 17
>     return [view_sym_int, permute_default_190, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, Invalid Node, sum_dim_int_list_27, Invalid Node, Invalid Node, Invalid Node, None]
>                                                        ^
> SyntaxError: invalid syntax
> ```

You mean locally you are hitting a different issue before applying your change? In that case, you need to update your pytorch.

**Comment by desertfire** [comment]
fixed by https://github.com/pytorch/torchdynamo/pull/864
