### ISSUE TITLE
Show line errors in user code

### ISSUE THREAD

**Issue by msaroufim** [pytorch/torchdynamo#891]
@yanboliang recently debugged an issue that prevented `pytorch-geometric` from working with dynamo

The actual problem per Yanbo was the below

The problem is we don't handle ```autograd.profiler.*``` well, but they are used widely during model training iterations, e.g, ```optimizer.zero_grad()``` and ```optimizer.step()``` in your example. Sure, if you have other examples that's doesn't work well, send me the repros and I'm glad to help debug.

_Originally posted by @yanboliang in https://github.com/pytorch/torchdynamo/issues/829#issuecomment-1219765418_

BUT looking at the actual error message I got it was the below where there is a hint that maybe something is wrong with the profiler but it doesn't relate back to a line of code I can comment out. If it did I would have been able to comment out a line and get my model to work. Also potentially an issue where a minifier would have helped

```
  File "/home/ubuntu/torchdynamo/torchdynamo/variables/misc.py", line 298, in __init__
    super(ProfileRecordFunctionVariable, self).__init__(
  File "/home/ubuntu/torchdynamo/torchdynamo/variables/misc.py", line 118, in __init__
    super(ContextWrappingVariable, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'enter'
========== Exception (above) while processing ==========
  File "gnn.py", line 35, in <module>
    optimizer.zero_grad()
  File "/home/ubuntu/anaconda3/envs/pyg/lib/python3.8/site-packages/torch/optim/optimizer.py", line 216, in zero_grad
    def zero_grad(self, set_to_none: bool = False):
```

**Comment by yanboliang** [comment]
@msaroufim Your codebase is not updated. We removed ```ProfileRecordFunctionVariable``` in the latest main branch. Can you pull the main branch and test this again?

**Comment by msaroufim** [comment]
Oh sorry I should clarify, I did not mean I'm still seeing the issue. I'm not and thank you for resolving it.

I'm making an ask to improve the debugging experience so I could have figured out the exact line in my code I needed to remove to make this work without asking you for help. The current stacktrace error does not show exactly which line of code was problematic.

**Comment by mlazos** [comment]
#793 should help with this. It will provide a call stack. The line numbers of dynamo-compiled functions need to be fixed though.
