### ISSUE TITLE
FAMBench Integration for Training

### ISSUE THREAD

**Issue by bitfort** [pytorch/torchdynamo#91]

**Comment by xuzhao9** [comment]
Adding support in https://github.com/pytorch/benchmark/pull/821

**Comment by xuzhao9** [comment]
Added fambench_dlrm and fambench_xlmr. FAMBench RNNT is broken (https://github.com/facebookresearch/FAMBench/issues/85)

**Comment by ciciewang** [comment]
added two models for FAMBench.

**Comment by anijain2305** [comment]
Torchbench integrations seems complete. Closing this. Feel free to reopen.
