### ISSUE TITLE
Using `min` with dynamic shape and a python constant inside  torchdynamo.export fails

### ISSUE THREAD

**Issue by tugsbayasgalan** [pytorch/torchdynamo#911]
Below is the repro:
```
torchdynamo.config.dynamic_shapes = True
def f(x, a):
    return min(x.shape[0], a)

traced = torchdynamo.export(f, torch.ones(6), 3)
print(traced)
```
With the error:
```
TypeError: clamp() received an invalid combination of arguments - got (int, max=int), but expected one of:
 * (Tensor input, Tensor min, Tensor max, *, Tensor out)
 * (Tensor input, Number min, Number max, *, Tensor out)
 ```
I think the reason is `min` calls torch.clamp internally (https://github.com/pytorch/torchdynamo/blob/main/torchdynamo/variables/builtin.py#L373). This is problematic in the case of DynamicShapeVariable (which is x right now), because it doesn't resolve to TensorVariable. But the according to pytorch documentation of torch.clamp, the first argument to it should be a tensor (not a number). Adding this line fixes the issue:
```
if isinstance(a, DynamicShapeVariable):
   a = variables.TorchVariable(torch.tensor).call_function(tx, [a], {})
```

cc: @voznesenskym

**Comment by voznesenskym** [comment]
Nice find! Try putting up a PR with the fix and some tests, and if it passes CI, we can see what the team thinks :)

**Comment by jansel** [comment]
This fix seems reasonable to me.  We should do the same for `max`.
