### ISSUE TITLE
TIMM models regressed significantly from 2 days ago

### ISSUE THREAD

**Issue by soumith** [pytorch/torchdynamo#936]
1.39x 2 days ago - https://github.com/pytorch/torchdynamo/issues/681#issuecomment-1220968892

vs

1.06x yesterday (and today) - https://github.com/pytorch/torchdynamo/issues/681#issuecomment-1221308526

**Comment by jansel** [comment]
I think this might be because of https://github.com/pytorch/torchdynamo/issues/929

**Comment by anijain2305** [comment]
Confirmed from the logs that its because of #929

**Comment by anijain2305** [comment]
cc @desertfire Should we add some kind of performance tests in CI?

**Comment by soumith** [comment]
the PR that created #929 was reverted.

But today's CI which ran 3 hours ago still has the regression.

**Comment by desertfire** [comment]
> the PR that created #929 was reverted.
> 
> But today's CI which ran 3 hours ago still has the regression.

I suppose you are referring to https://github.com/pytorch/torchdynamo/issues/681#issuecomment-1221730080. From its Build Summary section, we can see Jason's revert hasn't been picked up yet.
```
## Commit hashes ## torchdynamo commit: https://github.com/pytorch/torchdynamo/commit/8bbecb0cc8b9d2003d93161ea1b1b3060e31b0e5 pytorch commit: 09e837634bc76c4380db7119e0e997816d584844 functorch commit: de7b1863527256446c0ad302daaee4e2b9ec62c2 torchbench commit: be4fe4856a0bf2481d18826e2e761fd4f0f34845
```

@anijain2305 , can we provide a functionality to manually kick off a perf run in case like this? On your comment on adding perf tests in CI, yes I certainly agree. Let me enable failure checking first and then see how stable the numbers on CI are.

**Comment by anijain2305** [comment]
Automatic performance benchmarking run failed yesterday for some reason :( It seems there was some issue with Slurm `srun`. And infra just reposted the old results (2 days ago), which is unacceptable. Let me clean this up.

> can we provide a functionality to manually kick off a perf run in case like this?
I don't have this now. But, I can provide it. Let me clean up and put the benchmarking infra in a repo.

**Comment by jansel** [comment]
float32 perf seems to have recovered: https://github.com/pytorch/torchdynamo/issues/681#issuecomment-1223463076

**Comment by anijain2305** [comment]
float16 results are recovered as well - https://github.com/pytorch/torchdynamo/issues/681#issuecomment-1224739292

Closing the issue.
