### ISSUE TITLE
torchdynamo.config.debug/trace are silently doing nothing on master

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#942]
This is because the log interface changed, but users like me get no errors if they try to use the old idiom.

This is a concrete case of https://github.com/pytorch/torchdynamo/issues/767 

cc @mlazos

**Comment by mlazos** [comment]
#951

**Comment by voznesenskym** [comment]
> #951 should fix this

I'm not sure it will. I'm just making it throw. It's not actually adding back in support for debug or trace.

**Comment by mlazos** [comment]
Hmm I'm getting an infinite recursion instead of an error when I ran [this](https://gist.github.com/mlazos/e540dfdafcf5888439e2729c734e8774)

Can you try it out and let me know if you see this too?

**Comment by voznesenskym** [comment]
Hmm I can check! surprised tests passed if that's not working...  object.__setattr__() should be safe to call! Let me take a look real quick.

**Comment by voznesenskym** [comment]
https://github.com/pytorch/torchdynamo/pull/984
