### ISSUE TITLE
clone_tensor(example_value) is fishy

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#945]
This utility function doesn't preserve strides

```
def clone_tensor(x):
    """Clone the tensor and its gradient"""
    y = x.clone().requires_grad_(x.requires_grad)
    if x.is_leaf and x.grad is not None:
        y.grad = x.grad.clone()
    return y
```

However, we use it in situations where we will immediately record the metadata after, e.g., as seen in `torchdynamo/variables/tensor.py`

```
            # tensor subclasses will not be converted to FakeTensors and need to be cloned
            if not use_fake_tensors or not isinstance(example_value, FakeTensor):
                example_value = clone_tensor(example_value)
            proxy.node.meta["example_value"] = example_value
            specialized_props = cls.specialize(example_value)
```

This means we will specialize stride calls incorrectly. I have a repro for this.

Why are we cloning here at all? It seems fishy.

**Comment by anijain2305** [comment]
Why do we clone?
This allows us to specialize the graph depending on the return value of `TorchVariable` during the bytecode analysis. I think with FakeTensors, we can remove this. But, the code is there as a fallback when FakeTensor has an error.

We could use this clone function instead https://github.com/pytorch/torchdynamo/blob/fc52b39596add70e604b96e2da0e26407c94f149/torchdynamo/utils.py#L263-L282

**Comment by ezyang** [comment]
This causes `PYTORCH_TEST_WITH_DYNAMO=1 python test/test_nn.py -k TestNNDeviceTypeCPU.test_grid_sample_large_index_2d` to fail, though I'm not sure why it doesn't fail on master. Maybe related to https://github.com/pytorch/pytorch/pull/83830

**Comment by ezyang** [comment]
ok patch coming

**Comment by ezyang** [comment]
`clone_input` doesn't work, so I'm waiting on more guidance from the original authors for what to do

**Comment by jansel** [comment]
Could we just have one `clone()` function that preserves both strides and grad?

The reason for cloning is to try to prevent mutation from dynamic_propagation/tracers from leaking into user data.
