### ISSUE TITLE
Dynamo generated warnings interfere with warnings machinery in PyTorch

### ISSUE THREAD

**Issue by ezyang** [pytorch/torchdynamo#948]
we have tests in pytorch like

```
    def test_new_pattern_no_warning(self):
        epochs = 35
        with warnings.catch_warnings(record=True) as ws:
            warnings.simplefilter("always")  # allow any warning to be raised
            scheduler = StepLR(self.opt, gamma=0.1, step_size=3)
            self.assertTrue(len(ws) == 0, "No warning should be raised")
```

if dynamo generates warnings inside of `catch_warnings`, they will get caught by this warning handler and cause this test to fail.

It seems to me that dynamo generated warnings should be sent directly to the warning handler that was active *at the time torchdynamo was enabled*; inner warning handlers inside the dynamo segment should not catch dynamo (which is an "external" force).

**Comment by williamwen42** [comment]
Cannot exactly replicate the observed issue, but made preemptive fixes so that warnings/logging should not interfere with user code.
